'use strict';
(() => {
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const W=1024,H=768,colors=['#a9e867','#68c9f5','#f3d65a','#ee917a'];
const presets=window.TriumphInput.presets;
const orders=['NORMAL','FOLLOW','ATTACK','DEFEND'];
const missions=[
 {name:'LANDING ZONE',brief:'Secure the landing zone. Destroy every alien and nest.',nests:[[710,130],[865,290],[760,530]],rocks:[[390,180,62,60],[560,360,55,70],[410,555,65,55]],flowers:[[615,160],[660,480]]},
 {name:'LOCKED COMPOUND',brief:'Shoot the terminal to unlock the compound. Clear the infestation.',nests:[[830,140],[835,540],[575,345]],rocks:[[460,180,25,330],[460,180,240,25],[460,490,240,25]],gate:[700,205,25,285],terminal:[900,635],flowers:[[755,230],[600,595]]},
 {name:'CANYON PASS',brief:'Push through the rocky pass. Collect support before advancing.',nests:[[850,100],[880,365],[850,600],[600,590]],rocks:[[380,70,100,180],[380,460,100,180],[650,275,100,150]],flowers:[[570,170],[760,480]]},
 {name:'OUTPOST',brief:'Defend the crystal until the attack subsides, then clear remaining aliens.',nests:[[840,100],[860,590],[530,630],[560,80]],rocks:[[340,230,180,20],[340,460,180,20],[320,230,20,250]],crystal:[425,345],hold:90,flowers:[[710,190],[710,520]]},
 {name:'BREEDING GROUNDS',brief:'Crush the evolver plants. Eliminate the breeding nests.',nests:[[610,90],[890,130],[700,350],[900,560],[600,610]],rocks:[[450,250,65,90],[450,500,55,90]],flowers:[[510,170],[820,250],[790,480],[510,640]]},
 {name:'RESEARCH FACILITY',brief:'Activate the terminal. Open the facility and clear every room.',nests:[[830,120],[850,580],[620,350],[870,350]],rocks:[[400,100,25,220],[400,430,25,190],[400,100,530,25],[400,600,530,25],[670,125,25,190],[670,430,25,170]],gate:[670,315,25,115],terminal:[550,560],flowers:[[750,180],[740,535]]},
 {name:'THE SWARM',brief:'The swarm is gathering. Preserve the army and bring in reinforcements.',nests:[[600,90],[880,100],[870,320],[880,600],[600,600]],rocks:[[400,180,70,80],[520,320,70,80],[400,470,70,80]],flowers:[[700,190],[740,450],[510,610]]},
 {name:'CRYSTAL VAULT',brief:'Unlock the vault. Recover the crystal and eliminate the defenders.',nests:[[790,120],[870,540],[630,340]],rocks:[[590,210,250,20],[590,470,250,20],[590,210,20,280]],gate:[840,230,20,240],terminal:[910,630],crystal:[720,350],flowers:[[490,140],[750,580]]},
 {name:'FINAL STAND',brief:'Protect the crystal for two minutes. Destroy all remaining enemies.',nests:[[140,85],[860,85],[860,590],[140,590]],rocks:[[380,240,80,25],[570,240,80,25],[380,470,80,25],[570,470,80,25]],crystal:[510,350],hold:120,flowers:[[300,150],[730,150],[300,550],[730,550]]}
];
const inputState=window.TriumphInput.createState();
const keys=inputState.keys;
let s,seed=2099,background,paused=false,last=0,audio;
const selection=inputState.selection;
const eagleClaims=new Map();

const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const soundCache=new Map();
function sound(handle,volume=.3){if(!window.ORIGINAL_AUDIO)return;try{if(!soundCache.has(handle)){const record=window.ORIGINAL_AUDIO.find(a=>a.kind==='sound'&&a.handle===handle);if(!record)return;soundCache.set(handle,new Audio('assets/audio/'+record.pcm));}const a=soundCache.get(handle).cloneNode();a.volume=volume;a.play().catch(()=>{});}catch{}}
function tone(f=180,d=.035,v=.035){try{audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type='square';o.frequency.value=f;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d);}catch{}}
function unit(x,y,team,type='soldier',id=0){return {x,y,team,type,id,alive:true,angle:team==='human'?0:Math.PI,cool:team==='alien'?2+rnd()*3:rnd()*.6,hp:type==='tank'?8:type==='air'?5:type==='queen'?18:1,order:0,leader:1,respawn:0,weapon:0,weaponTime:0,grenades:3,external:null};}
function makeBackground(){background=document.createElement('canvas');background.width=W;background.height=H;const c=background.getContext('2d');c.fillStyle=s.level===5?'#655e54':'#b2a183';c.fillRect(0,0,W,H);for(let i=0;i<16000;i++){c.fillStyle=['#b7a88a','#aa997a','#a19174','#c0af8d','#96886c'][Math.floor(rnd()*5)];c.fillRect(Math.floor(rnd()*W),Math.floor(rnd()*H),1+rnd()*3,1+rnd()*2);}for(let i=0;i<30;i++){const x=rnd()*W,y=rnd()*H;c.strokeStyle='#938169';c.beginPath();c.ellipse(x,y,10+rnd()*15,4+rnd()*7,0,0,7);c.stroke();}}
function legacyBegin(level=0,merits=0){seed=2099+level;s={level,merits,mode:'briefing',t:0,humans:[],aliens:[],vents:[],bullets:[],effects:[],pickups:[],nests:[],rocks:[],flowers:[],score:[0,0,0,0],kills:0,gate:null,terminal:null,crystal:null,hold:missions[level].hold||0,pickupTimer:14};const m=missions[level];for(let i=0;i<4;i++)s.humans.push(unit(110,280+i*34,'human','commander',i+1));for(let i=0;i<28;i++)s.humans.push(unit(35+rnd()*190,80+rnd()*535,'human'));
 m.nests.forEach(([x,y])=>{s.nests.push({x,y,hp:28,timer:1+rnd()*4});for(let i=0;i<4;i++)s.aliens.push(unit(x-60+rnd()*100,y-50+rnd()*100,'alien'));});s.rocks=m.rocks.map(([x,y,w,h])=>({x,y,w,h}));s.flowers=m.flowers.map(([x,y])=>({x,y,alive:true}));if(m.gate)s.gate={x:m.gate[0],y:m.gate[1],w:m.gate[2],h:m.gate[3],open:false};if(m.terminal)s.terminal={x:m.terminal[0],y:m.terminal[1],active:false};if(m.crystal)s.crystal={x:m.crystal[0],y:m.crystal[1],hp:50,recovered:false};['troops','tank','air','rapid','plasma','grenade'].forEach((type,i)=>s.pickups.push({x:240+(i%2)*70,y:100+i*95,type}));makeBackground();paused=true;keys.clear();}

const original=window.ORIGINAL,sourceRules=window.ORIGINAL_RULES,imageCache=new Map();
function loadImage(src){if(!imageCache.has(src)){const i=new Image();i.src=src;imageCache.set(src,i);}return imageCache.get(src);}
function sprite(...args){return window.TriumphRendering.sprite(ctx,original,s?.t||0,loadImage,...args);}
function originalBegin(level,merits){legacyBegin(level,merits);const m=original.maps[level];document.querySelector('#mission').value=String(level);s.rules=sourceRules?.maps[m.index];s.difficulty=sourceRules?.difficulty[document.querySelector('#difficulty').value]||{bug:4,queen:50,evolutionRollMax:24};s.profile=window.TriumphBalance.originalProfiles.global[document.querySelector('#difficulty').value];s.difficulty={...s.difficulty,bug:s.profile.bugHP,queen:s.profile.queenHP};const waveProfile=window.TriumphBalance.originalProfiles.waves[level+1];s.wave=waveProfile?{...sourceRules.waves[m.index],...waveProfile.settings[document.querySelector('#difficulty').value]}:sourceRules?.waves[m.index];if(s.wave?.normalInterval)s.wave.interval=s.wave.normalInterval;s.waveKills={normal:0,queen:0};s.originalMap=m;s.mask=Uint8Array.from(atob(m.mask),c=>c.charCodeAt(0));s.humans=[];s.aliens=[];s.nests=[];s.flowers=[];s.rocks=[];s.pickups=[];s.gate=null;s.terminal=null;s.crystal=null;s.doors=[];s.terminals=[];s.props=[];s.fires=[];s.cannons=[];s.hold=0;supportLifecycle.initialize(s,window.ORIGINAL_SUPPORT[m.index]);s.pickupClock=1;s.waveRemaining=s.wave?s.wave.normalKills+s.wave.queenKills:0;s.waveClock=0;
window.TriumphVents.initialize(s,m);
const onMap=i=>i.x>10&&i.x<1015&&i.y>35&&i.y<756,instances=m.instances.map(i=>({...i,definition:original.objects[i.object]}));
function actor(i,team,type,id=0){const u=unit(i.x,i.y,team,type,id);u.object=i.object;u.hp=team==='alien'?(type==='queen'?s.difficulty.queen:s.difficulty.bug):type==='tank'?8:1;return u;}
for(let id=1;id<=4;id++){const marker=instances.find(i=>new RegExp(`P${id} Spawn Point`).test(i.definition.name||'')),commander=instances.find(i=>new RegExp(id===1?'^Commander1$':`^Commander ${id}$`).test(i.definition.name||''));const first=instances.find(i=>i.definition.name==='Commander1'&&i.x>0&&i.y>0),origin=instances.find(i=>i.definition.name==='P1 Spawn Point'),offset={x:first&&origin?first.x-origin.x:7,y:first&&origin?first.y-origin.y:15};const explicit=s.rules?.commanderStarts[id];const pos=explicit||(marker?{...marker,x:marker.x+offset.x,y:marker.y+offset.y}:commander)||{x:30,y:280+id*35};const u=actor({...pos,x:Math.max(25,pos.x),y:Math.max(50,pos.y)},'human','commander',id);u.object=explicit?.object||commander?.object||51;u.spawn={x:u.x,y:u.y};s.humans.push(u);}
for(const i of instances){if(!onMap(i)&&!(s.rules?.terminals[i.object]&&i.x>0&&i.x<W&&i.y>0&&i.y<H))continue;const o=i.definition,name=o.name||'';
if(name==='Troop')s.humans.push(actor(i,'human','soldier'));else if(name==='Tank')s.humans.push(actor(i,'human','tank'));else if(name==='Krate Ground Bug'||name==='Krate Ground Bug 2')s.aliens.push(actor(i,'alien','soldier'));else if(name==='Advanced Krate Bug')s.aliens.push(actor(i,'alien','queen'));else if(name==='Egg')s.nests.push({x:i.x,y:i.y,hp:s.profile.nestHP,timer:2+rnd()*7,object:i.object,sourceId:i.handle,breeding:window.TriumphBreeding.create((level+1)*1000003+Math.round(i.x)*1009+Math.round(i.y)*9176+i.object,s.profile.nestRollSuccesses)});else if(name==='growplant')s.flowers.push({x:i.x,y:i.y,alive:true,object:i.object});else if(/^Door \d/.test(name)){const anim=o.animations[0]||Object.values(o.animations)[0],handle=Object.values(anim)[0].frames[0],info=original.images[handle];s.doors.push({x:i.x-info.hx,y:i.y-info.hy,w:info.width,h:info.height,cx:i.x,cy:i.y,object:i.object,open:false,locked:!(s.rules?.doors[i.object]?.initiallyUnlocked??true),durability:s.rules?.doors[i.object]?.durability,damage:0});}else if(/^computer area/.test(name))s.terminals.push({x:i.x,y:i.y,object:i.object,active:false});else if(/^(Small explosive canister|Large explosive drum|Breakable wall)/.test(name)){const handle=Object.values(Object.values(o.animations)[0])[0].frames[0],info=original.images[handle];s.props.push({x:i.x,y:i.y,object:i.object,hp:/wall/.test(name)?12:4,wall:/wall/.test(name),left:i.x-info.hx,top:i.y-info.hy,w:info.width,h:info.height});}else if(name==='cannon')s.cannons.push({x:i.x,y:i.y,object:i.object,occupant:null,cool:0});else if(name==='Crystal')s.crystal={x:i.x,y:i.y,hp:s.profile.crystalHP,object:i.object};else {const type=name==='Ground Reinforcements'?'troops':name==='Airial Reinforcements'?'air':name==='Ground Support'?'tank':name==='BLITZ!'?'blitz':name==='1 Grenade'?'grenade':name==='Auto Gun'?'auto':name==='Plasma Gun'?'plasma':name==='Flame Gun'?'flame':null;if(type)s.pickups.push({x:i.x,y:i.y,type,object:i.object});}}

function bounds(object,x,y){const o=original.objects[object],dir=Object.values(Object.values(o?.animations||{})[0]||{})[0],h=dir?.frames[0]||o?.image,i=original.images[h];return i?{x:x-i.hx,y:y-i.hy,w:i.width,h:i.height}:{x:x-8,y:y-8,w:16,h:16};}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
for(const rule of s.rules?.difficultyCull||[]){if(!(rule.flag===1?s.difficulty.medium:rule.flag===2?s.difficulty.easy:false))continue;const helpers=instances.filter(i=>i.object===rule.helper);for(const list of ['aliens','flowers','props'])s[list]=s[list].filter(a=>a.object!==rule.target||!helpers.some(h=>overlap(bounds(a.object,a.x,a.y),bounds(h.object,h.x,h.y))));}
const retained=window.TriumphBalance.originalProfiles.nests[level][document.querySelector('#difficulty').value];s.nests=s.nests.filter(n=>retained.some(p=>p.id===n.sourceId&&p.x===n.x&&p.y===n.y));
background=loadImage(`assets/maps/${m.index}.png`);missions[level].name=m.name.toUpperCase();missions[level].brief=m.briefing.filter(t=>!t.startsWith('GOOD')).join(' ');for(const o of [51,52,146,151,152,74,53,54,55,56,63,64,65,99,108,547,446,447,448,475])for(const a of Object.values(original.objects[o]?.animations||{}))for(const d of Object.values(a))for(const h of d.frames)loadImage(`assets/images/${h}.png`);
}
function begin(level=0,merits=0){input.reset();eagleClaims.clear();if(original)originalBegin(level,merits);else legacyBegin(level,merits);window.TriumphNavigation?.reset();window.TriumphMusic?.select(s.rules?.music??0);}
// Scenario identity is independent of original level and support-map indices.
const missionLedger={original:0,custom:Object.create(null)};
function rememberMerits(){if(!s)return;if(s.customId)missionLedger.custom[s.customId]=s.merits;else missionLedger.original=s.merits;}
function loadOriginal(level){rememberMerits();begin(level,missionLedger.original);}
function loadCustomMission(id){const m=window.TriumphCustomMissions.resolve(id,document.querySelector('#difficulty').value);if(!m)throw Error('Unknown custom mission: '+id);rememberMerits();begin(m.fixtureMission-1,missionLedger.custom[id]||0);s.customId=id;s.customMission=m;s.profile=null;s.difficulty=sourceRules.difficulty[document.querySelector('#difficulty').value];document.querySelector('#mission').value=id;
 s.rules={...s.rules,minimumTime:0,victoryTerminals:[]};s.wave=null;s.waveRemaining=0;s.vents=[];s.flowers=[];s.crystal=null;
 if(m.objective.rescueSoldiers)s.rescueAcquired=false;else delete s.rescueAcquired;s.customWaves=window.TriumphMissions.createWaves(m);s.customAirPending=!!m.scheduledAir;s.desertMines=[];
 // Custom scenery is independent of the recovered rules/support template.
 if(m.terrainId){const terrain=window.TriumphTerrains[m.terrainId];s.terrainId=terrain.id;s.mask=Uint8Array.from(atob(terrain.mask),c=>c.charCodeAt(0));background=loadImage(terrain.image);s.props=[];s.cannons=[];s.doors=[];s.rocks=[];}
 const make=(x,y,team,type,object,id=0)=>{const u=unit(x,y,team,type,id);u.object=object;u.hp=team==='alien'?s.difficulty.bug:1;if(id)u.spawn={x,y};return u;};
 s.humans=m.commanders.map(([x,y],i)=>make(x,y,'human','commander',[51,91,100,101][i],i+1)).concat(m.soldiers.map(([x,y])=>make(x,y,'human','soldier',52)),m.robots.map(([x,y])=>({...make(x,y,'human','robot',460),hp:7})),m.commandos.map(([x,y])=>make(x,y,'human','commando',52)),(m.snipers||[]).map(([x,y])=>make(x,y,'human','snow-sniper',52)));
 s.aliens=m.bugs.map(([x,y])=>make(x,y,'alien','soldier',151));
 s.nests=m.nests.map(([x,y])=>({x,y,object:74,hp:sourceRules.eggHealth||50,customInterval:m.nestInterval,...(m.nestBudget===undefined?{}:{birthsRemaining:m.nestBudget}),timer:m.nestInterval||2+rnd()*7,breeding:!m.nestInterval&&document.querySelector('#difficulty').value==='normal'?window.TriumphBreeding.create(2000006+x*1009+y*9176+74):null}));
 if(m.crawlers){for(const [i,[x,y]] of m.crawlers.entries()){const c=spawnDesertRider('convoy-crawler',x,y,m.escortRoutes[i].map(([x,y])=>({x,y})));Object.assign(c,{hp:2,disabled:true,rescue:true,convoyNumber:i+1});}const scoutPoints=m.scouts||[[130,260],[130,460]],mechanicPoints=m.mechanics||[[150,350],[150,420]],guardPoints=m.guardPoints?m.guardPoints.slice(0,m.guards):Array.from({length:m.guards},(_,i)=>[85+(i%2)*40,470+Math.floor(i/2)*34]);for(const [type,points] of [['rider-scout',scoutPoints],['field-mechanic',mechanicPoints],['dune-guard',guardPoints]])for(const [x,y] of points)spawnDesertRider(type,x,y);for(const [x,y] of m.worms)spawnDesertWorm(x,y);}
 s.terminals=m.terminals.map(t=>({...t,active:false,used:false}));s.pickups=[...m.support,...m.weapons].map(p=>({...p}));
 window.TriumphJungleAmbush?.initialize(s,m);
 window.TriumphVolcanicHazards?.initialize(s);
 if(m.vents)window.TriumphVents?.initialize(s,m);
}
function restartMission(){if(s.customId)loadCustomMission(s.customId);else begin(s.level,s.merits);}
function currentMission(){return s.customMission||missions[s.level];}
function staticBlocked(x,y){if(!s.mask)return false;x=Math.floor(x);y=Math.floor(y);if(x<0||x>=W||y<32||y>=H)return true;const n=y*W+x;return !!(s.mask[n>>3]&(1<<(n&7)));}
function interact(u,only=null){if(!s.originalMap)return false;let used=false;for(const t of s.terminals)if((!only||only===t)&&dist(u,t)<35){const rule=s.rules?.terminals[t.object];sound(rule?.sound||46,.45);t.used=true;if(rule?.setsFlag||s.customMission?.objective.activate?.includes(t.key))t.active=true;used=true;for(const d of s.doors)if(rule?.unlocks.includes(d.object))d.locked=false;}for(const d of s.doors)if((!only||only===d)&&!d.destroyed&&!d.locked&&dist(u,{x:d.cx,y:d.cy})<45&&s.t-(d.lastUse||-10)>.5){d.open=!d.open;d.lastUse=s.t;sound(37,.45);used=true;}return used;}
function blocked(x,y,canOpenDoors=false){if(s.props?.some(p=>p.wall&&p.hp>0&&x>p.left&&x<p.left+p.w&&y>p.top&&y<p.top+p.h))return true;if(staticBlocked(x,y))return true;if(s.doors?.some(d=>!d.destroyed&&!d.open&&(!canOpenDoors||d.locked)&&x>d.x-3&&x<d.x+d.w+3&&y>d.y-3&&y<d.y+d.h+3))return true;return [...s.rocks,...(s.gate&&!s.gate.open?[s.gate]:[])].some(r=>x>r.x-6&&x<r.x+r.w+6&&y>r.y-6&&y<r.y+r.h+6);}
const humanRouteBlocked=(x,y)=>blocked(x,y,true);
const riderRouteBlocked=(x,y)=>x<0||x>=W||y<36||y>=H||blocked(x,y,true);
const navigationRevision=()=>s.level+':'+(s.doors||[]).map(d=>[Number(d.open),Number(d.locked),Number(d.destroyed)].join(',')).join(';')+':'+(s.props||[]).filter(p=>p.wall&&p.hp>0).length;
function move(u,dx,dy,dt,speed){if(window.TriumphDesertRiders.isRider(u)){const len=Math.hypot(dx,dy);if(len)window.TriumphDesertRiders.travel(u,{x:u.x+dx/len*speed*dt,y:u.y+dy/len*speed*dt},speed,dt,wormBlocked);return;}const len=Math.hypot(dx,dy);if(!len)return;dx/=len;dy/=len;u.angle=u.team==='human'&&['soldier','commander','robot','commando'].includes(u.type)?diagonal(Math.atan2(dy,dx)):Math.atan2(dy,dx);u.movingUntil=s.t+.1;if(u.x<12||u.x>W-12||u.y<38||u.y>H-16){u.x+=dx*dt*speed;u.y+=dy*dt*speed;return;}const x=Math.max(12,Math.min(W-12,u.x+dx*dt*speed)),y=Math.max(38,Math.min(H-16,u.y+dy*dt*speed));if(!blocked(x,u.y))u.x=x;if(!blocked(u.x,y))u.y=y;}
function navigate(u,dx,dy,dt,speed){if(u.team==='human'&&u.type==='robot'&&u.cannon===undefined)speed*=window.TriumphBalance.groundRobotMovementMultiplier;if(u.team==='human')for(const d of s.doors||[])if(!d.open&&!d.locked&&!d.destroyed&&dist(u,{x:d.cx,y:d.cy})<45){d.open=true;d.lastUse=s.t;sound(37,.2);}const goal={x:u.x+dx,y:u.y+dy};if(window.TriumphNavigation){const revision=navigationRevision();const next=window.TriumphNavigation.step(u,goal,window.TriumphDesertRiders.isRider(u)?window.TriumphDesertRiders.footprint(riderRouteBlocked,window.TriumphDesertRiders.radius(u)):u.team==='human'?humanRouteBlocked:blocked,revision);if(next){move(u,next.x-u.x,next.y-u.y,dt,speed);return;}}const angle=Math.atan2(dy,dx),step=Math.max(12,speed*dt);for(const offset of [0,.4,-.4,.85,-.85,1.4,-1.4,2,-2]){const a=angle+offset;if(!blocked(u.x+Math.cos(a)*step,u.y+Math.sin(a)*step)){move(u,Math.cos(a),Math.sin(a),dt,speed);return;}}}
function cannonAngle(angle){return Math.round(angle/(Math.PI/8))*(Math.PI/8);}
function diagonal(angle){return Math.round(angle/(Math.PI/4))*(Math.PI/4);}
function cardinal(angle){return Math.round(angle/(Math.PI/2))*(Math.PI/2);}
function visible(a,b){
 if(b.type==='desert-worm'&&!window.TriumphDesertWorm.exposed(b))return false;
 // Weapon sight tests the projectile centerline to the target's hittable edge.
 // Walking clearance includes body padding and excludes boundary rows, which
 // incorrectly hid nests at y=752 and enemies standing beside solid terrain.
 if(b.hp!==undefined||b.team){const length=dist(a,b),radius=s.nests?.includes(b)?26:b.type==='queen'||b.type==='tank'?17:b===s.crystal?14:8,travel=Math.max(0,length-radius+1),steps=Math.ceil(travel/4);for(let i=1;i<=steps;i++){const f=travel/length*i/steps;if(blocked(a.x+(b.x-a.x)*f,a.y+(b.y-a.y)*f))return false;}return true;}
 return window.TriumphNavigation?window.TriumphNavigation.line(a,b,blocked):!blocked((a.x+b.x)/2,(a.y+b.y)/2);
}
const specialistRules=window.TriumphBalance.specialistRules;
const infantryType=u=>['soldier','commando','snow-sniper','rider-scout','dune-guard','field-mechanic'].includes(u?.type);
const weaponUserType=u=>['soldier','commando','snow-sniper'].includes(u?.type);
const burstRules=window.TriumphBalance.burstRules;
const tankSweepRules=window.TriumphBalance.tankSweepRules;
const {enemyFireDelay,trackBurst,burstReady,finishBurstShot,tankGroup,aimTank,aimCannon,humanFiringLane,aimHuman,fire,burst,sprayDensity}=window.TriumphCombat.create({getState:()=>s,burstRules,tankSweepRules,cannonSweepRules:window.TriumphBalance.cannonSweepRules,rnd,visible,dist,blocked,navigate,cardinal,diagonal,cannonAngle,getDifficulty:()=>document.querySelector('#difficulty').value,bugFireBases:window.TriumphBalance.bugFireBases,specialistRules,desertRiders:window.TriumphDesertRiders,originalAudio:()=>window.ORIGINAL_AUDIO,sound,tone,emitAcousticEvent:(origin,r)=>emitAcousticEvent(origin,r)});
function stepProjectiles(dt){window.TriumphProjectiles.step(s,dt,{W,H,blocked,dist,damage,destroyProp,wormExposed:window.TriumphDesertWorm.exposed,sound,tone,burst,emitAcousticEvent:(origin,r)=>emitAcousticEvent(origin,r)});}

function nearest(u,list,max=Infinity){let best=null,d=max;for(const a of list){if(a.alive===false||a.hp<=0)continue;const t=dist(u,a);if(t<d){best=a;d=t;}}return best;}

function bugArrival(x,y){const point={x:Math.max(16,Math.min(W-16,x)),y:Math.max(44,Math.min(H-24,y))};return window.TriumphNavigation?.destination(point,point,blocked)||point;}
function wormBlocked(x,y){return x<0||x>=W||y<36||y>=H||blocked(x,y);}
function wormRouteBlocked(x,y){return !window.TriumphDesertWorm.clear(x,y,wormBlocked);}
function spawnDesertRider(type,x,y,route=[]){const u=window.TriumphDesertRiders.create(type,x,y,wormBlocked,route);if(u)s.humans.push(u);return u;}
function spawnDesertWorm(x,y){const u=window.TriumphDesertWorm.create(x,y,wormBlocked);if(u)s.aliens.push(u);return u;}
function spawnGroundBug(x,y){({x,y}=bugArrival(x,y));const special=rnd()<specialistRules.redbug.spawnChance,u=unit(x,y,'alien',special?'redbug':'soldier');u.hp=special?specialistRules.redbug.hp:s.difficulty?.bug||4;s.aliens.push(u);return u;}
function alertPack(sourceBug,threat,radius=160){
 if(!s||!s.aliens||!threat||threat.alive===false)return;
 for(const other of s.aliens){
  if(!other.alive||other===sourceBug||other.type==='desert-worm')continue;
  if(dist(other,sourceBug)<=radius||dist(other,threat)<=radius){
   other.ai=other.ai||{};
   if(!other.ai.target||!other.ai.target.alive||dist(other,threat)<dist(other,other.ai.target)){
    other.ai.target=threat;other.ai.boredUntil=0;other.ai.hesitateUntil=0;other.ai.focusUntil=Math.max(other.ai.focusUntil||0,s.t+3);
    other.intent={mode:'approach',until:s.t+2+rnd()*2,goal:{x:threat.x+(rnd()-.5)*20,y:threat.y+(rnd()-.5)*20}};
    other.angle=Math.atan2(threat.y-other.y,threat.x-other.x);
   }
  }
 }
}
function emitAcousticEvent(origin,radius=280){
 if(!s||!s.aliens||!origin)return;
 const soundX=origin.x,soundY=origin.y;
 for(const a of s.aliens){
  if(!a.alive||a.type==='desert-worm')continue;
  const d=dist(a,{x:soundX,y:soundY});
  if(d<=radius&&visible(a,{x:soundX,y:soundY})){
   a.ai=a.ai||{};a.ai.boredUntil=0;a.ai.hesitateUntil=0;
   a.angle=Math.atan2(soundY-a.y,soundX-a.x);
   const perceiveRange=a.type==='redbug'?specialistRules.redbug.sight:175;
   const target=perceive(a,s.humans.filter(u=>u.alive),perceiveRange);
   if(target){
    a.ai.target=target;a.ai.focusUntil=Math.max(a.ai.focusUntil||0,s.t+2);
    a.intent={mode:'approach',until:s.t+2+rnd()*2,goal:{x:target.x,y:target.y}};
    alertPack(a,target,160);
   }else{
    a.intent={mode:'approach',until:s.t+3+rnd()*2,goal:{x:soundX,y:soundY}};
   }
  }
 }
}
function kill(u,owner){if(!u.alive||(u.type==='desert-worm'&&!window.TriumphDesertWorm.exposed(u)))return;cancelSupply(u);u.alive=false;sound(u.team==='alien'?(u.type==='queen'?20:5):6,.22);burst(u.x,u.y,10,u.team==='alien'?'#b57068':'#7d3f35');if(u.team==='alien'){s.kills++;if(s.waveKills)s.waveKills[u.type==='queen'?'queen':'normal']++;if(owner)s.score[owner-1]+=10;if(u.type==='queen')for(let i=0;i<4;i++){spawnGroundBug(u.x+rnd()*30-15,u.y+rnd()*30-15);}}if(u.type==='commander'){u.respawn=10;if(u.id===inputState.activeCommander)inputState.drag=null;}}
function damage(u,n,owner){if(!u.alive||u.shieldUntil>s.t||(u.type==='desert-worm'&&!window.TriumphDesertWorm.exposed(u)))return;u.hp-=n;if(u.team==='alien'){let threat=null;if(owner)threat=s.humans.find(h=>h.id===owner&&h.alive);if(!threat)threat=nearest(u,s.humans.filter(h=>h.alive));if(threat){u.ai=u.ai||{};u.ai.target=threat;u.ai.boredUntil=0;u.ai.hesitateUntil=0;u.ai.focusUntil=Math.max(u.ai.focusUntil||0,s.t+3);alertPack(u,threat,160);}}if(u.hp<=0)kill(u,owner);}
function destroyProp(p){if(p.destroyed)return;p.destroyed=true;burst(p.x,p.y,p.wall?20:65);sound(p.wall?41:25,.5);if(!p.wall){s.fires.push({x:p.x,y:p.y,until:s.t+4,object:274});for(const a of s.aliens)if(a.alive&&dist(a,p)<65)damage(a,8,0);for(const n of s.nests)if(n.hp>0&&dist(n,p)<75){n.hp-=12;emitAcousticEvent(n,280);}for(const q of s.props)if(q!==p&&q.hp>0&&dist(q,p)<60){q.hp=0;destroyProp(q);}}emitAcousticEvent(p,280);}
function grenade(u){if(!u.alive||u.grenades<=0)return;u.grenades--;const x=u.x+Math.cos(u.angle)*90,y=u.y+Math.sin(u.angle)*90;burst(x,y,58);emitAcousticEvent({x,y},280);for(const a of s.aliens)if(a.alive&&dist(a,{x,y})<75)damage(a,12,u.id);for(const n of s.nests)if(n.hp>0&&dist(n,{x,y})<80){n.hp-=15;emitAcousticEvent(n,280);if(n.hp<=0)burst(n.x,n.y,32);}for(const p of s.props||[])if(p.hp>0&&dist(p,{x,y})<80){p.hp-=15;if(p.hp<=0)destroyProp(p);}sound(23,.5);if(!window.ORIGINAL_AUDIO)tone(65,.25,.06);}


const supportLifecycle=window.TriumphSupportLifecycle.create({getState:()=>s,original,W,H,random:rnd,paths:window.TriumphSupport,navigation:window.TriumphNavigation,blocked,staticBlocked,unit,infantryType,assignRally:u=>assignRally(u),sound,burst,dist,kill,damage,fire,emitAcousticEvent:(origin,r)=>emitAcousticEvent(origin,r)});
function groundArrival(...args){return supportLifecycle.groundArrival(...args);}
function flightEntersMap(...args){return supportLifecycle.flightEntersMap(...args);}
function addTroop(...args){return supportLifecycle.addTroop(...args);}
function reinforcementStatus(...args){return supportLifecycle.reinforcementStatus(...args);}
function reinforcementRule(...args){return supportLifecycle.reinforcementRule(...args);}
function reinforce(...args){return supportLifecycle.reinforce(...args);}
function supportExplosion(...args){return supportLifecycle.supportExplosion(...args);}
function updateSupport(...args){return supportLifecycle.updateSupport(...args);}
function spawnPickupRoll(roll){if(s.customMission&&!s.customMission.randomPickups)return;const rules=window.ORIGINAL_PICKUPS?.[s.originalMap?.index];if(!rules)return;const troops=s.humans.filter(u=>u.alive&&infantryType(u)).length,compare=window.TriumphSupport.compare;for(const rule of rules.cases){if(rule.type==='growplant'&&(document.querySelector('#difficulty').value!=='normal'||!(rule.globals||[]).every(g=>compare(s.support.globals[g.index]||0,g.comparison,g.value))))continue;if(s.t<rule.minimumTime||!rule.checks.every(c=>compare(c.variable===0?roll:rules.secondary,c.comparison,c.difficulty?s.difficulty[c.difficulty]:c.value)))continue;if(rule.count&&!compare((rule.type==='growplant'?s.flowers.filter(f=>f.alive):s.pickups.filter(p=>p.type===rule.type)).length,rule.count.comparison,rule.count.value))continue;if(rule.troops){const tokens=rule.troops.tokens,limit=tokens.length===1?tokens[0].value:s.rules.maxAliens*tokens.at(-1).value;if(!compare(troops,rule.troops.comparison,limit))continue;}if(['troops','air','tank','blitz'].includes(rule.type)&&!reinforcementRule(rule.type))continue;const helper=s.supportHelpers[rule.parent];let point=helper?{x:helper.x+rule.x,y:helper.y+rule.y}:null;const clear=p=>p&&p.x>20&&p.x<W-20&&p.y>45&&p.y<H-20&&!blocked(p.x,p.y)&&!blocked(p.x-8,p.y-8)&&!blocked(p.x+8,p.y+8);if(!clear(point)){point=null;for(let attempt=0;attempt<64;attempt++){const p={x:24+rnd()*(W-48),y:48+rnd()*(H-72)};if(clear(p)){point=p;break;}}}if(point){if(rule.type==='growplant')s.flowers.push({...point,alive:true,object:rule.object});else s.pickups.push({...point,type:rule.type,object:rule.object});}}}
function updatePickupSpawns(dt){if(s.customMission&&!s.customMission.randomPickups)return;const rules=window.ORIGINAL_PICKUPS?.[s.originalMap?.index];if(!rules)return;s.pickupClock-=dt;while(s.pickupClock<=0){s.pickupClock+=rules.interval;spawnPickupRoll(Math.floor(rnd()*rules.range));}}
function hasRespawnSupport(...args){return supportLifecycle.hasRespawnSupport(...args);}
function respawnCommander(...args){return supportLifecycle.respawnCommander(...args);}
const pickupWeapon=type=>({auto:0,rapid:1,flame:1,plasma:2})[type];
const duplicateCommanderWeapon=(u,p)=>u.type==='commander'&&pickupWeapon(p.type)!==undefined&&u.weapon===pickupWeapon(p.type);
function pickup(u,p){if(duplicateCommanderWeapon(u,p))return false;if(['blitz','troops','tank','air'].includes(p.type)){if(!reinforce(p.type,p))return false;}else if(p.type==='grenade')u.grenades=Math.min(8,u.grenades+1);else {u.weapon=['rapid','flame'].includes(p.type)?1:p.type==='auto'?0:2;u.weaponTime=Infinity;}if(u.id)s.score[u.id-1]+=25;burst(p.x,p.y,15,'#ffed7b');tone(650,.1);return true;}
const bugFireBases=window.TriumphBalance.bugFireBases;


function showUnits(){
 input.openModal('units');
 const difficulty=document.querySelector('#difficulty').value,h=s.difficulty||sourceRules.difficulty[difficulty],base=bugFireBases[difficulty]||3.8;
 const burstText=type=>{const r=burstRules[type];return `${r.min}–${r.max} shots per burst; ${r.restMin}–${r.restMax} s rest; ${r.delayMin}–${r.delayMax} s reaction delay.`;};
 const rows=[
 ['Commander','Commander1',1,'Bullet: 1; grenade: 12 to bugs, 15 to nests','0.25 s (4 shots/s); flame: 0.18 s','Keyboard / AI fires in eight directions, including diagonals; selected mouse commander aims freely. Moves at 85 px/s, commands nearby troops and collects weapons/support. Returns after 10 s if army or incoming support remain; return shield lasts 0.6 s. Grenades: 0.33 s cooldown, up to 8 carried.'],
 ['Infantry','Troop',1,'1 per bullet','0.38 s (2.63 shots/s); Defend: 0.20 s (5/s)',burstText('soldier')+' Eight-direction fire (including diagonals); moves into an unobstructed weapon-range lane and fires only when aligned. Defend holds and waits for a legal lane. Sees visible enemies within 245 px. Normal patrols, Follow stays with its commander, Attack advances, Defend holds position. Collects weapons/eagles and occupies cannons. Attack-moving soldiers make short route-side detours: eagles before turrets in clear areas, turrets before combat when enemies are nearby. When clear of enemies, temporarily seeks usable eagles within 250 px, then returns. Combat pauses the trip; player orders cancel it.'],
 ['Commando','Troop',1,'1 per bullet','0.38 s (2.63 shots/s); flame: 0.18 s',burstText('commando')+' Blue bandana. Fires in eight directions, including diagonals. Delivered by blue-eagle air and infiltration support; retains normal infantry orders, sight, pickups, health and damage, including automatic eagle trips when no enemies are in range.'],
 ['Tank','Tank',8,'5 per bullet','0.20 s (5 shots/s)',burstText('tank')+' Sweeps a locked 25–80° arc toward the densest visible bug group within 300 px; narrow for tight groups, wider for spread groups. Alternates sweep direction between bursts. Falls back to a nest when no bugs are visible. Uses squad orders and terrain routing. Right-click an enemy to focus a 15° sweep across that target. Walls stop shots.'],
 ['Ground robot','ground bot',7,'1 per bullet','0.38 s; Defend: 0.20 s; flame: 0.18 s',burstText('robot')+' Moves 50% faster than its previous recreation speed (54 px/s travel; 36 px/s patrol). Uses squad orders, terrain routing and eight-direction fire. Detects enemies within 245 px.'],
 ['Krate ground bug','Krate Ground Bug',h.bug,'Spit: 1; melee: 1',`${base.toFixed(1)}–${(base+1.6).toFixed(1)} s spit; melee: 1 s`,'Sees 175 px with clear sight. Spits in its facing direction ±11.25°. Randomly approaches, wanders or pauses. Focus lasts 1.5–3.5 s, then breaks for 1–3 s; may skip shooting. Evolves at a growplant.'],
 ['Ceiling / vent bug','alien shadow','Untargetable aloft','Ground bug after landing','Contact roll every 0.1 s','Missions 7–9: ceiling shadows cross walls and drop beside commanders or infantry. Drop and jump animations cannot be attacked; landed bugs fight normally. In missions 7–8, ordinary ground bugs can return into vents on a 5% roll every 2 s, while ceiling population allows. Clear every ceiling and transition bug to finish the mission.'],
 ['Desert charging worm (custom opt-in)',null,16,'Charge: 2 per ground target','1.2 s warning; 1.5 s recovery','Beneath the Dunes custom mission. Sand ripples: underground and immune. Exposed gold warning locks a horizontal or vertical lane; sidestep before the 300 px/s charge (260 px maximum). Walls stop its 24 px body. Exposed during charge and recovery; no spit, evolution or wall damage.'],
 ['Rider scout (custom opt-in)',null,1,'1 per bullet','0.6 s; evade rest 2.5 s','Beneath the Dunes custom mission. Eight-direction rifle, 180 px sight. Fixed kit; no weapon/eagle collection or cannon mounting. Shared troop orders, focus, force-move and door/terminal use. Automatically retreats 38 px at 100 px/s from visible ground bugs within 62 px; terrain blocks evasion.'],
 ['Dune guard (custom opt-in)',null,1,'Five pellets, 1 each','1.1 s','Beneath the Dunes custom mission. Eight-direction shotgun, 30 degree total arc, 120 px range; exactly five pellets. Fixed kit; no pickups or cannon mounting; shared troop movement/focus/use orders.'],
 ['Field mechanic (custom opt-in)',null,1,'Rifle 1; repair 0.5 HP/s','0.6 s rifle','Beneath the Dunes custom mission. Eight-direction rifle, 180 px sight. Repairs one living, damaged nearby tank, ground robot or crawler within 62 px with clear sight, up to its normal health cap. Fixed kit; no pickups or cannon mounting; shared troop movement/focus/use orders.'],
 ['Convoy crawler (custom opt-in)',null,6,'Mine: 4 to exposed ground enemies','2 s evade rest; four mines','Beneath the Dunes custom mission. Route travel 30 px/s. Beneath the Dunes crawlers start disabled at 2/6 HP: full repair permanently unlocks travel; keep a living ground escort within 110 px with clear sight. Full 17 px footprint; reacts once to each locked worm lane, evading 32 px on both axes at 100 px/s if the full sweep is clear. After completing evasion drops a mine at its departure point; arms after 0.65 s, expires after 30 s. Mines trigger within 22 px, blast 38 px, terrain blocks damage; no friendly or underground damage. No shield during evasion.'],
 ['Red Krate bug','Krate Ground Bug',specialistRules.redbug.hp,'Spit: 1; melee: 1',`${specialistRules.redbug.fireMin}–${specialistRules.redbug.fireMax} s spit; melee: 1 s`,`Red abdomen band. ${specialistRules.redbug.sight} px sight, blocked by terrain. ${specialistRules.redbug.spawnChance*100}% chance among newly spawned ground bugs from nests, queens and waves. Fixed health/cooldown across difficulties; normal facing cone and randomized behavior. Can evolve into a normal queen.`],
 ['Advanced Krate / queen','Advanced Krate Bug',h.queen,'Spit: 1; melee: 1',`${(base+.4).toFixed(1)}–${(base+2).toFixed(1)} s spit; melee: 1 s`,'Same facing cone and distracted perception as ground bugs; moves more slowly. Spawns one bug every 7 s below the population cap; releases four when killed.'],
 ['Egg / nest','Egg',s.profile?.nestHP||sourceRules.eggHealth||50,'No direct damage',s.customMission?.nestInterval?`Spawn: ${s.customMission.nestInterval} s`:s.profile?`${s.profile.nestRollSuccesses}% opportunity / 0.5 s; birth after 1.8 s`:difficulty==='normal'?'4% opportunity / 0.5 s; birth after 1.8 s':`Spawn: ${(5/(window.TriumphBalance.motionMultipliers[difficulty])).toFixed(1)}–${(9/(window.TriumphBalance.motionMultipliers[difficulty])).toFixed(1)} s`,'Stationary breeding site, spawning ground bugs below the population cap. Original missions: first roll at 0.5 s; 2.4 s busy phase on every setting. Custom missions retain their own cadence. Destroy to stop breeding.'],
 ['Growplant / evolver','growplant','Consumed on contact','None','No attack','A touching ground bug becomes a full-health queen. Commanders consume it on contact to prevent evolution. Normal regenerates it in missions 1–3 on item rolls 22–24, while at most three live plants exist before creation. Placed plants elsewhere remain. Not a bullet-damage target.'],
 ['Troop carrier','Troop Carrier','Not damageable','None','Drops: 1 troop/s while stopped','Follows recovered carrier paths and unloads below the population cap, stopping for at least 5 seconds to deliver a squad. Blocks bug projectiles without taking damage. Incoming support allows commanders to return. Unloaded soldiers attack-move to the nearest reachable rally flag when one exists.'],
 ['Air support','Air Support','Not damageable','Bullet: 1; bomb: 12 to bugs, 2 to nests','Gun: 0.33 s; bomb/drop: 1 s','Flies a straight pass, shoots along its flight direction, bombs nearby enemies and drops commandos over open terrain below the cap. Leaves after its pass. Commandos ignore rally flags, including Blitzkrieg drops.'],
 ['Plasma cannon','cannon','Operator: 1; cannon not damageable','1 direct + six 1-damage sparks','Operator: 0.38 s; Defend: 0.20 s',burstText('soldier')+' Infantry occupies this stationary gun. Detects visible targets within 360 px, retains 16 equally spaced directions (22.5°) visually with either infantry or commando operators. Each burst locks its target center, sweeps smoothly across a random total 0–15° arc, and reverses direction next burst. Commando operators retain 5–7 shots, 0.8–1.2 s rest and 0.2–0.4 s reaction. No armor for operator; attack-move dismounts it.'],
 ['Crystal','Crystal',s.profile?.crystalHP||sourceRules.crystalHealth||7,'None','No attack','Mission objective. Bug bullets/melee each remove 1 HP; destruction loses the mission. Recovery/extraction depends on the mission.'],
 ['Canister / explosive drum','Small explosive canister',4,'Explosion: 8 to bugs, 12 to nests','One explosion','Can chain nearby containers. Leaves fire for 4 s; touching bugs take 1 damage each simulation update. Friendly units and commanders are immune.'],
 ['Breakable wall','Breakable wall',12,'None','No attack','Blocks movement and shots until destroyed.'],
 ['Door','Door','Durability: 5, 15 or indestructible','None','No attack','Closed doors block movement and shots. Terminals unlock linked doors; troops open unlocked doors nearby. Bug bullets remove 1 durability per hit from destructible doors.'],
 ['Terminal','computer area','Not damageable','None','No attack','Operate nearby with Fire, or double right-click with troops selected to send them to activate it. Unlocks linked doors or satisfies mission objectives.']
 ];
 const image=name=>{const o=Object.values(original?.objects||{}).find(o=>o.name===name||o.name?.startsWith(name)),a=Object.values(o?.animations||{})[0],d=Object.values(a||{})[0],handle=d?.frames?.[0]??o?.image;return handle===undefined?'':`<img src="assets/images/${handle}.png" alt="" loading="lazy">`;};
 document.querySelector('#units-context').textContent=`${currentMission().name} · Firing difficulty: ${difficulty} · Bug HP: ${h.bug}, queen HP: ${h.queen}. Health is set at mission start; changing difficulty restarts the mission.${s.customMission?.profile?` Custom ${s.customMission.profile}: ${s.customMission.guards===undefined?s.customMission.soldiers.length+s.customMission.commandos.length:s.customMission.guards+4} starting infantry; ${s.nests.length} nests. ${s.customWaves.arrivals.length} finite arrivals.${s.customMission.nestInterval?` Nest birth interval: ${s.customMission.nestInterval}s.`:''}`:''}${s.customMission?.role==='expedition'?' Whiteout Signal: activate station relay, acquire three soldiers within 70px when three army slots are free, extract one designated living survivor at west pad (80px). Three finite yellow eagle caches provide carrier reinforcements. Party loss after acquisition or army exhaustion loses; enemies may remain.':s.customMission?.role==='capital-defense'?' District Twelve: activate both transit terminals, hold 120 seconds, wait for three scheduled commandos at 70 seconds and all support landing, then clear every finite nest birth and arrival. Empty nests may remain. Two finite yellow eagles; last noncommander loss fails immediately.':s.customMission?.role==='harbor-defense'?` Harbor Watch: hold 120 seconds, exhaust or destroy four finite nests, emit all ${s.customWaves.arrivals.length} arrivals, then clear bugs. Empty nests need not be destroyed. Three finite yellow troop eagles; full cap retains pickup. Losing the last noncommander fails even with support inbound.`:s.customMission?.role==='defense'?' Last Convoy: hold for 120 seconds, emit all ${s.customWaves.arrivals.length} scheduled arrivals and clear enemies with a living noncommander. The last noncommander dying causes defeat even with support inbound.':s.customMission?.role==='infiltration'?' Silent Return: unlock access, activate the laser, then return every living ground human to the extraction zone with a noncommander. At 20s three friendly aircraft from the north drop one commando each in three tight parallel columns with about one soldier sprite of clear horizontal space. Return them too; wait for the schedule and all support arrivals. Enemies and nests may remain.':''}`;
 if(s.customMission)document.querySelector('#units-context').textContent+=' Finite eagle caches: '+s.customMission.support.map(p=>p.type).join(', ')+'; no refill. Custom infantry support waits at full soldier/commando cap including pending landing drops. Carrier unloads only into free slots; specialists, crawlers, tanks and robots retain their existing cap convention.';
 document.querySelector('#unit-cards').innerHTML=rows.map(([name,obj,hp,damage,rate,behavior])=>`<article class="unit-card ${name==='Commando'?'commando-card':name==='Red Krate bug'?'redbug-card':''}"><h3>${image(obj)}${name}</h3><dl><dt>HP</dt><dd>${hp}</dd><dt>Damage</dt><dd>${damage}</dd><dt>Cooldown</dt><dd>${rate}</dd><dt>Defense</dt><dd>No armor / damage reduction</dd></dl><p>${behavior}</p></article>`).join('')+`<article class="unit-card weapons"><h3>Weapons & combat rules</h3><p>Rally flags: yellow ground, bronze support and Blitzkrieg soldier/tank/robot arrivals attack-move to the nearest reachable flag by terrain route distance, then hold nearby. Commandos are excluded. Player orders override rally orders; deleting a flag affects future arrivals.</p><p>Auto gun: 1 damage, 290 px/s, up to 638 px travel. Flame: 1 damage, 0.18 s cooldown (5.56 shots/s), up to 145 px. Plasma: 1 direct damage + six 1-damage sparks on impact; commander cooldown 0.25 s, infantry uses its order cooldown; up to 319 px. Each spark can hit separately. Bug spit: 120 px/s, up to 264 px travel; target detection is 175 px for normal bugs and 200 px for red bugs.</p><p>Walls stop shots and block sight. Bullets hit the opposing team. Commander grenades and support bombs hurt bugs and nests; exploding containers and their fire hurt enemies only. No armor, accuracy stat or defense roll exists. Return shields briefly protect commanders; carriers and aircraft have no damageable health pool. Listed shot rates apply within a burst. Infantry, commandos, robots and tanks rest between bursts, with independently randomized reaction delays. Losing a target ends its burst; reacquiring adds a delay, and switching targets never cancels a rest period. Commanders and aircraft retain continuous fire. AI may also hesitate, skip attacks or lack a firing lane.</p></article>`;
 document.querySelector('#unit-guide').showModal();
}
document.querySelector('#units').onclick=showUnits;
document.querySelector('#units-close').onclick=()=>document.querySelector('#unit-guide').close();
document.querySelector('#unit-guide').onclose=()=>{input.closeModal('units',true);};
function perceive(u,items,range=210){const hostile=u.team==='alien';if(hostile)range=Math.min(range,u.type==='redbug'?specialistRules.redbug.sight:175);else range=Math.max(range,u.type==='snow-sniper'?480:u.weapon===2?319:u.type==='tank'?300:u.type==='dune-guard'?120:['rider-scout','field-mechanic'].includes(u.type)?180:u.weapon===1?145:245);if(!u.ai)u.ai={nextScan:s.t+(hostile?.8+rnd()*1.2:.1+rnd()*.2),target:null};const ai=u.ai;if(ai.target&&(ai.target.alive===false||ai.target.hp<=0||dist(u,ai.target)>range||!visible(u,ai.target)))ai.target=null;if(hostile&&ai.target&&s.t>ai.focusUntil){ai.target=null;ai.boredUntil=s.t+1+rnd()*2;ai.nextScan=ai.boredUntil;}if(hostile&&s.t<(ai.boredUntil||0))return null;if(s.t>=ai.nextScan){ai.nextScan=s.t+(hostile?1+rnd()*1.4:.3+rnd()*.4);const isSpray=!hostile&&(u.weapon===1||u.type==='dune-guard');const seen=items.filter(a=>(a.alive||a.hp>0)&&dist(u,a)<range&&visible(u,a)).map(a=>{if(isSpray&&sprayDensity){const r=u.weapon===1?145:120,arc=u.weapon===1?Math.PI/8:Math.PI/12;a.sprayDensity=sprayDensity(u,Math.atan2(a.y-u.y,a.x-u.x),arc,r);}return a;}).sort((a,b)=>{if(isSpray&&(b.sprayDensity||0)!==(a.sprayDensity||0))return (b.sprayDensity||0)-(a.sprayDensity||0);const cost=p=>dist(u,p)+(hostile||['soldier','commander','robot','commando','rider-scout','dune-guard','field-mechanic','snow-sniper'].includes(u.type)?0:Math.min(Math.abs(p.x-u.x),Math.abs(p.y-u.y))*.7);return cost(a)-cost(b);});const previous=ai.target;if(!previous||!seen.includes(previous)){const maxDensity=isSpray&&seen.length?seen[0].sprayDensity||0:0;const topCandidates=isSpray&&seen.length?seen.filter(p=>(p.sprayDensity||0)===maxDensity):seen.slice(0,Math.min(hostile?3:2,seen.length));ai.target=topCandidates.length?topCandidates[Math.floor(rnd()*topCandidates.length)]:null;if(ai.target!==previous){ai.hesitateUntil=s.t+(hostile?.35+rnd()*.6:.08+rnd()*.15);ai.focusUntil=s.t+1.5+rnd()*2;}}}return s.t<(ai.hesitateUntil||0)?null:ai.target;}
function patrol(u,dt,speed){if(!u.patrol||s.t>=u.patrol.until){const angle=Math.floor(rnd()*4)*Math.PI/2,distance=35+rnd()*70;u.patrol={x:Math.max(16,Math.min(W-16,u.x+Math.cos(angle)*distance)),y:Math.max(42,Math.min(H-18,u.y+Math.sin(angle)*distance)),until:s.t+1.5+rnd()*2,pause:s.t+(rnd()<.35?.3+rnd()*.7:0)};}if(s.t>=u.patrol.pause&&dist(u,u.patrol)>10)navigate(u,u.patrol.x-u.x,u.patrol.y-u.y,dt,speed);}
function bugIntent(a,target,dt,mult){if(!target){if(a.intent&&a.intent.mode==='approach'&&s.t<a.intent.until&&dist(a,a.intent.goal)>15){navigate(a,a.intent.goal.x-a.x,a.intent.goal.y-a.y,dt,(a.type==='queen'?13:22)*mult);}else{patrol(a,dt,(a.type==='queen'?13:22)*mult);}return;}if(a.ai?.target){if(!a.intent||s.t>=a.intent.until||a.intent.mode!=='approach'){a.intent={mode:'approach',until:s.t+1+rnd()*2,goal:{x:target.x+(rnd()-.5)*20,y:target.y+(rnd()-.5)*20}};}}else{if(!a.intent||s.t>=a.intent.until){const roll=rnd();a.intent={mode:roll<.4?'approach':roll<.75?'wander':'pause',until:s.t+1+rnd()*2,goal:{x:target.x+(rnd()-.5)*80,y:target.y+(rnd()-.5)*80}};}}if(a.intent.mode==='wander')patrol(a,dt,(a.type==='queen'?13:22)*mult);else if(a.intent.mode==='approach'&&dist(a,target)>35)navigate(a,a.intent.goal.x-a.x,a.intent.goal.y-a.y,dt,(a.type==='queen'?17:27)*mult);}
function cancelSupply(u){if(u.supplyTrip?.eagle&&eagleClaims.get(u.supplyTrip.eagle)===u)eagleClaims.delete(u.supplyTrip.eagle);u.supplyTrip=null;}
function supplyStep(u,target,dt){
 if(!weaponUserType(u)||u.cannon!==undefined||u.attackMove)return false;
 const threat=target||nearest(u,[...s.aliens,...s.nests].filter(a=>a.alive!==false&&a.hp>0&&dist(u,a)<245&&visible(u,a)),245);
 let trip=u.supplyTrip;
 if(threat){if(!trip)return false;if(target)aimHuman(u,target,dt*.85);return true;}
 if(trip?.phase==='out'&&(!s.pickups.includes(trip.eagle)||!reinforcementRule(trip.eagle.type))){if(eagleClaims.get(trip.eagle)===u)eagleClaims.delete(trip.eagle);trip.phase='return';}
 if(!trip){
  if(s.t<(u.nextSupplyScan||0))return false;u.nextSupplyScan=s.t+.6+rnd()*.6;
  const revision=navigationRevision();
  const candidates=s.pickups.filter(p=>['troops','air','tank','blitz'].includes(p.type)&&dist(u,p)<=250&&reinforcementRule(p.type)).sort((a,b)=>dist(u,a)-dist(u,b));
  for(const p of candidates){const owner=eagleClaims.get(p);if(owner&&(!owner.alive||owner.supplyTrip?.eagle!==p))eagleClaims.delete(p);if(eagleClaims.has(p))continue;if(window.TriumphNavigation&&!window.TriumphNavigation.reachable(u,p,humanRouteBlocked,revision))continue;trip=u.supplyTrip={eagle:p,phase:'out',origin:{x:u.x,y:u.y}};eagleClaims.set(p,u);break;}
 }
 if(!trip)return false;
 const leader=u.order===1?s.humans.find(a=>a.id===u.leader&&a.alive):null,goal=trip.phase==='out'?trip.eagle:leader||trip.origin,arrival=trip.phase==='out'?16:leader?65:12;
 if(dist(u,goal)>arrival)navigate(u,goal.x-u.x,goal.y-u.y,dt,36);
 else if(trip.phase==='out'){const index=s.pickups.indexOf(trip.eagle);if(index>=0&&pickup(u,trip.eagle)){s.pickups.splice(index,1);eagleClaims.delete(trip.eagle);trip.phase='return';}}
 else{cancelSupply(u);u.nextSupplyScan=s.t+1.5;}
 return true;
}
function commanderAI(u,dt){const target=perceive(u,[...s.aliens,...s.nests],210);if(target){const d=dist(u,target);if(d>150)navigate(u,target.x-u.x,target.y-u.y,dt,55);else if(d<45&&rnd()<.25)navigate(u,u.x-target.x,u.y-target.y,dt,55);aimHuman(u,target,dt*.4);return;}const leader=s.humans.find(a=>a.id===(u.id===2?1:4)&&a!==u&&a.alive)||s.humans.find(a=>[1,4].includes(a.id)&&a!==u&&a.alive);const p=nearest(u,s.pickups.filter(p=>!duplicateCommanderWeapon(u,p)&&visible(u,p)),65);if(p){navigate(u,p.x-u.x,p.y-u.y,dt,55);return;}if(leader&&dist(u,leader)>85){if(!u.followOffset)u.followOffset={x:(rnd()-.5)*70,y:(rnd()-.5)*70};navigate(u,leader.x+u.followOffset.x-u.x,leader.y+u.followOffset.y-u.y,dt,60);}else patrol(u,dt,28);}
function spawnVentGroundBug(x,y){({x,y}=bugArrival(x,y));const a=unit(x,y,'alien');a.object=151;a.hp=s.difficulty?.bug||4;s.aliens.push(a);return a;}
function update(dt){if(s.mode!=='playing'||paused)return;if(s.customMission?.objective.rescueCrawlers&&missionProgress().lost){s.mode='defeat';tone(50,.5);return;}if(s.customMission?.objective.atLeastOneNonCommander&&!s.humans.some(u=>u.alive&&u.type!=='commander')){s.mode='defeat';tone(50,.5);return;}if(s.customMission?.objective.rescueSoldiers){const o=s.customMission.objective.rescueSoldiers;if(!s.rescueAcquired&&s.terminals.every(t=>t.active)&&s.humans.some(u=>u.alive&&dist(u,o)<=o.range)&&s.humans.filter(u=>u.alive&&u.type!=='commander').length+s.drops.filter(d=>!d.finished).length+3<=s.rules.maxAliens){s.rescueAcquired=true;for(const [x,y] of s.customMission.rescueParty){const u=unit(x,y,'human','soldier');u.object=52;u.rescueSurvivor=true;s.humans.push(u);}sound(46,.45);}if(missionProgress().lost){s.mode='defeat';tone(50,.5);return;}}s.t+=dt;if(s.originalMap){updateSupport(dt);updatePickupSpawns(dt);}if(s.originalMap||s.customMission?.vents){window.TriumphVents.update(s,dt,{random:rnd,blocked,spawn:spawnVentGroundBug,sound});}const difficulty=document.querySelector('#difficulty').value,mult=s.difficulty?(s.profile?.enemyMotionMultiplier??window.TriumphBalance.motionMultipliers[difficulty]):difficulty==='easy'?.7:difficulty==='hard'?1.35:1;
 for(const u of s.humans){if(window.TriumphDesertRiders.isRider(u)){s.desertMines??=[];if(u.type==='convoy-crawler')for(const d of s.doors||[])if(!d.open&&!d.locked&&!d.destroyed&&dist(u,{x:d.cx,y:d.cy})<45){d.open=true;d.lastUse=s.t;sound(37,.2);}const handled=window.TriumphDesertRiders.step(u,dt,{sharedControls:true,escortRange:s.customMission?.objective.rescueCrawlers?.escortRange,blocked:wormBlocked,aliens:s.aliens,humans:s.humans,mines:s.desertMines,visible,route:(a,b)=>window.TriumphNavigation.step(a,b,window.TriumphDesertRiders.footprint(riderRouteBlocked,window.TriumphDesertRiders.radius(a)),navigationRevision()),shoot:bullets=>{s.bullets.push(...bullets);sound(11,.08);}});if(handled)continue;}u.cool=Math.max(0,u.cool-dt);if(!u.alive){if(u.type==='commander'){supportLifecycle.stepReturn(u,dt);}continue;}
 if(u.type==='commander'){if(u.shieldUntil>s.t)for(const a of [...s.aliens])if(a.alive&&dist(u,a)<24)damage(a,a.type==='queen'?50:5,u.id);u.weaponTime-=dt;if(u.weaponTime<=0)u.weapon=0;if(inputState.mouseMode==='commander'&&u.id===inputState.activeCommander){directCommanderStep(u,dt);gamepad?.step(u,dt);}else if(u.external&&u.external.until>s.t){const q=u.external;move(u,q.dx||0,q.dy||0,dt,85);if(q.fire)fire(u);}else commanderAI(u,dt);for(let i=s.pickups.length-1;i>=0;i--)if(dist(u,s.pickups[i])<22){if(pickup(u,s.pickups[i]))s.pickups.splice(i,1);}for(const f of s.flowers)if(f.alive&&dist(u,f)<20){f.alive=false;burst(f.x,f.y,15,'#a588bc');}if(s.crystal&&dist(u,s.crystal)<25&&s.level===7)s.crystal.recovered=true;
    }else {if(useOrderStep(u,dt))continue;if(focusAttackStep(u,dt))continue;if(u.attackMove?.force){trackBurst(u,null);attackMoveStep(u,null,dt);continue;}if(infantryType(u)){const gun=u.cannon!==undefined?s.cannons[u.cannon]:!u.attackMove&&!u.supplyTrip?s.cannons.find(c=>!c.occupant&&dist(u,c)<24):null;if(gun){if(!gun.occupant){gun.occupant=u;u.cannon=s.cannons.indexOf(gun);}u.x=gun.x;u.y=gun.y;const aim=perceive(u,[...s.aliens,...s.nests],360);if(!aim)trackBurst(u,null);if(aim){u.weapon=2;aimHuman(u,aim,0);}continue;}for(let i=s.pickups.length-1;i>=0;i--)if(['auto','plasma','flame','troops','air','tank','blitz'].includes(s.pickups[i].type)&&!(u.type==='soldier'&&u.attackMove&&['troops','air','tank','blitz'].includes(s.pickups[i].type))&&dist(u,s.pickups[i])<18){if(pickup(u,s.pickups[i]))s.pickups.splice(i,1);}}const perceiveRange=u.type==='snow-sniper'?480:u.weapon===2?319:u.type==='tank'?300:['rider-scout','field-mechanic'].includes(u.type)?180:245;const target=perceive(u,[...s.aliens,...s.nests],perceiveRange);if(!target)trackBurst(u,null);const leader=s.humans.find(a=>a.id===u.leader&&a.alive);if(attackMoveStep(u,target,dt))continue;if(supplyStep(u,target,dt))continue;if(u.order===3){const goal=u.anchor||u,leash=window.TriumphBalance?.guardLeashRadius||50;if(!target&&dist(u,goal)>12||dist(u,goal)>leash)navigate(u,goal.x-u.x,goal.y-u.y,dt,36);}else if(u.order===1&&leader&&dist(u,leader)>75)navigate(u,leader.x-u.x,leader.y-u.y,dt,36);else if(target&&u.order===2){const closeRange=u.type==='snow-sniper'?450:u.weapon===2?265:u.weapon===1?125:u.type==='dune-guard'?100:110;const d=dist(u,target);if(d>closeRange)navigate(u,target.x-u.x,target.y-u.y,dt,36);else if(u.weapon===2&&d<140){const backX=u.x-(target.x-u.x),backY=u.y-(target.y-u.y);if(!blocked(backX,backY))navigate(u,u.x-target.x,u.y-target.y,dt,36);}}else if(target&&(u.weapon===1||u.type==='dune-guard')&&u.order!==1){const closeRange=u.weapon===1?125:100;if(dist(u,target)>closeRange)navigate(u,target.x-u.x,target.y-u.y,dt,36);}else if(!target&&u.order!==1)patrol(u,dt,24);if(target)aimHuman(u,target,u.order===1&&leader&&dist(u,leader)>90?0:dt*.85);}

 }
 for(const a of s.aliens){if(!a.alive)continue;if(a.type==='desert-worm'){window.TriumphDesertWorm.step(a,dt,{humans:s.humans,blocked:wormBlocked,damage,route:(u,target)=>window.TriumphNavigation.step(u,target,wormRouteBlocked,navigationRevision())});continue;}a.cool=Math.max(0,a.cool-dt);const target=perceive(a,[...s.humans.filter(u=>u.alive),...(s.crystal&&!s.crystal.recovered&&s.crystal.y>36?[s.crystal]:[])],240);if(target){if(target.team==='human'||target.id!==undefined)alertPack(a,target,160);const d=dist(a,target);bugIntent(a,target,dt,mult);const desired=Math.atan2(target.y-a.y,target.x-a.x),turn=Math.atan2(Math.sin(desired-a.angle),Math.cos(desired-a.angle));if(d<=55&&a.intent?.mode==='approach')a.angle+=Math.max(-1.0*dt,Math.min(1.0*dt,turn));const offset=Math.atan2(Math.sin(desired-a.angle),Math.cos(desired-a.angle));a.shotOffset=Math.max(-Math.PI/16,Math.min(Math.PI/16,offset));if(d<13&&a.cool<=0){if(target===s.crystal){s.crystal.hp--;sound(56,.4);}else damage(target,1,0);a.cool=1;}else if(d<(a.type==='redbug'?specialistRules.redbug.sight:175)&&Math.abs(offset)<=Math.PI/16&&visible(a,target)&&a.cool<=0&&s.t>=(a.spitDecision||0)){a.spitDecision=s.t+.8+rnd()*1.4;if(rnd()<.5)fire(a);}}else bugIntent(a,null,dt,mult);if(a.type==='queen'&&(a.spawnCool||0)<s.t){a.spawnCool=s.t+7;if(s.aliens.filter(a=>a.alive&&a.type!=='queen').length<(s.rules?.maxAliens||50)){spawnGroundBug(a.x+15,a.y+15);}}if(a.type!=='queen')for(const f of s.flowers)if(f.alive&&dist(a,f)<16){f.alive=false;a.type='queen';a.hp=s.difficulty?.queen||50;a.object=152;burst(a.x,a.y,22,'#ca88af');}}
 window.TriumphDesertRiders.updateMines(s.desertMines||[],dt,{aliens:s.aliens,blocked:wormBlocked,visible,damage,burst});
 for(const n of s.nests){if(n.breeding){window.TriumphBreeding.advance(n,dt,{capacity:()=>s.aliens.filter(a=>a.alive&&a.type!=='queen').length<(s.rules?.maxAliens||50),spawn:n=>spawnGroundBug(n.x-25+rnd()*50,n.y+20)});continue;}if(n.hp<=0||n.birthsRemaining===0)continue;n.timer-=dt;if(n.timer<=0){n.timer=n.customInterval||(5+rnd()*4)/mult;if(s.aliens.filter(a=>a.alive&&a.type!=='queen').length<(s.rules?.maxAliens||50)){spawnGroundBug(n.x-25+rnd()*50,n.y+20);if(n.birthsRemaining!==undefined)n.birthsRemaining--;}else if(n.birthsRemaining!==undefined)n.timer=0;}}
 stepProjectiles(dt);
 for(const c of s.cannons||[])if(c.occupant&&!c.occupant.alive)c.occupant=null;for(const f of s.fires||[])if(f.until>s.t)for(const a of s.aliens)if(a.alive&&dist(a,f)<18)damage(a,1,0);if(s.fires)s.fires=s.fires.filter(f=>f.until>s.t);s.effects=s.effects.filter(e=>(e.t-=dt)>0);s.aliens=s.aliens.filter(a=>a.alive);s.pickupTimer-=dt;if(!s.originalMap&&s.pickupTimer<0){s.pickupTimer=18;if(s.pickups.length<10)s.pickups.push({x:100+rnd()*760,y:60+rnd()*560,type:['troops','grenade','rapid','plasma','tank','air'][Math.floor(rnd()*6)]});}if(s.hold>0)s.hold=Math.max(0,s.hold-dt);
 window.TriumphMissions.emitWaves(s,spawnGroundBug);
 window.TriumphJungleAmbush?.update(s,dt,{random:rnd,blocked,spawn:spawnGroundBug,sound});
 window.TriumphVolcanicHazards?.update(s,dt,{random:rnd,blocked,damage,sound,burst});
 if(s.wave){s.waveRemaining=Math.max(0,s.wave.normalKills-s.waveKills.normal)+Math.max(0,s.wave.queenKills-s.waveKills.queen);if(s.t>=s.wave.start&&s.aliens.length<(s.rules?.maxAliens||50)){s.waveClock-=dt;const advanced=s.wave.queenKills>0&&s.waveKills.normal>=s.wave.normalKills;if(s.waveClock<=0&&s.waveRemaining>0){s.waveClock=advanced?s.wave.queenInterval:s.wave.interval;const x=s.level===4?(rnd()<.5?16:1008):40+rnd()*940,y=rnd()<.5?45:740;if(advanced){const a=unit(x,y,'alien','queen');a.hp=s.difficulty.queen;s.aliens.push(a);}else spawnGroundBug(x,y);}}}if(s.crystal&&s.level===8&&s.wave&&s.waveKills.normal>=s.wave.normalKills&&s.waveKills.queen>=(s.wave.extractionQueenThreshold??40)&&[...Object.keys(s.rules.terminals)].every(id=>s.terminals.some(t=>t.object===Number(id)&&t.active))){s.crystal.extracting=true;s.crystal.y-=20*dt;if(s.crystal.y<-30)s.crystal.recovered=true;}const army=s.humans.filter(u=>u.alive&&u.type!=='commander').length,commanders=s.humans.filter(u=>u.alive&&u.type==='commander').length;if((s.customMission?.objective.rescueCrawlers&&missionProgress().lost)||(s.customMission?.objective.atLeastOneNonCommander&&army===0)||(army===0&&commanders===0&&!hasRespawnSupport())||(s.crystal&&s.crystal.hp<=0)){s.mode='defeat';tone(50,.5);}else if(missionProgress().ready){s.mode='victory';s.merits+=100+army*3+s.kills;tone(600,.3);} }
function missionProgress(){return window.TriumphMissions.progress(s);}

function variantMark(u){window.TriumphRendering.variantMark(ctx,u);}










function updateCommandPanel(){const tactical=s.mode==='playing'&&paused;canvas.setAttribute('data-tactical',String(tactical));const tacticalButton=document.querySelector('#pause');tacticalButton.textContent=tactical?'Exit tactical mode':'Tactical mode';tacticalButton.setAttribute('aria-pressed',String(tactical));const rally=document.querySelector('#rally');rally.setAttribute('aria-pressed',String(inputState.rallyMode));rally.disabled=s.mode!=='playing';rally.title=`R: toggle rally placement (${inputState.rallyPoints.length} flags)`;const u=selectedCommander();for(let id=1;id<=4;id++)document.querySelector('#cmd-'+id).setAttribute('aria-pressed',String(inputState.mouseMode==='commander'&&inputState.activeCommander===id));for(let order=0;order<4;order++){const button=document.querySelector('#order-'+order);button.setAttribute('aria-pressed',String(u?.order===order));button.disabled=!u?.alive||s.mode!=='playing';}const hint=document.querySelector('#command-hint');const message=inputState.rallyMode?'Rally placement: left-click clear ground to place a flag; right-click a flag to remove it. R or Escape exits.':inputState.mouseMode==='troops'?'Troop control: drag to select troops; right-click to attack-move. Select a commander below for direct control.':'Commander '+inputState.activeCommander+': WASD · hold left-click fires · right-click grenade · drag selects troops.';if(hint.textContent!==message)hint.textContent=message;}












// Short opportunistic detours use the next terrain-route segment, never the straight
// line through a wall. Keep the player's destination until pickup or mounting.


const {giveOrder,selectable,attackMoveTo,usableAt,useOrderTo,useSight,useOrderStep,enemyAt,focusAttackTo,focusAttackStep,attackMoveInteraction,attackMoveStep}=window.TriumphOrders.create({getState:()=>s,inputState,selection,W,H,dist,nearest,blocked,cancelSupply,trackBurst,sound,tone,infantryType,navigate,interact,pickup,burst,visible,aimHuman,navigationRevision,humanRouteBlocked,reinforcementRule,eagleClaims,navigation:window.TriumphNavigation,wormExposed:window.TriumphDesertWorm.exposed,hasOriginalAudio:()=>!!window.ORIGINAL_AUDIO});
const input=window.TriumphInput.create({getState:()=>s,isPaused:()=>paused,setPaused:value=>paused=value,inputState,keys,selection,W,H,dist,nearest,blocked,focusCanvas:()=>canvas.focus(),refreshPanel:()=>updateCommandPanel(),interact,fire,grenade,selectable,enemyAt,usableAt,focusAttackTo,useOrderTo,attackMoveTo,giveOrder,advance,restartMission,presets,modalOpen:()=>document.querySelector('#controls').open||document.querySelector('#unit-guide').open,unlockAudio:()=>window.TriumphMusic?.unlock(),capturePointer:id=>canvas.setPointerCapture(id),releasePointer:id=>{if(canvas.hasPointerCapture(id))canvas.releasePointerCapture(id);},move,rallyChoose:window.TriumphRally.choose});
const {directCommanderStep,toggleRally,addRally,removeRally,assignRally,selectedCommander,selectCommander,updateMouseFire,mouseCommanderAction,selectTroops}=input;
window.TriumphInputDOM.bind(canvas,window,input,W,H);
const gamepad=window.TriumphGamepad?.create({getPads:()=>navigator.getGamepads?.(),getState:()=>s,inputState,isPaused:()=>paused,modalOpen:()=>document.querySelector('#controls').open||document.querySelector('#unit-guide').open,focused:()=>document.hasFocus(),selectCommander,tactical:input.tactical,giveOrder,interact,grenade,move,fire,unlockAudio:()=>window.TriumphMusic?.unlock()});







function draw(){window.TriumphRendering.draw(ctx,s,inputState,{original,background},{W,H,colors,orders,paused},{sprite,selectable,selectedCommander,reinforcementStatus,hasRespawnSupport,missionProgress,currentMission,riders:window.TriumphDesertRiders,worm:window.TriumphDesertWorm,rally:window.TriumphRally,breeding:window.TriumphBreeding,vents:window.TriumphVents,jungleAmbush:window.TriumphJungleAmbush,volcanicHazards:window.TriumphVolcanicHazards});}
function advance(){window.TriumphMusic?.unlock();if(s.mode==='briefing'){s.mode='playing';paused=true;inputState.drag=null;keys.clear();canvas.focus();tone(400,.15);}else if(s.customId&&(s.mode==='victory'||s.mode==='defeat'))restartMission();else if(s.mode==='victory')begin(s.level===8?0:s.level+1,s.level===8?0:s.merits);else if(s.mode==='defeat')begin(s.merits>=100?s.level:0,s.merits>=100?s.merits-100:0);else paused=!paused;}
document.querySelector('#rally').onclick=toggleRally;
for(let id=1;id<=4;id++)document.querySelector('#cmd-'+id).onclick=()=>selectCommander(id);for(let order=0;order<4;order++)document.querySelector('#order-'+order).onclick=()=>{const u=selectedCommander();if(u?.alive&&s.mode==='playing'){giveOrder(u,order);canvas.focus();updateCommandPanel();}};

document.querySelector('#difficulty').onchange=()=>restartMission();
document.querySelector('#mission').onchange=e=>{const value=e.target.value;if(window.TriumphCustomMissions.get(value))loadCustomMission(value);else loadOriginal(Number(value));};
document.querySelector('#start').onclick=()=>{advance();canvas.focus();};document.querySelector('#pause').onclick=()=>{input.tactical();};document.querySelector('#reset').onclick=()=>{restartMission();canvas.focus();};document.querySelector('#options').onclick=()=>{input.openModal('controls');document.querySelector('#controls').showModal();};document.querySelector('#close').onclick=()=>{document.querySelector('#controls').close();input.closeModal('controls');};
window.triumph={state:()=>JSON.parse(JSON.stringify({mission:s.customId?null:s.level+1,customId:s.customId||null,merits:s.merits,mode:s.mode,paused,time:s.t,activeCommander:inputState.activeCommander,mouseMode:inputState.mouseMode,rallyMode:inputState.rallyMode,rallyPoints:inputState.rallyPoints,missionProgress:missionProgress(),selectedTroops:[...selection].filter(selectable).map(u=>({x:u.x,y:u.y,type:u.type,attackMove:u.attackMove,useOrder:u.useOrder?{kind:u.useOrder.kind,x:u.useOrder.x,y:u.useOrder.y}:null,focusTarget:u.focusTarget?{x:u.focusTarget.x,y:u.focusTarget.y,hp:u.focusTarget.hp}:null})),army:s.humans.filter(u=>u.alive&&u.type!=='commander').length,commanders:s.humans.filter(u=>u.type==='commander'),aliens:s.aliens,vents:s.vents,nests:s.nests,pickups:s.pickups,gate:s.gate,doors:s.doors,terminals:s.terminals,props:s.props,cannons:(s.cannons||[]).map(c=>({...c,occupant:c.occupant?{alive:c.occupant.alive}:null})),reinforcements:s.reinforcements.map(({path,...r})=>r),drops:s.drops,crystal:s.crystal,waveRemaining:s.waveRemaining,waveKills:s.waveKills})),loadMission:(level)=>{if(!Number.isInteger(level)||level<1||level>9)throw Error('Mission must be 1–9');loadOriginal(level-1);},loadCustomMission,customMissions:window.TriumphCustomMissions.list,command:(id,q)=>{if(![2,3].includes(id))throw Error('Assistant controls commanders 2 and 3');const u=s.humans.find(a=>a.id===id);u.external={...q,until:s.t+Math.min(3,Math.max(.05,q.seconds||.5))};if(q.order!==undefined)giveOrder(u,typeof q.order==='number'?q.order:null);if(q.grenade)grenade(u);},missions};
function frame(now){const dt=Math.min(.04,(now-last)/1000||0);last=now;if(gamepad){const status=document.querySelector('#gamepad-status');const message=gamepad.poll();if(status.textContent!==message)status.textContent=message;}update(dt);draw();updateCommandPanel();requestAnimationFrame(frame);}begin();updateCommandPanel();requestAnimationFrame(frame);
})();
