'use strict';
(() => {
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const W=1024,H=768,colors=['#a9e867','#68c9f5','#f3d65a','#ee917a'];
const presets=[['KeyW','KeyS','KeyA','KeyD','KeyV','KeyB'],['KeyI','KeyK','KeyJ','KeyL','BracketLeft','BracketRight'],['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','NumpadMultiply','NumpadSubtract'],['Numpad8','Numpad5','Numpad4','Numpad6','Numpad0','Numpad1']];
const orders=['NORMAL','FOLLOW','ATTACK','DEFEND'];
const missions=[
 {name:'LANDING ZONE',brief:'Secure the landing zone. Destroy every alien and nest.',nests:[[710,130],[865,290],[760,530]],rocks:[[390,180,62,60],[560,360,55,70],[410,555,65,55]],flowers:[[615,160],[660,480]]},
 {name:'LOCKED COMPOUND',brief:'Shoot the terminal to unlock the compound. Clear the infestation.',nests:[[830,140],[835,540],[575,345]],rocks:[[460,180,25,330],[460,180,240,25],[460,490,240,25]],gate:[700,205,25,285],terminal:[900,635],flowers:[[755,230],[600,595]]},
 {name:'CANYON PASS',brief:'Push through the rocky pass. Collect support before advancing.',nests:[[850,100],[880,365],[850,600],[600,590]],rocks:[[380,70,100,180],[380,460,100,180],[650,275,100,150]],flowers:[[570,170],[760,480]]},
 {name:'OUTPOST',brief:'Defend the crystal until the attack subsides, then clear remaining aliens.',nests:[[840,100],[860,590],[530,630],[560,80]],rocks:[[340,230,180,20],[340,460,180,20],[320,230,20,250]],crystal:[425,345],hold:90,flowers:[[710,190],[710,520]]},
 {name:'BREEDING GROUNDS',brief:'Crush the evolver plants. Eliminate the breeding nests.',nests:[[610,90],[890,130],[700,350],[900,560],[600,610]],rocks:[[450,250,65,90],[450,500,55,90]],flowers:[[510,170],[820,250],[790,480],[510,640]]},
 {name:'RESEARCH FACILITY',brief:'Activate the terminal. Open the facility and clear every room.',nests:[[830,120],[850,580],[620,350],[870,350]],rocks:[[400,100,25,220],[400,430,25,190],[400,100,530,25],[400,600,530,25],[670,125,25,190],[670,430,25,170]],gate:[670,315,25,115],terminal:[550,560],flowers:[[750,180],[740,535]]},
 {name:'THE SWARM',brief:'The swarm is gathering. Preserve the army and bring in reinforcements.',nests:[[600,90],[880,100],[870,320],[880,600],[600,600]],rocks:[[400,180,70,80],[520,320,70,80],[400,470,70,80]],flowers:[[700,190],[740,450],[510,610]]},
 {name:'CRYSTAL VAULT',brief:'Unlock the vault. Recover the crystal and eliminate the defenders.',nests:[[790,120],[870,540],[630,340]],rocks:[[590,210,250,20],[590,470,250,20],[590,210,20,280]],gate:[840,230,20,240],terminal:[910,630],crystal:[720,350],flowers:[[490,140],[750,580]]},
 {name:'FINAL STAND',brief:'Protect the crystal for two minutes. Destroy all remaining enemies.',nests:[[140,85],[860,85],[860,590],[140,590]],rocks:[[380,240,80,25],[570,240,80,25],[380,470,80,25],[570,470,80,25]],crystal:[510,350],hold:120,flowers:[[300,150],[730,150],[300,550],[730,550]]}
];
let rallyMode=false,rallyPoints=[],nextRallyId=1;
let keys=new Set(),s,seed=2099,background,paused=false,last=0,audio;
let selection=new Set(),drag=null,moveMarker=null,lastMoveClick=null;
const eagleClaims=new Map();
let activeCommander=null,mouseMode='troops',mouseAim=null;
const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const soundCache=new Map();
function sound(handle,volume=.3){if(!window.ORIGINAL_AUDIO)return;try{if(!soundCache.has(handle)){const record=window.ORIGINAL_AUDIO.find(a=>a.kind==='sound'&&a.handle===handle);if(!record)return;soundCache.set(handle,new Audio('assets/audio/'+record.pcm));}const a=soundCache.get(handle).cloneNode();a.volume=volume;a.play().catch(()=>{});}catch{}}
function tone(f=180,d=.035,v=.035){try{audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type='square';o.frequency.value=f;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d);}catch{}}
function unit(x,y,team,type='soldier',id=0){return {x,y,team,type,id,alive:true,angle:team==='human'?0:Math.PI,cool:team==='alien'?2+rnd()*3:rnd()*.6,hp:type==='tank'?8:type==='air'?5:type==='queen'?18:1,order:0,leader:1,respawn:0,weapon:0,weaponTime:0,grenades:3,external:null};}
function makeBackground(){background=document.createElement('canvas');background.width=W;background.height=H;const c=background.getContext('2d');c.fillStyle=s.level===5?'#655e54':'#b2a183';c.fillRect(0,0,W,H);for(let i=0;i<16000;i++){c.fillStyle=['#b7a88a','#aa997a','#a19174','#c0af8d','#96886c'][Math.floor(rnd()*5)];c.fillRect(Math.floor(rnd()*W),Math.floor(rnd()*H),1+rnd()*3,1+rnd()*2);}for(let i=0;i<30;i++){const x=rnd()*W,y=rnd()*H;c.strokeStyle='#938169';c.beginPath();c.ellipse(x,y,10+rnd()*15,4+rnd()*7,0,0,7);c.stroke();}}
function legacyBegin(level=0,merits=0){seed=2099+level;s={level,merits,mode:'briefing',t:0,humans:[],aliens:[],vents:[],bullets:[],effects:[],pickups:[],nests:[],rocks:[],flowers:[],score:[0,0,0,0],kills:0,gate:null,terminal:null,crystal:null,hold:missions[level].hold||0,pickupTimer:14};const m=missions[level];for(let i=0;i<4;i++)s.humans.push(unit(110,280+i*34,'human','commander',i+1));for(let i=0;i<28;i++)s.humans.push(unit(35+rnd()*190,80+rnd()*535,'human'));
 m.nests.forEach(([x,y])=>{s.nests.push({x,y,hp:28,timer:1+rnd()*4});for(let i=0;i<4;i++)s.aliens.push(unit(x-60+rnd()*100,y-50+rnd()*100,'alien'));});s.rocks=m.rocks.map(([x,y,w,h])=>({x,y,w,h}));s.flowers=m.flowers.map(([x,y])=>({x,y,alive:true}));if(m.gate)s.gate={x:m.gate[0],y:m.gate[1],w:m.gate[2],h:m.gate[3],open:false};if(m.terminal)s.terminal={x:m.terminal[0],y:m.terminal[1],active:false};if(m.crystal)s.crystal={x:m.crystal[0],y:m.crystal[1],hp:50,recovered:false};['troops','tank','air','rapid','plasma','grenade'].forEach((type,i)=>s.pickups.push({x:240+(i%2)*70,y:100+i*95,type}));makeBackground();paused=true;keys.clear();}

const original=window.ORIGINAL,sourceRules=window.ORIGINAL_RULES,imageCache=new Map();
function loadImage(src){if(!imageCache.has(src)){const i=new Image();i.src=src;imageCache.set(src,i);}return imageCache.get(src);}
function sprite(object,x,y,angle=0,animation=0,frameOverride=null){const o=original?.objects[object];if(!o)return false;const animations=o.animations,dirs=animations?.[animation]||animations?.[0]||Object.values(animations||{})[0];let handle=o.image;if(dirs){let dir=((Math.round(-angle*16/Math.PI)%32)+32)%32;const choices=Object.keys(dirs).map(Number);dir=choices.reduce((best,d)=>Math.min(Math.abs(dir-d),32-Math.abs(dir-d))<Math.min(Math.abs(dir-best),32-Math.abs(dir-best))?d:best,choices[0]);const a=dirs[dir];handle=a.frames[frameOverride===null?Math.floor((s?.t||0)*(a.speed||20)/10)%a.frames.length:frameOverride%a.frames.length];}const info=original.images[handle];if(!info)return false;const image=loadImage(`assets/images/${handle}.png`);if(image.complete&&image.naturalWidth)ctx.drawImage(image,Math.round(x-info.hx),Math.round(y-info.hy));return true;}
function originalBegin(level,merits){legacyBegin(level,merits);const m=original.maps[level];document.querySelector('#mission').value=String(level);s.rules=sourceRules?.maps[m.index];s.difficulty=sourceRules?.difficulty[document.querySelector('#difficulty').value]||{bug:4,queen:50,evolutionRollMax:24};s.profile=window.TriumphBalance.originalProfiles.global[document.querySelector('#difficulty').value];s.difficulty={...s.difficulty,bug:s.profile.bugHP,queen:s.profile.queenHP};const waveProfile=window.TriumphBalance.originalProfiles.waves[level+1];s.wave=waveProfile?{...sourceRules.waves[m.index],...waveProfile.settings[document.querySelector('#difficulty').value]}:sourceRules?.waves[m.index];if(s.wave?.normalInterval)s.wave.interval=s.wave.normalInterval;s.waveKills={normal:0,queen:0};s.originalMap=m;s.mask=Uint8Array.from(atob(m.mask),c=>c.charCodeAt(0));s.humans=[];s.aliens=[];s.nests=[];s.flowers=[];s.rocks=[];s.pickups=[];s.gate=null;s.terminal=null;s.crystal=null;s.doors=[];s.terminals=[];s.props=[];s.fires=[];s.cannons=[];s.hold=0;s.reinforcements=[];s.drops=[];s.support=window.ORIGINAL_SUPPORT[m.index];s.supportHelpers={};s.telepads=s.support.telepads.filter(i=>i.x>0&&i.x<W&&i.y>35&&i.y<H);for(const h of s.support.helpers)s.supportHelpers[h.object]={...h,path:window.TriumphSupport.path(h.object,h.x,h.y),angle:randomDirection(h.object)};s.padClock=0;s.pickupClock=1;s.waveRemaining=s.wave?s.wave.normalKills+s.wave.queenKills:0;s.waveClock=0;
window.TriumphVents.initialize(s,m);
const onMap=i=>i.x>10&&i.x<1015&&i.y>35&&i.y<756,instances=m.instances.map(i=>({...i,definition:original.objects[i.object]}));
function actor(i,team,type,id=0){const u=unit(i.x,i.y,team,type,id);u.object=i.object;u.hp=team==='alien'?(type==='queen'?s.difficulty.queen:s.difficulty.bug):type==='tank'?8:1;return u;}
for(let id=1;id<=4;id++){const marker=instances.find(i=>new RegExp(`P${id} Spawn Point`).test(i.definition.name||'')),commander=instances.find(i=>new RegExp(id===1?'^Commander1$':`^Commander ${id}$`).test(i.definition.name||''));const first=instances.find(i=>i.definition.name==='Commander1'&&i.x>0&&i.y>0),origin=instances.find(i=>i.definition.name==='P1 Spawn Point'),offset={x:first&&origin?first.x-origin.x:7,y:first&&origin?first.y-origin.y:15};const explicit=s.rules?.commanderStarts[id];const pos=explicit||(marker?{...marker,x:marker.x+offset.x,y:marker.y+offset.y}:commander)||{x:30,y:280+id*35};const u=actor({...pos,x:Math.max(25,pos.x),y:Math.max(50,pos.y)},'human','commander',id);u.object=explicit?.object||commander?.object||51;u.spawn={x:u.x,y:u.y};s.humans.push(u);}
for(const i of instances){if(!onMap(i)&&!(s.rules?.terminals[i.object]&&i.x>0&&i.x<W&&i.y>0&&i.y<H))continue;const o=i.definition,name=o.name||'';
if(name==='Troop')s.humans.push(actor(i,'human','soldier'));else if(name==='Tank')s.humans.push(actor(i,'human','tank'));else if(name==='Krate Ground Bug'||name==='Krate Ground Bug 2')s.aliens.push(actor(i,'alien','soldier'));else if(name==='Advanced Krate Bug')s.aliens.push(actor(i,'alien','queen'));else if(name==='Egg')s.nests.push({x:i.x,y:i.y,hp:s.profile.nestHP,timer:2+rnd()*7,object:i.object,sourceId:i.handle,breeding:window.TriumphBreeding.create((level+1)*1000003+Math.round(i.x)*1009+Math.round(i.y)*9176+i.object,s.profile.nestRollSuccesses)});else if(name==='growplant')s.flowers.push({x:i.x,y:i.y,alive:true,object:i.object});else if(/^Door \d/.test(name)){const anim=o.animations[0]||Object.values(o.animations)[0],handle=Object.values(anim)[0].frames[0],info=original.images[handle];s.doors.push({x:i.x-info.hx,y:i.y-info.hy,w:info.width,h:info.height,cx:i.x,cy:i.y,object:i.object,open:false,locked:!(s.rules?.doors[i.object]?.initiallyUnlocked??true),durability:s.rules?.doors[i.object]?.durability,damage:0});}else if(/^computer area/.test(name))s.terminals.push({x:i.x,y:i.y,object:i.object,active:false});else if(/^(Small explosive canister|Large explosive drum|Breakable wall)/.test(name)){const handle=Object.values(Object.values(o.animations)[0])[0].frames[0],info=original.images[handle];s.props.push({x:i.x,y:i.y,object:i.object,hp:/wall/.test(name)?12:4,wall:/wall/.test(name),left:i.x-info.hx,top:i.y-info.hy,w:info.width,h:info.height});}else if(name==='cannon')s.cannons.push({x:i.x,y:i.y,object:i.object,occupant:null,cool:0});else if(name==='Crystal')s.crystal={x:i.x,y:i.y,hp:s.profile.crystalHP,object:i.object};else {const type=name==='Ground Reinforcements'?'troops':name==='Airial Reinforcements'?'air':name==='Ground Support'?'tank':name==='BLITZ!'?'blitz':name==='1 Grenade'?'grenade':name==='Auto Gun'?'auto':name==='Plasma Gun'?'plasma':name==='Flame Gun'?'flame':null;if(type)s.pickups.push({x:i.x,y:i.y,type,object:i.object});}}

function bounds(object,x,y){const o=original.objects[object],dir=Object.values(Object.values(o?.animations||{})[0]||{})[0],h=dir?.frames[0]||o?.image,i=original.images[h];return i?{x:x-i.hx,y:y-i.hy,w:i.width,h:i.height}:{x:x-8,y:y-8,w:16,h:16};}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
for(const rule of s.rules?.difficultyCull||[]){if(!(rule.flag===1?s.difficulty.medium:rule.flag===2?s.difficulty.easy:false))continue;const helpers=instances.filter(i=>i.object===rule.helper);for(const list of ['aliens','flowers','props'])s[list]=s[list].filter(a=>a.object!==rule.target||!helpers.some(h=>overlap(bounds(a.object,a.x,a.y),bounds(h.object,h.x,h.y))));}
const retained=window.TriumphBalance.originalProfiles.nests[level][document.querySelector('#difficulty').value];s.nests=s.nests.filter(n=>retained.some(p=>p.id===n.sourceId&&p.x===n.x&&p.y===n.y));
background=loadImage(`assets/maps/${m.index}.png`);missions[level].name=m.name.toUpperCase();missions[level].brief=m.briefing.filter(t=>!t.startsWith('GOOD')).join(' ');for(const o of [51,52,146,151,152,74,53,54,55,56,63,64,65,99,108,547,446,447,448,475])for(const a of Object.values(original.objects[o]?.animations||{}))for(const d of Object.values(a))for(const h of d.frames)loadImage(`assets/images/${h}.png`);
}
function begin(level=0,merits=0){rallyMode=false;rallyPoints=[];nextRallyId=1;eagleClaims.clear();lastMoveClick=null;selection.clear();drag=null;moveMarker=null;activeCommander=null;mouseMode='troops';mouseAim=null;keys.clear();if(original)originalBegin(level,merits);else legacyBegin(level,merits);window.TriumphNavigation?.reset();window.TriumphMusic?.select(s.rules?.music??0);}
// Scenario identity is independent of original level and support-map indices.
const missionLedger={original:0,custom:Object.create(null)};
function rememberMerits(){if(!s)return;if(s.customId)missionLedger.custom[s.customId]=s.merits;else missionLedger.original=s.merits;}
function loadOriginal(level){rememberMerits();begin(level,missionLedger.original);}
function loadCustomMission(id){const m=window.TriumphCustomMissions.resolve(id,document.querySelector('#difficulty').value);if(!m)throw Error('Unknown custom mission: '+id);rememberMerits();begin(m.fixtureMission-1,missionLedger.custom[id]||0);s.customId=id;s.customMission=m;s.profile=null;s.difficulty=sourceRules.difficulty[document.querySelector('#difficulty').value];document.querySelector('#mission').value=id;
 s.rules={...s.rules,minimumTime:0,victoryTerminals:[]};s.wave=null;s.waveRemaining=0;s.vents=[];s.flowers=[];s.crystal=null;
 s.customWaves=window.TriumphMissions.createWaves(m);s.customAirPending=!!m.scheduledAir;s.desertMines=[];
 // Custom scenery is independent of the recovered rules/support template.
 if(m.terrainId){const terrain=window.TriumphTerrains[m.terrainId];s.terrainId=terrain.id;s.mask=Uint8Array.from(atob(terrain.mask),c=>c.charCodeAt(0));background=loadImage(terrain.image);s.props=[];s.cannons=[];s.doors=[];s.rocks=[];}
 const make=(x,y,team,type,object,id=0)=>{const u=unit(x,y,team,type,id);u.object=object;u.hp=team==='alien'?s.difficulty.bug:1;if(id)u.spawn={x,y};return u;};
 s.humans=m.commanders.map(([x,y],i)=>make(x,y,'human','commander',[51,91,100,101][i],i+1)).concat(m.soldiers.map(([x,y])=>make(x,y,'human','soldier',52)),m.robots.map(([x,y])=>({...make(x,y,'human','robot',460),hp:7})),m.commandos.map(([x,y])=>make(x,y,'human','commando',52)));
 s.aliens=m.bugs.map(([x,y])=>make(x,y,'alien','soldier',151));
 s.nests=m.nests.map(([x,y])=>({x,y,object:74,hp:sourceRules.eggHealth||50,customInterval:m.nestInterval,timer:m.nestInterval||2+rnd()*7,breeding:!m.nestInterval&&document.querySelector('#difficulty').value==='normal'?window.TriumphBreeding.create(2000006+x*1009+y*9176+74):null}));
 if(m.crawlers){for(const [i,[x,y]] of m.crawlers.entries()){const c=spawnDesertRider('convoy-crawler',x,y,m.escortRoutes[i].map(([x,y])=>({x,y})));Object.assign(c,{hp:2,disabled:true,rescue:true,convoyNumber:i+1});}for(const [type,points] of [['rider-scout',[[130,260],[130,460]]],['field-mechanic',[[150,350],[150,420]]],['dune-guard',Array.from({length:m.guards},(_,i)=>[85+(i%2)*40,470+Math.floor(i/2)*34])]])for(const [x,y] of points)spawnDesertRider(type,x,y);for(const [x,y] of m.worms)spawnDesertWorm(x,y);}
 s.terminals=m.terminals.map(t=>({...t,active:false,used:false}));s.pickups=[...m.support,...m.weapons].map(p=>({...p}));
}
function restartMission(){if(s.customId)loadCustomMission(s.customId);else begin(s.level,s.merits);}
function currentMission(){return s.customMission||missions[s.level];}
function staticBlocked(x,y){if(!s.mask)return false;x=Math.floor(x);y=Math.floor(y);if(x<0||x>=W||y<32||y>=H)return true;const n=y*W+x;return !!(s.mask[n>>3]&(1<<(n&7)));}
function interact(u,only=null){if(!s.originalMap)return false;let used=false;for(const t of s.terminals)if((!only||only===t)&&dist(u,t)<35){const rule=s.rules?.terminals[t.object];sound(rule?.sound||46,.45);t.used=true;if(rule?.setsFlag||s.customMission?.objective.activate?.includes(t.key))t.active=true;used=true;for(const d of s.doors)if(rule?.unlocks.includes(d.object))d.locked=false;}for(const d of s.doors)if((!only||only===d)&&!d.destroyed&&!d.locked&&dist(u,{x:d.cx,y:d.cy})<45&&s.t-(d.lastUse||-10)>.5){d.open=!d.open;d.lastUse=s.t;sound(37,.45);used=true;}return used;}
function blocked(x,y,canOpenDoors=false){if(s.props?.some(p=>p.wall&&p.hp>0&&x>p.left&&x<p.left+p.w&&y>p.top&&y<p.top+p.h))return true;if(staticBlocked(x,y))return true;if(s.doors?.some(d=>!d.destroyed&&!d.open&&(!canOpenDoors||d.locked)&&x>d.x-3&&x<d.x+d.w+3&&y>d.y-3&&y<d.y+d.h+3))return true;return [...s.rocks,...(s.gate&&!s.gate.open?[s.gate]:[])].some(r=>x>r.x-6&&x<r.x+r.w+6&&y>r.y-6&&y<r.y+r.h+6);}
const humanRouteBlocked=(x,y)=>blocked(x,y,true);
const riderRouteBlocked=(x,y)=>x<0||x>=W||y<36||y>=H||blocked(x,y,true);
const navigationRevision=()=>s.level+':'+(s.doors||[]).map(d=>[Number(d.open),Number(d.locked),Number(d.destroyed)].join(',')).join(';')+':'+(s.props||[]).filter(p=>p.wall&&p.hp>0).length;
function move(u,dx,dy,dt,speed){if(window.TriumphDesertRiders.isRider(u)){const len=Math.hypot(dx,dy);if(len)window.TriumphDesertRiders.travel(u,{x:u.x+dx/len*speed*dt,y:u.y+dy/len*speed*dt},speed,dt,wormBlocked);return;}const len=Math.hypot(dx,dy);if(!len)return;dx/=len;dy/=len;u.angle=u.team==='human'&&['soldier','commander','robot'].includes(u.type)?cardinal(Math.atan2(dy,dx)):u.type==='commando'?diagonal(Math.atan2(dy,dx)):Math.atan2(dy,dx);u.movingUntil=s.t+.1;if(u.x<12||u.x>W-12||u.y<38||u.y>H-16){u.x+=dx*dt*speed;u.y+=dy*dt*speed;return;}const x=Math.max(12,Math.min(W-12,u.x+dx*dt*speed)),y=Math.max(38,Math.min(H-16,u.y+dy*dt*speed));if(!blocked(x,u.y))u.x=x;if(!blocked(u.x,y))u.y=y;}
function navigate(u,dx,dy,dt,speed){if(u.team==='human'&&u.type==='robot'&&u.cannon===undefined)speed*=window.TriumphBalance.groundRobotMovementMultiplier;if(u.team==='human')for(const d of s.doors||[])if(!d.open&&!d.locked&&!d.destroyed&&dist(u,{x:d.cx,y:d.cy})<45){d.open=true;d.lastUse=s.t;sound(37,.2);}const goal={x:u.x+dx,y:u.y+dy};if(window.TriumphNavigation){const revision=navigationRevision();const next=window.TriumphNavigation.step(u,goal,window.TriumphDesertRiders.isRider(u)?window.TriumphDesertRiders.footprint(riderRouteBlocked,window.TriumphDesertRiders.radius(u)):u.team==='human'?humanRouteBlocked:blocked,revision);if(next){move(u,next.x-u.x,next.y-u.y,dt,speed);return;}}const angle=Math.atan2(dy,dx),step=Math.max(12,speed*dt);for(const offset of [0,.4,-.4,.85,-.85,1.4,-1.4,2,-2]){const a=angle+offset;if(!blocked(u.x+Math.cos(a)*step,u.y+Math.sin(a)*step)){move(u,Math.cos(a),Math.sin(a),dt,speed);return;}}}
function cannonAngle(angle){return Math.round(angle/(Math.PI/8))*(Math.PI/8);}
function diagonal(angle){return Math.round(angle/(Math.PI/4))*(Math.PI/4);}
function cardinal(angle){return Math.round(angle/(Math.PI/2))*(Math.PI/2);}
function visible(a,b){
 if(b.type==='desert-worm'&&!window.TriumphDesertWorm.exposed(b))return false;
 // Weapon sight tests the projectile centerline to the target's hittable edge.
 // Walking clearance includes body padding and excludes boundary rows, which
 // incorrectly hid nests at y=752 and enemies standing beside solid terrain.
 if(b.hp!==undefined||b.team){const length=dist(a,b),radius=s.nests?.includes(b)?26:b.type==='queen'||b.type==='tank'?17:b===s.crystal?14:8,travel=Math.max(0,length-radius+1),steps=Math.ceil(travel/4);for(let i=1;i<=steps;i++){const f=travel/length*i/steps;if(blocked(a.x+(b.x-a.x)*f,a.y+(b.y-a.y)*f))return false;}return true;}
 return window.TriumphNavigation?window.TriumphNavigation.line(a,b,blocked):!blocked((a.x+b.x)/2,(a.y+b.y)/2);
}
const specialistRules=window.TriumphBalance.specialistRules;
const infantryType=u=>['soldier','commando'].includes(u.type);
const burstRules=window.TriumphBalance.burstRules;
const tankSweepRules=window.TriumphBalance.tankSweepRules;
const {enemyFireDelay,trackBurst,burstReady,finishBurstShot,tankGroup,aimTank,aimCannon,humanFiringLane,aimHuman,fire,burst}=window.TriumphCombat.create({getState:()=>s,burstRules,tankSweepRules,cannonSweepRules:window.TriumphBalance.cannonSweepRules,rnd,visible,dist,blocked,navigate,cardinal,diagonal,cannonAngle,getDifficulty:()=>document.querySelector('#difficulty').value,bugFireBases:window.TriumphBalance.bugFireBases,specialistRules,desertRiders:window.TriumphDesertRiders,originalAudio:()=>window.ORIGINAL_AUDIO,sound,tone});
function stepProjectiles(dt){window.TriumphProjectiles.step(s,dt,{W,H,blocked,dist,damage,destroyProp,wormExposed:window.TriumphDesertWorm.exposed,sound,tone,burst});}

function nearest(u,list,max=Infinity){let best=null,d=max;for(const a of list){if(a.alive===false||a.hp<=0)continue;const t=dist(u,a);if(t<d){best=a;d=t;}}return best;}

function bugArrival(x,y){const point={x:Math.max(16,Math.min(W-16,x)),y:Math.max(44,Math.min(H-24,y))};return window.TriumphNavigation?.destination(point,point,blocked)||point;}
function wormBlocked(x,y){return x<0||x>=W||y<36||y>=H||blocked(x,y);}
function wormRouteBlocked(x,y){return !window.TriumphDesertWorm.clear(x,y,wormBlocked);}
function spawnDesertRider(type,x,y,route=[]){const u=window.TriumphDesertRiders.create(type,x,y,wormBlocked,route);if(u)s.humans.push(u);return u;}
function spawnDesertWorm(x,y){const u=window.TriumphDesertWorm.create(x,y,wormBlocked);if(u)s.aliens.push(u);return u;}
function spawnGroundBug(x,y){({x,y}=bugArrival(x,y));const special=rnd()<specialistRules.redbug.spawnChance,u=unit(x,y,'alien',special?'redbug':'soldier');u.hp=special?specialistRules.redbug.hp:s.difficulty?.bug||4;s.aliens.push(u);return u;}
function kill(u,owner){if(!u.alive||(u.type==='desert-worm'&&!window.TriumphDesertWorm.exposed(u)))return;cancelSupply(u);u.alive=false;sound(u.team==='alien'?(u.type==='queen'?20:5):6,.22);burst(u.x,u.y,10,u.team==='alien'?'#b57068':'#7d3f35');if(u.team==='alien'){s.kills++;if(s.waveKills)s.waveKills[u.type==='queen'?'queen':'normal']++;if(owner)s.score[owner-1]+=10;if(u.type==='queen')for(let i=0;i<4;i++){spawnGroundBug(u.x+rnd()*30-15,u.y+rnd()*30-15);}}if(u.type==='commander'){u.respawn=10;if(u.id===activeCommander)drag=null;}}
function damage(u,n,owner){if(!u.alive||u.shieldUntil>s.t||(u.type==='desert-worm'&&!window.TriumphDesertWorm.exposed(u)))return;u.hp-=n;if(u.hp<=0)kill(u,owner);}
function destroyProp(p){if(p.destroyed)return;p.destroyed=true;burst(p.x,p.y,p.wall?20:65);sound(p.wall?41:25,.5);if(!p.wall){s.fires.push({x:p.x,y:p.y,until:s.t+4,object:274});for(const a of s.aliens)if(a.alive&&dist(a,p)<65)damage(a,8,0);for(const n of s.nests)if(n.hp>0&&dist(n,p)<75)n.hp-=12;for(const q of s.props)if(q!==p&&q.hp>0&&dist(q,p)<60){q.hp=0;destroyProp(q);}}}
function grenade(u){if(!u.alive||u.grenades<=0)return;u.grenades--;const x=u.x+Math.cos(u.angle)*90,y=u.y+Math.sin(u.angle)*90;burst(x,y,58);for(const a of s.aliens)if(a.alive&&dist(a,{x,y})<75)damage(a,12,u.id);for(const n of s.nests)if(n.hp>0&&dist(n,{x,y})<80){n.hp-=15;if(n.hp<=0)burst(n.x,n.y,32);}for(const p of s.props||[])if(p.hp>0&&dist(p,{x,y})<80){p.hp-=15;if(p.hp<=0)destroyProp(p);}sound(23,.5);if(!window.ORIGINAL_AUDIO)tone(65,.25,.06);}
function giveOrder(u,choice=null){u.order=choice===null?(u.order+1)%4:choice;u.selecting=false;for(const a of s.humans)if(a.alive&&a.type!=='commander'&&dist(a,u)<300){cancelSupply(a);a.useOrder=null;a.focusTarget=null;trackBurst(a,null);a.attackMove=null;a.order=u.order;a.leader=u.id;a.anchor={x:a.x,y:a.y};}sound([2,4,1,3][u.order],.55);if(!window.ORIGINAL_AUDIO)tone(440,.06,.025);}

function randomDirection(object){const mask=original.objects[object]?.movement?.direction>>>0,dirs=[];for(let i=0;i<32;i++)if(mask&(1<<i))dirs.push(i);return -(dirs[Math.floor(rnd()*dirs.length)]||0)*Math.PI/16;}
function supportPosition(create){const helper=s.supportHelpers[create.parent];const pad=s.telepads[Math.floor(rnd()*s.telepads.length)];return {x:(helper?.x??pad?.x??W/2)+create.x,y:(helper?.y??pad?.y??H/2)+create.y};}
function groundArrival(x,y){const desired={x:Math.max(12,Math.min(W-12,x)),y:Math.max(42,Math.min(H-16,y))},origin=s.humans.find(u=>u.type==='commander'&&u.alive)||desired;return window.TriumphNavigation?.destination(origin,desired,blocked)||desired;}
function flightEntersMap(pos,angle){const dx=Math.cos(angle),dy=Math.sin(angle);let enter=0,leave=Infinity;for(const [value,velocity,low,high] of [[pos.x,dx,12,W-12],[pos.y,dy,42,H-16]]){if(Math.abs(velocity)<1e-9){if(value<low||value>high)return false;continue;}const a=(low-value)/velocity,b=(high-value)/velocity;enter=Math.max(enter,Math.min(a,b));leave=Math.min(leave,Math.max(a,b));}return leave>=enter;}
function addTroop(object,x,y,type='soldier',rallyEligible=false){const u=unit(x,y,'human',type);u.object=object;u.grenades=0;Object.assign(u,groundArrival(x,y));s.humans.push(u);if(rallyEligible)assignRally(u);return u;}
function reinforcementStatus(type){const item={troops:'Ground Reinforcements',air:'Airial Reinforcements',tank:'Ground Support',blitz:'BLITZ!'}[type],rule=window.TriumphSupport.choose(s.support,item);if(!rule)return {rule:null,reason:'SUPPORT UNAVAILABLE'};const troops=s.humans.filter(u=>u.alive&&infantryType(u)).length;return rule.creates.some(c=>c.name==='Troop')&&troops>=s.rules.maxAliens?{rule:null,reason:'TROOPS FULL · WAIT FOR SPACE'}:{rule,reason:null};}
function reinforcementRule(type){return reinforcementStatus(type).rule;}
function reinforce(type){const rule=reinforcementRule(type);if(!rule)return false;for(const sample of rule.sounds)sound(sample,.55);
for(const create of rule.creates){const pos=supportPosition(create);if(create.name==='Troop'){addTroop(create.object,pos.x,pos.y,type==='air'?'commando':'soldier',['troops','tank','blitz'].includes(type));continue;}if(create.name==='Tank'||create.name==='ground bot'){const u=unit(pos.x,pos.y,'human',create.name==='Tank'?'tank':'robot');u.object=create.object;u.hp=create.name==='ground bot'?7:8;Object.assign(u,groundArrival(pos.x,pos.y));s.humans.push(u);if(['troops','tank','blitz'].includes(type))assignRally(u);if(create.name==='ground bot')sound(49,.45);continue;}if(create.name==='player SPAWN shield'){burst(pos.x,pos.y,24,'#86ccff');continue;}
const kind=create.name==='Troop Carrier'?'carrier':create.name==='Air Support'?'air':create.name==='zipline creator'?'infiltration':null;if(kind){const r={...pos,object:create.object,kind,rallyEligible:['troops','tank','blitz'].includes(type),age:0,nextDrop:Math.ceil(s.t+1e-6),fireCool:0,grenadeCool:0,angle:randomDirection(create.object),path:window.TriumphSupport.path(create.object,pos.x,pos.y),entered:false};if(kind==='air'&&!flightEntersMap(r,r.angle))r.angle=Math.atan2(H/2-r.y,W/2-r.x);s.reinforcements.push(r);if(kind==='carrier')sound(18,.4);}}
return true;}
function supportDrop(r,kind){const object=kind==='zipline'?389:109,metadata=Object.values(original.objects[object].animations[0])[0];s.drops.push({x:r.x,y:r.y,object,angle:r.angle,age:0,frames:metadata.frames.length,duration:metadata.frames.length/Math.max(1,metadata.speed/2),zipline:kind==='zipline',thrown:false});}
function supportExplosion(x,y,owner=0){burst(x,y,45);sound(23,.35);for(const a of s.aliens)if(a.alive&&dist(a,{x,y})<65)damage(a,12,owner);for(const n of s.nests)if(n.hp>0&&dist(n,{x,y})<70)n.hp-=2;}
function moveHelper(h,dt){if(h.path){window.TriumphSupport.advance(h.path,dt);Object.assign(h,{x:h.path.x,y:h.path.y,angle:h.path.angle});return;}const speed=original.objects[h.object]?.movement?.ball?.speed;if(!speed)return;let x=h.x+Math.cos(h.angle)*speed*6.25*dt,y=h.y+Math.sin(h.angle)*speed*6.25*dt;if(x<0||x>W){h.angle=Math.PI-h.angle;x=Math.max(0,Math.min(W,x));}if(y<38||y>H-12){h.angle=-h.angle;y=Math.max(38,Math.min(H-12,y));}h.x=x;h.y=y;}
function updateSupport(dt){
 if(s.customAirPending&&s.t>=s.customMission.scheduledAir.at){s.customAirPending=false;for(const [i,[x,y]] of s.customMission.scheduledAir.points.entries())s.reinforcements.push({x,y:-24-i*64,object:176,kind:'air',age:0,nextDrop:Infinity,fireCool:0,grenadeCool:0,angle:Math.PI/2,entered:false,scheduledTarget:{x,y}});sound(21,.55);}
for(const h of Object.values(s.supportHelpers))moveHelper(h,dt);s.padClock-=dt;if(s.telepads.length&&s.originalMap.index>=17&&s.padClock<=0){s.padClock=.05;const pad=s.telepads[Math.floor(rnd()*s.telepads.length)],spawner=Object.values(s.supportHelpers).find(h=>h.name==='Ground spawner');if(spawner){spawner.x=pad.x+16;spawner.y=pad.y+16;}}
const countTroops=()=>s.humans.filter(u=>u.alive&&infantryType(u)).length;
for(const r of s.reinforcements){r.age+=dt;r.fireCool-=dt;r.grenadeCool-=dt;if(r.kind==='carrier'){window.TriumphSupport.advance(r.path,dt);if(r.path?.pause>0&&!r.unloadStarted){r.unloadStarted=true;r.path.pause=Math.max(r.path.pause,5);r.nextDrop=s.t;}if(!r.path){r.finished=true;continue;}r.x=r.path.x;r.y=r.path.y;r.angle=r.path.angle;if(r.path.pause>0&&s.t>=r.nextDrop&&countTroops()<s.rules.maxAliens){addTroop(52,r.x,r.y,'soldier',r.rallyEligible);r.nextDrop=s.t+1;}if(r.path.pause<=0&&!r.path.done)for(const a of s.aliens)if(a.alive&&dist(a,r)<30){kill(a,0);}if(r.path.done)r.finished=true;}
else if(r.kind==='air'){const speed=original.objects[r.object].movement.ball.speed*6.25;r.x+=Math.cos(r.angle)*speed*dt;r.y+=Math.sin(r.angle)*speed*dt;if(r.scheduledTarget&&!r.scheduledDropped&&r.y>=r.scheduledTarget.y)r.y=r.scheduledTarget.y;const inside=r.x>=0&&r.x<W&&r.y>=36&&r.y<H;if(inside&&!r.entered){r.entered=true;sound(22,.4);}if(inside){if(r.scheduledTarget&&!r.scheduledDropped&&r.y>=r.scheduledTarget.y&&countTroops()+s.drops.filter(d=>!d.finished).length<s.rules.maxAliens){supportDrop({...r,...r.scheduledTarget},'air');r.scheduledDropped=true;}if(s.t>=r.nextDrop&&countTroops()<s.rules.maxAliens&&!staticBlocked(r.x,r.y)){supportDrop(r,'air');r.nextDrop=Math.floor(s.t)+1;}if(r.fireCool<=0){r.fireCool=.330;fire({...r,id:0,type:'air',team:'human',weapon:0,cool:0,order:0});}if(r.grenadeCool<=0){r.grenadeCool=1;supportExplosion(r.x,r.y);}}if(r.entered&&!inside||r.age>20&&!r.scheduledTarget)r.finished=true;}
else {moveHelper(r,dt);if(s.t>=r.nextDrop&&countTroops()<s.rules.maxAliens){supportDrop(r,'zipline');r.nextDrop=Math.floor(s.t)+1;}if(r.age>=10)r.finished=true;}}
s.reinforcements=s.reinforcements.filter(r=>!r.finished);
for(const d of s.drops){d.age+=dt;if(d.zipline&&!d.thrown&&d.age>=d.duration/2){d.thrown=true;supportExplosion(d.x,d.y);}if(d.age>=d.duration){addTroop(52,d.x,d.y,'commando');d.finished=true;}}
s.drops=s.drops.filter(d=>!d.finished);}
function spawnPickupRoll(roll){if(s.customMission&&!s.customMission.randomPickups)return;const rules=window.ORIGINAL_PICKUPS?.[s.originalMap?.index];if(!rules)return;const troops=s.humans.filter(u=>u.alive&&infantryType(u)).length,compare=window.TriumphSupport.compare;for(const rule of rules.cases){if(rule.type==='growplant'&&(document.querySelector('#difficulty').value!=='normal'||!(rule.globals||[]).every(g=>compare(s.support.globals[g.index]||0,g.comparison,g.value))))continue;if(s.t<rule.minimumTime||!rule.checks.every(c=>compare(c.variable===0?roll:rules.secondary,c.comparison,c.difficulty?s.difficulty[c.difficulty]:c.value)))continue;if(rule.count&&!compare((rule.type==='growplant'?s.flowers.filter(f=>f.alive):s.pickups.filter(p=>p.type===rule.type)).length,rule.count.comparison,rule.count.value))continue;if(rule.troops){const tokens=rule.troops.tokens,limit=tokens.length===1?tokens[0].value:s.rules.maxAliens*tokens.at(-1).value;if(!compare(troops,rule.troops.comparison,limit))continue;}if(['troops','air','tank','blitz'].includes(rule.type)&&!reinforcementRule(rule.type))continue;const helper=s.supportHelpers[rule.parent];let point=helper?{x:helper.x+rule.x,y:helper.y+rule.y}:null;const clear=p=>p&&p.x>20&&p.x<W-20&&p.y>45&&p.y<H-20&&!blocked(p.x,p.y)&&!blocked(p.x-8,p.y-8)&&!blocked(p.x+8,p.y+8);if(!clear(point)){point=null;for(let attempt=0;attempt<64;attempt++){const p={x:24+rnd()*(W-48),y:48+rnd()*(H-72)};if(clear(p)){point=p;break;}}}if(point){if(rule.type==='growplant')s.flowers.push({...point,alive:true,object:rule.object});else s.pickups.push({...point,type:rule.type,object:rule.object});}}}
function updatePickupSpawns(dt){if(s.customMission&&!s.customMission.randomPickups)return;const rules=window.ORIGINAL_PICKUPS?.[s.originalMap?.index];if(!rules)return;s.pickupClock-=dt;while(s.pickupClock<=0){s.pickupClock+=rules.interval;spawnPickupRoll(Math.floor(rnd()*rules.range));}}
function hasRespawnSupport(){return s.humans.some(u=>u.alive&&u.type!=='commander')||s.reinforcements.some(r=>!r.finished&&['carrier','air','infiltration'].includes(r.kind))||s.drops.length>0;}
function respawnCommander(u){const origin=u.spawn||{x:90,y:260+u.id*35},p=window.TriumphNavigation?.destination(origin,origin,blocked)||origin;u.alive=true;u.hp=1;u.x=p.x;u.y=p.y;u.weapon=0;u.weaponTime=0;u.selecting=false;u.external=null;u.ai=null;u.patrol=null;u.cool=.25;u.shieldUntil=s.t+.6;u.respawn=0;burst(u.x,u.y,24,'#bbdd99');}
const pickupWeapon=type=>({auto:0,rapid:1,flame:1,plasma:2})[type];
const duplicateCommanderWeapon=(u,p)=>u.type==='commander'&&pickupWeapon(p.type)!==undefined&&u.weapon===pickupWeapon(p.type);
function pickup(u,p){if(duplicateCommanderWeapon(u,p))return false;if(['blitz','troops','tank','air'].includes(p.type)){if(!reinforce(p.type))return false;}else if(p.type==='grenade')u.grenades=Math.min(8,u.grenades+1);else {u.weapon=['rapid','flame'].includes(p.type)?1:p.type==='auto'?0:2;u.weaponTime=Infinity;}if(u.id)s.score[u.id-1]+=25;burst(p.x,p.y,15,'#ffed7b');tone(650,.1);return true;}
const bugFireBases=window.TriumphBalance.bugFireBases;

let unitsWasPaused=false,controlsWasPaused=false;
function showUnits(){
 unitsWasPaused=paused;paused=true;drag=null;keys.clear();
 const difficulty=document.querySelector('#difficulty').value,h=s.difficulty||sourceRules.difficulty[difficulty],base=bugFireBases[difficulty]||3.8;
 const burstText=type=>{const r=burstRules[type];return `${r.min}–${r.max} shots per burst; ${r.restMin}–${r.restMax} s rest; ${r.delayMin}–${r.delayMax} s reaction delay.`;};
 const rows=[
 ['Commander','Commander1',1,'Bullet: 1; grenade: 12 to bugs, 15 to nests','0.25 s (4 shots/s); flame: 0.18 s','Keyboard / AI fires in four directions; selected mouse commander aims freely. Moves at 85 px/s, commands nearby troops and collects weapons/support. Returns after 10 s if army or incoming support remain; return shield lasts 0.6 s. Grenades: 0.33 s cooldown, up to 8 carried.'],
 ['Infantry','Troop',1,'1 per bullet','0.38 s (2.63 shots/s); Defend: 0.20 s (5/s)',burstText('soldier')+' Four-direction fire; moves into an unobstructed weapon-range lane and fires only when aligned. Defend holds and waits for a legal lane. Sees visible enemies within 245 px. Normal patrols, Follow stays with its commander, Attack advances, Defend holds position. Collects weapons/eagles and occupies cannons. Attack-moving soldiers make short route-side detours: eagles before turrets in clear areas, turrets before combat when enemies are nearby. When clear of enemies, temporarily seeks usable eagles within 250 px, then returns. Combat pauses the trip; player orders cancel it.'],
 ['Commando','Troop',1,'1 per bullet','0.38 s (2.63 shots/s); flame: 0.18 s',burstText('commando')+' Blue bandana. Fires in eight directions, including diagonals. Delivered by blue-eagle air and infiltration support; retains normal infantry orders, sight, pickups, health and damage, including automatic eagle trips when no enemies are in range.'],
 ['Tank','Tank',8,'5 per bullet','0.20 s (5 shots/s)',burstText('tank')+' Sweeps a locked 25–80° arc toward the densest visible bug group within 300 px; narrow for tight groups, wider for spread groups. Alternates sweep direction between bursts. Falls back to a nest when no bugs are visible. Uses squad orders and terrain routing. Right-click an enemy to focus a 15° sweep across that target. Walls stop shots.'],
 ['Ground robot','ground bot',7,'1 per bullet','0.38 s; Defend: 0.20 s; flame: 0.18 s',burstText('robot')+' Moves 50% faster than its previous recreation speed (54 px/s travel; 36 px/s patrol). Uses squad orders, terrain routing and four-direction fire. Detects enemies within 245 px.'],
 ['Krate ground bug','Krate Ground Bug',h.bug,'Spit: 1; melee: 1',`${base.toFixed(1)}–${(base+1.6).toFixed(1)} s spit; melee: 1 s`,'Sees 175 px with clear sight. Spits in its facing direction ±11.25°. Randomly approaches, wanders or pauses. Focus lasts 1.5–3.5 s, then breaks for 1–3 s; may skip shooting. Evolves at a growplant.'],
 ['Ceiling / vent bug','alien shadow','Untargetable aloft','Ground bug after landing','Contact roll every 0.1 s','Missions 7–9: ceiling shadows cross walls and drop beside commanders or infantry. Drop and jump animations cannot be attacked; landed bugs fight normally. In missions 7–8, ordinary ground bugs can return into vents on a 5% roll every 2 s, while ceiling population allows. Clear every ceiling and transition bug to finish the mission.'],
 ['Desert charging worm (custom opt-in)',null,16,'Charge: 2 per ground target','1.2 s warning; 1.5 s recovery','Beneath the Dunes custom mission. Sand ripples: underground and immune. Exposed gold warning locks a horizontal or vertical lane; sidestep before the 300 px/s charge (260 px maximum). Walls stop its 24 px body. Exposed during charge and recovery; no spit, evolution or wall damage.'],
 ['Rider scout (custom opt-in)',null,1,'1 per bullet','0.6 s; evade rest 2.5 s','Beneath the Dunes custom mission. Cardinal rifle, 180 px sight. Fixed kit; no weapon/eagle collection or cannon mounting. Shared troop orders, focus, force-move and door/terminal use. Automatically retreats 38 px at 100 px/s from visible ground bugs within 62 px; terrain blocks evasion.'],
 ['Dune guard (custom opt-in)',null,1,'Five pellets, 1 each','1.1 s','Beneath the Dunes custom mission. Cardinal shotgun, 30 degree total arc, 120 px range; exactly five pellets. Fixed kit; no pickups or cannon mounting; shared troop movement/focus/use orders.'],
 ['Field mechanic (custom opt-in)',null,1,'Rifle 1; repair 0.5 HP/s','0.6 s rifle','Beneath the Dunes custom mission. Repairs one living, damaged nearby tank, ground robot or crawler within 62 px with clear sight, up to its normal health cap. Fixed kit; no pickups or cannon mounting; shared troop movement/focus/use orders.'],
 ['Convoy crawler (custom opt-in)',null,6,'Mine: 4 to exposed ground enemies','2 s evade rest; four mines','Beneath the Dunes custom mission. Route travel 30 px/s. Beneath the Dunes crawlers start disabled at 2/6 HP: full repair permanently unlocks travel; keep a living ground escort within 110 px with clear sight. Full 17 px footprint; reacts once to each locked worm lane, evading 32 px on both axes at 100 px/s if the full sweep is clear. After completing evasion drops a mine at its departure point; arms after 0.65 s, expires after 30 s. Mines trigger within 22 px, blast 38 px, terrain blocks damage; no friendly or underground damage. No shield during evasion.'],
 ['Red Krate bug','Krate Ground Bug',specialistRules.redbug.hp,'Spit: 1; melee: 1',`${specialistRules.redbug.fireMin}–${specialistRules.redbug.fireMax} s spit; melee: 1 s`,`Red abdomen band. ${specialistRules.redbug.sight} px sight, blocked by terrain. ${specialistRules.redbug.spawnChance*100}% chance among newly spawned ground bugs from nests, queens and waves. Fixed health/cooldown across difficulties; normal facing cone and randomized behavior. Can evolve into a normal queen.`],
 ['Advanced Krate / queen','Advanced Krate Bug',h.queen,'Spit: 1; melee: 1',`${(base+.4).toFixed(1)}–${(base+2).toFixed(1)} s spit; melee: 1 s`,'Same facing cone and distracted perception as ground bugs; moves more slowly. Spawns one bug every 7 s below the population cap; releases four when killed.'],
 ['Egg / nest','Egg',s.profile?.nestHP||sourceRules.eggHealth||50,'No direct damage',s.customMission?.nestInterval?`Spawn: ${s.customMission.nestInterval} s`:s.profile?`${s.profile.nestRollSuccesses}% opportunity / 0.5 s; birth after 1.8 s`:difficulty==='normal'?'4% opportunity / 0.5 s; birth after 1.8 s':`Spawn: ${(5/(window.TriumphBalance.motionMultipliers[difficulty])).toFixed(1)}–${(9/(window.TriumphBalance.motionMultipliers[difficulty])).toFixed(1)} s`,'Stationary breeding site, spawning ground bugs below the population cap. Original missions: first roll at 0.5 s; 2.4 s busy phase on every setting. Custom missions retain their own cadence. Destroy to stop breeding.'],
 ['Growplant / evolver','growplant','Consumed on contact','None','No attack','A touching ground bug becomes a full-health queen. Commanders consume it on contact to prevent evolution. Normal regenerates it in missions 1–3 on item rolls 22–24, while at most three live plants exist before creation. Placed plants elsewhere remain. Not a bullet-damage target.'],
 ['Troop carrier','Troop Carrier','Not damageable','None','Drops: 1 troop/s while stopped','Follows recovered carrier paths and unloads below the population cap, stopping for at least 5 seconds to deliver a squad. Blocks bug projectiles without taking damage. Incoming support allows commanders to return. Unloaded soldiers attack-move to the nearest reachable rally flag when one exists.'],
 ['Air support','Air Support','Not damageable','Bullet: 1; bomb: 12 to bugs, 2 to nests','Gun: 0.33 s; bomb/drop: 1 s','Flies a straight pass, shoots along its flight direction, bombs nearby enemies and drops commandos over open terrain below the cap. Leaves after its pass. Commandos ignore rally flags, including Blitzkrieg drops.'],
 ['Plasma cannon','cannon','Operator: 1; cannon not damageable','1 direct + six 1-damage sparks','Operator: 0.38 s; Defend: 0.20 s',burstText('soldier')+' Infantry occupies this stationary gun. Detects visible targets within 360 px, retains 16 equally spaced directions (22.5°) visually with either infantry or commando operators. Each burst locks its target center, sweeps smoothly across a random total 0–15° arc, and reverses direction next burst. Commando operators retain 5–7 shots, 0.8–1.2 s rest and 0.2–0.4 s reaction. No armor for operator; attack-move dismounts it.'],
 ['Crystal','Crystal',s.profile?.crystalHP||sourceRules.crystalHealth||7,'None','No attack','Mission objective. Bug bullets/melee each remove 1 HP; destruction loses the mission. Recovery/extraction depends on the mission.'],
 ['Canister / explosive drum','Small explosive canister',4,'Explosion: 8 to bugs, 12 to nests','One explosion','Can chain nearby containers. Leaves fire for 4 s; touching bugs take 1 damage each simulation update. Friendly units and commanders are immune.'],
 ['Breakable wall','Breakable wall',12,'None','No attack','Blocks movement and shots until destroyed.'],
 ['Door','Door','Durability: 5, 15 or indestructible','None','No attack','Closed doors block movement and shots. Terminals unlock linked doors; troops open unlocked doors nearby. Bug bullets remove 1 durability per hit from destructible doors.'],
 ['Terminal','computer area','Not damageable','None','No attack','Operate nearby with Fire, or double right-click with troops selected to send them to activate it. Unlocks linked doors or satisfies mission objectives.']
 ];
 const image=name=>{const o=Object.values(original?.objects||{}).find(o=>o.name===name||o.name?.startsWith(name)),a=Object.values(o?.animations||{})[0],d=Object.values(a||{})[0],handle=d?.frames?.[0]??o?.image;return handle===undefined?'':`<img src="assets/images/${handle}.png" alt="" loading="lazy">`;};
 document.querySelector('#units-context').textContent=`${currentMission().name} · Firing difficulty: ${difficulty} · Bug HP: ${h.bug}, queen HP: ${h.queen}. Health is set at mission start; changing difficulty restarts the mission.${s.customMission?.profile?` Custom ${s.customMission.profile}: ${s.customMission.guards===undefined?s.customMission.soldiers.length+s.customMission.commandos.length:s.customMission.guards+4} starting infantry; ${s.nests.length} nests. ${s.customWaves.arrivals.length} finite arrivals.${s.customMission.nestInterval?` Nest birth interval: ${s.customMission.nestInterval}s.`:''}`:''}${s.customMission?.role==='defense'?' Last Convoy: hold for 120 seconds, emit all ${s.customWaves.arrivals.length} scheduled arrivals and clear enemies with a living noncommander. The last noncommander dying causes defeat even with support inbound.':s.customMission?.role==='infiltration'?' Silent Return: unlock access, activate the laser, then return every living ground human to the extraction zone with a noncommander. At 20s three friendly aircraft from the north drop one commando each along the central vertical line. Return them too; wait for the schedule and all support arrivals. Enemies and nests may remain.':''}`;
 document.querySelector('#unit-cards').innerHTML=rows.map(([name,obj,hp,damage,rate,behavior])=>`<article class="unit-card ${name==='Commando'?'commando-card':name==='Red Krate bug'?'redbug-card':''}"><h3>${image(obj)}${name}</h3><dl><dt>HP</dt><dd>${hp}</dd><dt>Damage</dt><dd>${damage}</dd><dt>Cooldown</dt><dd>${rate}</dd><dt>Defense</dt><dd>No armor / damage reduction</dd></dl><p>${behavior}</p></article>`).join('')+`<article class="unit-card weapons"><h3>Weapons & combat rules</h3><p>Rally flags: yellow ground, bronze support and Blitzkrieg soldier/tank/robot arrivals attack-move to the nearest reachable flag by terrain route distance, then hold nearby. Commandos are excluded. Player orders override rally orders; deleting a flag affects future arrivals.</p><p>Auto gun: 1 damage, 290 px/s, up to 638 px travel. Flame: 1 damage, 0.18 s cooldown (5.56 shots/s), up to 145 px. Plasma: 1 direct damage + six 1-damage sparks on impact; commander cooldown 0.25 s, infantry uses its order cooldown; up to 319 px. Each spark can hit separately. Bug spit: 120 px/s, up to 264 px travel; target detection is 175 px for normal bugs and 200 px for red bugs.</p><p>Walls stop shots and block sight. Bullets hit the opposing team. Commander grenades and support bombs hurt bugs and nests; exploding containers and their fire hurt enemies only. No armor, accuracy stat or defense roll exists. Return shields briefly protect commanders; carriers and aircraft have no damageable health pool. Listed shot rates apply within a burst. Infantry, commandos, robots and tanks rest between bursts, with independently randomized reaction delays. Losing a target ends its burst; reacquiring adds a delay, and switching targets never cancels a rest period. Commanders and aircraft retain continuous fire. AI may also hesitate, skip attacks or lack a firing lane.</p></article>`;
 document.querySelector('#unit-guide').showModal();
}
document.querySelector('#units').onclick=showUnits;
document.querySelector('#units-close').onclick=()=>document.querySelector('#unit-guide').close();
document.querySelector('#unit-guide').onclose=()=>{paused=unitsWasPaused;keys.clear();drag=null;canvas.focus();};
function perceive(u,items,range=210){const hostile=u.team==='alien';if(hostile)range=Math.min(range,u.type==='redbug'?specialistRules.redbug.sight:175);if(!u.ai)u.ai={nextScan:s.t+(hostile?.8+rnd()*1.2:.1+rnd()*.2),target:null};const ai=u.ai;if(ai.target&&(ai.target.alive===false||ai.target.hp<=0||dist(u,ai.target)>range||!visible(u,ai.target)))ai.target=null;if(hostile&&ai.target&&s.t>ai.focusUntil){ai.target=null;ai.boredUntil=s.t+1+rnd()*2;ai.nextScan=ai.boredUntil;}if(hostile&&s.t<(ai.boredUntil||0))return null;if(s.t>=ai.nextScan){ai.nextScan=s.t+(hostile?1+rnd()*1.4:.3+rnd()*.4);const seen=items.filter(a=>(a.alive||a.hp>0)&&dist(u,a)<range&&visible(u,a)).sort((a,b)=>{const cost=p=>dist(u,p)+(hostile||u.type==='commando'?0:Math.min(Math.abs(p.x-u.x),Math.abs(p.y-u.y))*.7);return cost(a)-cost(b);});const previous=ai.target;if(!previous||!seen.includes(previous)){ai.target=seen.length?seen[Math.floor(rnd()*Math.min(hostile?3:2,seen.length))]:null;if(ai.target!==previous){ai.hesitateUntil=s.t+(hostile?.35+rnd()*.6:.08+rnd()*.15);ai.focusUntil=s.t+1.5+rnd()*2;}}}return s.t<(ai.hesitateUntil||0)?null:ai.target;}
function patrol(u,dt,speed){if(!u.patrol||s.t>=u.patrol.until){const angle=Math.floor(rnd()*4)*Math.PI/2,distance=35+rnd()*70;u.patrol={x:Math.max(16,Math.min(W-16,u.x+Math.cos(angle)*distance)),y:Math.max(42,Math.min(H-18,u.y+Math.sin(angle)*distance)),until:s.t+1.5+rnd()*2,pause:s.t+(rnd()<.35?.3+rnd()*.7:0)};}if(s.t>=u.patrol.pause&&dist(u,u.patrol)>10)navigate(u,u.patrol.x-u.x,u.patrol.y-u.y,dt,speed);}
function bugIntent(a,target,dt,mult){if(!target){patrol(a,dt,(a.type==='queen'?13:22)*mult);return;}if(!a.intent||s.t>=a.intent.until){const roll=rnd();a.intent={mode:roll<.4?'approach':roll<.75?'wander':'pause',until:s.t+1+rnd()*2,goal:{x:target.x+(rnd()-.5)*80,y:target.y+(rnd()-.5)*80}};}if(a.intent.mode==='wander')patrol(a,dt,(a.type==='queen'?13:22)*mult);else if(a.intent.mode==='approach'&&dist(a,target)>35)navigate(a,a.intent.goal.x-a.x,a.intent.goal.y-a.y,dt,(a.type==='queen'?17:27)*mult);}
function cancelSupply(u){if(u.supplyTrip?.eagle&&eagleClaims.get(u.supplyTrip.eagle)===u)eagleClaims.delete(u.supplyTrip.eagle);u.supplyTrip=null;}
function supplyStep(u,target,dt){
 if(!infantryType(u)||u.cannon!==undefined||u.attackMove)return false;
 const threat=target||nearest(u,[...s.aliens,...s.nests].filter(a=>a.alive!==false&&a.hp>0&&dist(u,a)<245&&visible(u,a)),245);
 let trip=u.supplyTrip;
 if(threat){if(!trip)return false;if(target)aimHuman(u,target,dt*.85);return true;}
 if(trip?.phase==='out'&&(!s.pickups.includes(trip.eagle)||!reinforcementRule(trip.eagle.type))){if(eagleClaims.get(trip.eagle)===u)eagleClaims.delete(trip.eagle);trip.phase='return';}
 if(!trip){
  if(s.t<(u.nextSupplyScan||0))return false;u.nextSupplyScan=s.t+.6+rnd()*.6;
  const revision=navigationRevision();
  const candidates=s.pickups.filter(p=>['troops','air','tank','blitz'].includes(p.type)&&dist(u,p)<=250&&reinforcementRule(p.type)).sort((a,b)=>dist(u,a)-dist(u,b));
  for(const p of candidates){const owner=eagleClaims.get(p);if(owner&&(!owner.alive||owner.supplyTrip?.eagle!==p))eagleClaims.delete(p);if(eagleClaims.has(p))continue;if(window.TriumphNavigation&&!window.TriumphNavigation.reachable(u,p,humanRouteBlocked,revision))continue;trip=u.supplyTrip={eagle:p,phase:'out',origin:{x:u.x,y:u.y}};eagleClaims.set(p,u);break;}
 }
 if(!trip)return false;
 const leader=u.order===1?s.humans.find(a=>a.id===u.leader&&a.alive):null,goal=trip.phase==='out'?trip.eagle:leader||trip.origin,arrival=trip.phase==='out'?16:leader?65:12;
 if(dist(u,goal)>arrival)navigate(u,goal.x-u.x,goal.y-u.y,dt,36);
 else if(trip.phase==='out'){const index=s.pickups.indexOf(trip.eagle);if(index>=0&&pickup(u,trip.eagle)){s.pickups.splice(index,1);eagleClaims.delete(trip.eagle);trip.phase='return';}}
 else{cancelSupply(u);u.nextSupplyScan=s.t+1.5;}
 return true;
}
function commanderAI(u,dt){const target=perceive(u,[...s.aliens,...s.nests],210);if(target){const d=dist(u,target);if(d>150)navigate(u,target.x-u.x,target.y-u.y,dt,55);else if(d<45&&rnd()<.25)navigate(u,u.x-target.x,u.y-target.y,dt,55);aimHuman(u,target,dt*.4);return;}const leader=s.humans.find(a=>a.id===(u.id===2?1:4)&&a!==u&&a.alive)||s.humans.find(a=>[1,4].includes(a.id)&&a!==u&&a.alive);const p=nearest(u,s.pickups.filter(p=>!duplicateCommanderWeapon(u,p)&&visible(u,p)),65);if(p){navigate(u,p.x-u.x,p.y-u.y,dt,55);return;}if(leader&&dist(u,leader)>85){if(!u.followOffset)u.followOffset={x:(rnd()-.5)*70,y:(rnd()-.5)*70};navigate(u,leader.x+u.followOffset.x-u.x,leader.y+u.followOffset.y-u.y,dt,60);}else patrol(u,dt,28);}
function spawnVentGroundBug(x,y){({x,y}=bugArrival(x,y));const a=unit(x,y,'alien');a.object=151;a.hp=s.difficulty?.bug||4;s.aliens.push(a);return a;}
function update(dt){if(s.mode!=='playing'||paused)return;if(s.customMission?.objective.rescueCrawlers&&missionProgress().lost){s.mode='defeat';tone(50,.5);return;}if(s.customMission?.objective.atLeastOneNonCommander&&!s.humans.some(u=>u.alive&&u.type!=='commander')){s.mode='defeat';tone(50,.5);return;}s.t+=dt;if(s.originalMap){updateSupport(dt);updatePickupSpawns(dt);window.TriumphVents.update(s,dt,{random:rnd,blocked,spawn:spawnVentGroundBug,sound});}const difficulty=document.querySelector('#difficulty').value,mult=s.difficulty?(s.profile?.enemyMotionMultiplier??window.TriumphBalance.motionMultipliers[difficulty]):difficulty==='easy'?.7:difficulty==='hard'?1.35:1;
 for(const u of s.humans){if(window.TriumphDesertRiders.isRider(u)){s.desertMines??=[];if(u.type==='convoy-crawler')for(const d of s.doors||[])if(!d.open&&!d.locked&&!d.destroyed&&dist(u,{x:d.cx,y:d.cy})<45){d.open=true;d.lastUse=s.t;sound(37,.2);}const handled=window.TriumphDesertRiders.step(u,dt,{sharedControls:true,escortRange:s.customMission?.objective.rescueCrawlers?.escortRange,blocked:wormBlocked,aliens:s.aliens,humans:s.humans,mines:s.desertMines,visible,route:(a,b)=>window.TriumphNavigation.step(a,b,window.TriumphDesertRiders.footprint(riderRouteBlocked,window.TriumphDesertRiders.radius(a)),navigationRevision()),shoot:bullets=>{s.bullets.push(...bullets);sound(11,.08);}});if(handled)continue;}u.cool=Math.max(0,u.cool-dt);if(!u.alive){if(u.type==='commander'){u.respawn=Math.max(0,(u.respawn??10)-dt);if(u.respawn<=0&&hasRespawnSupport())respawnCommander(u);}continue;}
 if(u.type==='commander'){if(u.shieldUntil>s.t)for(const a of [...s.aliens])if(a.alive&&dist(u,a)<24)damage(a,a.type==='queen'?50:5,u.id);u.weaponTime-=dt;if(u.weaponTime<=0)u.weapon=0;if(mouseMode==='commander'&&u.id===activeCommander){move(u,(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0),dt,85);if(mouseMode==='commander'&&mouseAim)u.angle=Math.atan2(mouseAim.y-u.y,mouseAim.x-u.x);updateMouseFire(u);if(keys.has('KeyV')&&keys.has('KeyB')){if((u.grenadeCool||0)<=s.t){grenade(u);u.grenadeCool=s.t+.330;}}else if(keys.has('KeyV'))fire(u,mouseMode==='commander'&&!!mouseAim);}else if(u.external&&u.external.until>s.t){const q=u.external;move(u,q.dx||0,q.dy||0,dt,85);if(q.fire)fire(u);}else commanderAI(u,dt);for(let i=s.pickups.length-1;i>=0;i--)if(dist(u,s.pickups[i])<22){if(pickup(u,s.pickups[i]))s.pickups.splice(i,1);}for(const f of s.flowers)if(f.alive&&dist(u,f)<20){f.alive=false;burst(f.x,f.y,15,'#a588bc');}if(s.crystal&&dist(u,s.crystal)<25&&s.level===7)s.crystal.recovered=true;
 }else {if(useOrderStep(u,dt))continue;if(focusAttackStep(u,dt))continue;if(u.attackMove?.force){trackBurst(u,null);attackMoveStep(u,null,dt);continue;}if(s.originalMap&&infantryType(u)){const gun=u.cannon!==undefined?s.cannons[u.cannon]:!u.attackMove&&!u.supplyTrip?s.cannons.find(c=>!c.occupant&&dist(u,c)<24):null;if(gun){if(!gun.occupant){gun.occupant=u;u.cannon=s.cannons.indexOf(gun);}u.x=gun.x;u.y=gun.y;const aim=perceive(u,[...s.aliens,...s.nests],360);if(!aim)trackBurst(u,null);if(aim){u.weapon=2;aimHuman(u,aim,0);}continue;}for(let i=s.pickups.length-1;i>=0;i--)if(['auto','plasma','flame','troops','air','tank','blitz'].includes(s.pickups[i].type)&&!(u.type==='soldier'&&u.attackMove&&['troops','air','tank','blitz'].includes(s.pickups[i].type))&&dist(u,s.pickups[i])<18){if(pickup(u,s.pickups[i]))s.pickups.splice(i,1);}}const target=perceive(u,[...s.aliens,...s.nests],u.type==='tank'?300:u.type==='dune-guard'?120:['rider-scout','field-mechanic'].includes(u.type)?180:245);if(!target)trackBurst(u,null);const leader=s.humans.find(a=>a.id===u.leader&&a.alive);if(attackMoveStep(u,target,dt))continue;if(supplyStep(u,target,dt))continue;if(u.order===3){const goal=u.anchor||u;if(dist(u,goal)>20)navigate(u,goal.x-u.x,goal.y-u.y,dt,36);}else if(u.order===1&&leader&&dist(u,leader)>75)navigate(u,leader.x-u.x,leader.y-u.y,dt,36);else if(target&&u.order===2&&dist(u,target)>110)navigate(u,target.x-u.x,target.y-u.y,dt,36);else if(!target&&u.order!==1)patrol(u,dt,24);if(target)aimHuman(u,target,u.order===3?0:u.order===1&&leader&&dist(u,leader)>90?0:dt*.85);}

 }
 for(const a of s.aliens){if(!a.alive)continue;if(a.type==='desert-worm'){window.TriumphDesertWorm.step(a,dt,{humans:s.humans,blocked:wormBlocked,damage,route:(u,target)=>window.TriumphNavigation.step(u,target,wormRouteBlocked,navigationRevision())});continue;}a.cool=Math.max(0,a.cool-dt);const target=perceive(a,[...s.humans.filter(u=>u.alive),...(s.crystal&&!s.crystal.recovered&&s.crystal.y>36?[s.crystal]:[])],240);if(target){const d=dist(a,target);bugIntent(a,target,dt,mult);const desired=Math.atan2(target.y-a.y,target.x-a.x),turn=Math.atan2(Math.sin(desired-a.angle),Math.cos(desired-a.angle));if(d<=55&&a.intent?.mode==='approach')a.angle+=Math.max(-1.0*dt,Math.min(1.0*dt,turn));const offset=Math.atan2(Math.sin(desired-a.angle),Math.cos(desired-a.angle));a.shotOffset=Math.max(-Math.PI/16,Math.min(Math.PI/16,offset));if(d<13&&a.cool<=0){if(target===s.crystal){s.crystal.hp--;sound(56,.4);}else damage(target,1,0);a.cool=1;}else if(d<(a.type==='redbug'?specialistRules.redbug.sight:175)&&Math.abs(offset)<=Math.PI/16&&visible(a,target)&&a.cool<=0&&s.t>=(a.spitDecision||0)){a.spitDecision=s.t+.8+rnd()*1.4;if(rnd()<.5)fire(a);}}else patrol(a,dt,(a.type==='queen'?13:22)*mult);if(a.type==='queen'&&(a.spawnCool||0)<s.t){a.spawnCool=s.t+7;if(s.aliens.filter(a=>a.alive&&a.type!=='queen').length<(s.rules?.maxAliens||50)){spawnGroundBug(a.x+15,a.y+15);}}if(a.type!=='queen')for(const f of s.flowers)if(f.alive&&dist(a,f)<16){f.alive=false;a.type='queen';a.hp=s.difficulty?.queen||50;a.object=152;burst(a.x,a.y,22,'#ca88af');}}
 window.TriumphDesertRiders.updateMines(s.desertMines||[],dt,{aliens:s.aliens,blocked:wormBlocked,visible,damage,burst});
 for(const n of s.nests){if(n.breeding){window.TriumphBreeding.advance(n,dt,{capacity:()=>s.aliens.filter(a=>a.alive&&a.type!=='queen').length<(s.rules?.maxAliens||50),spawn:n=>spawnGroundBug(n.x-25+rnd()*50,n.y+20)});continue;}if(n.hp<=0)continue;n.timer-=dt;if(n.timer<=0){n.timer=n.customInterval||(5+rnd()*4)/mult;if(s.aliens.filter(a=>a.alive&&a.type!=='queen').length<(s.rules?.maxAliens||50)){spawnGroundBug(n.x-25+rnd()*50,n.y+20);}}}
 stepProjectiles(dt);
 for(const c of s.cannons||[])if(c.occupant&&!c.occupant.alive)c.occupant=null;for(const f of s.fires||[])if(f.until>s.t)for(const a of s.aliens)if(a.alive&&dist(a,f)<18)damage(a,1,0);if(s.fires)s.fires=s.fires.filter(f=>f.until>s.t);s.effects=s.effects.filter(e=>(e.t-=dt)>0);s.aliens=s.aliens.filter(a=>a.alive);s.pickupTimer-=dt;if(!s.originalMap&&s.pickupTimer<0){s.pickupTimer=18;if(s.pickups.length<10)s.pickups.push({x:100+rnd()*760,y:60+rnd()*560,type:['troops','grenade','rapid','plasma','tank','air'][Math.floor(rnd()*6)]});}if(s.hold>0)s.hold=Math.max(0,s.hold-dt);
 window.TriumphMissions.emitWaves(s,spawnGroundBug);
 if(s.wave){s.waveRemaining=Math.max(0,s.wave.normalKills-s.waveKills.normal)+Math.max(0,s.wave.queenKills-s.waveKills.queen);if(s.t>=s.wave.start&&s.aliens.length<(s.rules?.maxAliens||50)){s.waveClock-=dt;const advanced=s.wave.queenKills>0&&s.waveKills.normal>=s.wave.normalKills;if(s.waveClock<=0&&s.waveRemaining>0){s.waveClock=advanced?s.wave.queenInterval:s.wave.interval;const x=s.level===4?(rnd()<.5?16:1008):40+rnd()*940,y=rnd()<.5?45:740;if(advanced){const a=unit(x,y,'alien','queen');a.hp=s.difficulty.queen;s.aliens.push(a);}else spawnGroundBug(x,y);}}}if(s.crystal&&s.level===8&&s.wave&&s.waveKills.normal>=s.wave.normalKills&&s.waveKills.queen>=(s.wave.extractionQueenThreshold??40)&&[...Object.keys(s.rules.terminals)].every(id=>s.terminals.some(t=>t.object===Number(id)&&t.active))){s.crystal.extracting=true;s.crystal.y-=20*dt;if(s.crystal.y<-30)s.crystal.recovered=true;}const army=s.humans.filter(u=>u.alive&&u.type!=='commander').length,commanders=s.humans.filter(u=>u.alive&&u.type==='commander').length;if((s.customMission?.objective.rescueCrawlers&&missionProgress().lost)||(s.customMission?.objective.atLeastOneNonCommander&&army===0)||(army===0&&commanders===0&&!hasRespawnSupport())||(s.crystal&&s.crystal.hp<=0)){s.mode='defeat';tone(50,.5);}else if(missionProgress().ready){s.mode='victory';s.merits+=100+army*3+s.kills;tone(600,.3);} }
function missionProgress(){return window.TriumphMissions.progress(s);}
function text(t,x,y,color='#d4e1bf',size=14,align='left'){ctx.fillStyle=color;ctx.font=`bold ${size}px monospace`;ctx.textAlign=align;ctx.fillText(t,x,y);ctx.textAlign='left';}
function variantMark(u){if(!['commando','redbug'].includes(u.type))return;ctx.save();ctx.translate(Math.round(u.x),Math.round(u.y));ctx.rotate(u.angle);ctx.fillStyle='#101710';if(u.type==='commando'){ctx.fillRect(1,-6,5,12);ctx.fillStyle='#4dbaff';ctx.fillRect(2,-5,3,10);ctx.fillRect(0,4,3,3);}else{ctx.fillRect(-6,-7,6,14);ctx.fillStyle='#fa4b4b';ctx.fillRect(-5,-6,4,12);}ctx.restore();}
function soldier(u){if(window.TriumphDesertRiders.isRider(u)){window.TriumphDesertRiders.draw(ctx,u);return;}if(u.shieldUntil>s.t){ctx.strokeStyle='#b9f5fc';ctx.beginPath();ctx.arc(u.x,u.y,24,0,Math.PI*2);ctx.stroke();}if(original&&sprite(u.object||({soldier:52,commando:52,commander:51,tank:146,air:73,robot:460}[u.type]),u.x,u.y,u.angle,u.movingUntil>s.t?1:0)){variantMark(u);if(u.type==='commander'){text('P'+u.id,u.x,u.y-28,colors[u.id-1],12,'center');if(u.selecting){text('↑ ATTACK',u.x,u.y-65,'#fff',11,'center');text('← NORMAL   FOLLOW →',u.x,u.y-50,'#fff',11,'center');text('↓ DEFEND',u.x,u.y-35,'#fff',11,'center');}}return;}ctx.save();ctx.translate(Math.round(u.x),Math.round(u.y));ctx.fillStyle='#675d48';ctx.fillRect(-7,7,15,4);if(u.type==='tank'){ctx.fillStyle='#32392a';ctx.fillRect(-17,-10,34,22);ctx.fillStyle='#73815c';ctx.fillRect(-13,-10,26,18);ctx.fillStyle='#a0aa80';ctx.fillRect(-8,-7,14,12);ctx.rotate(u.angle);ctx.fillStyle='#293126';ctx.fillRect(0,-2,26,5);}else if(u.type==='air'){ctx.fillStyle='#5c7370';ctx.fillRect(-15,-7,28,13);ctx.fillStyle='#8aa09a';ctx.fillRect(-8,-11,14,21);ctx.fillStyle='#353f3b';ctx.fillRect(-22,-2,44,3);ctx.fillRect(-2,-20,3,40);}else{ctx.fillStyle='#303329';ctx.fillRect(-5,4,4,6);ctx.fillRect(2,4,4,6);ctx.fillStyle=u.type==='commander'?colors[u.id-1]:'#687a50';ctx.fillRect(-6,-5,12,10);ctx.fillStyle='#263928';ctx.fillRect(-5,-5,4,8);ctx.fillStyle='#bea784';ctx.fillRect(-4,-11,8,7);ctx.fillStyle='#465939';ctx.fillRect(-5,-13,10,5);ctx.fillStyle='#28342b';ctx.fillRect(-5,-9,10,2);ctx.rotate(u.angle);ctx.fillStyle='#242b26';ctx.fillRect(2,-2,14,3);ctx.fillStyle='#768477';ctx.fillRect(13,-2,3,2);}ctx.restore();variantMark(u);if(u.type==='commander')text(String(u.id),u.x,u.y-20,colors[u.id-1],11,'center');}
function bug(a){if(a.type==='desert-worm'){window.TriumphDesertWorm.draw(ctx,a,s.t);return;}if(original&&sprite(a.object||(a.type==='queen'?152:151),a.x,a.y,a.angle,a.movingUntil>s.t?1:0)){variantMark(a);return;}ctx.save();ctx.translate(Math.round(a.x),Math.round(a.y));ctx.rotate(a.angle);const q=a.type==='queen',r=q?17:7;ctx.strokeStyle='#574f3d';ctx.lineWidth=2;for(let i=-1;i<=1;i++){ctx.beginPath();ctx.moveTo(i*4,-3);ctx.lineTo(i*6-4,-r-5);ctx.lineTo(i*6+2,-r-7);ctx.stroke();ctx.beginPath();ctx.moveTo(i*4,3);ctx.lineTo(i*6-4,r+5);ctx.lineTo(i*6+2,r+7);ctx.stroke();}ctx.fillStyle=q?'#c6a782':'#bda379';ctx.strokeStyle='#615039';ctx.beginPath();ctx.ellipse(-3,0,r,r*.75,0,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#867054';ctx.fillRect(3,-4,8,8);ctx.fillStyle='#e3d494';ctx.fillRect(8,-3,2,2);ctx.fillRect(8,2,2,2);ctx.restore();variantMark(a);}
function drawRock(r){ctx.fillStyle='#71664e';ctx.fillRect(r.x+5,r.y+12,r.w,r.h);ctx.fillStyle=s.level===5?'#7e8880':'#918269';ctx.fillRect(r.x,r.y,r.w,r.h);ctx.strokeStyle='#c0af8c';ctx.strokeRect(r.x+1,r.y+1,r.w-2,r.h-2);ctx.fillStyle='#aa9978';for(let i=8;i<r.w-10;i+=17)ctx.fillRect(r.x+i,r.y+8,5,r.h-18);}
function toggleRally(){if(s.mode!=='playing')return;rallyMode=!rallyMode;drag=null;mouseAim=null;keys.clear();lastMoveClick=null;canvas.focus();updateCommandPanel();}
function addRally(point){if(point.x<12||point.x>W-12||point.y<44||point.y>=H-20||[[0,0],[-4,-4],[4,-4],[-4,4],[4,4]].some(([dx,dy])=>blocked(point.x+dx,point.y+dy)))return false;if(rallyPoints.some(p=>dist(p,point)<20))return false;rallyPoints.push({...point,id:nextRallyId++});return true;}
function removeRally(point){const flag=nearest(point,rallyPoints,22);if(!flag)return false;rallyPoints.splice(rallyPoints.indexOf(flag),1);return true;}
function assignRally(u){if(!['soldier','tank','robot'].includes(u.type))return;const best=window.TriumphRally.choose(u,rallyPoints,s,blocked);if(best){u.attackMove={x:best.x,y:best.y,force:false,rally:best.id};u.order=2;u.patrol=null;}}
function drawRally(){window.TriumphRally.draw(ctx,rallyPoints,text);if(rallyMode)text('RALLY MODE · left-click places · right-click removes · R/Esc exits',W/2,paused?108:57,'#ffdf78',12,'center');}
function selectedCommander(){return s.humans.find(u=>u.type==='commander'&&u.id===activeCommander);}
function selectCommander(id){const deselect=mouseMode==='commander'&&activeCommander===id;lastMoveClick=null;activeCommander=deselect?null:id;mouseMode=deselect?'troops':'commander';selection.clear();drag=null;mouseAim=null;keys.clear();const u=selectedCommander();if(u){u.external=null;u.selecting=false;}canvas.focus();updateCommandPanel();}
function updateCommandPanel(){const tactical=s.mode==='playing'&&paused;canvas.setAttribute('data-tactical',String(tactical));const tacticalButton=document.querySelector('#pause');tacticalButton.textContent=tactical?'Exit tactical mode':'Tactical mode';tacticalButton.setAttribute('aria-pressed',String(tactical));const rally=document.querySelector('#rally');rally.setAttribute('aria-pressed',String(rallyMode));rally.disabled=s.mode!=='playing';rally.title=`R: toggle rally placement (${rallyPoints.length} flags)`;const u=selectedCommander();for(let id=1;id<=4;id++)document.querySelector('#cmd-'+id).setAttribute('aria-pressed',String(mouseMode==='commander'&&activeCommander===id));for(let order=0;order<4;order++){const button=document.querySelector('#order-'+order);button.setAttribute('aria-pressed',String(u?.order===order));button.disabled=!u?.alive||s.mode!=='playing';}const hint=document.querySelector('#command-hint');const message=rallyMode?'Rally placement: left-click clear ground to place a flag; right-click a flag to remove it. R or Escape exits.':mouseMode==='troops'?'Troop control: drag to select troops; right-click to attack-move. Select a commander below for direct control.':'Commander '+activeCommander+': WASD · hold left-click fires · right-click grenade · drag selects troops.';if(hint.textContent!==message)hint.textContent=message;}
function updateMouseFire(u){if(!drag?.mouseIntent||drag.selection||mouseMode!=='commander')return;if(!drag.firing&&s.t-drag.started>=.12){drag.firing=true;interact(u);}if(drag.firing){u.angle=Math.atan2(mouseAim.y-u.y,mouseAim.x-u.x);fire(u,true);}}
function mouseCommanderAction(point,isGrenade=false){const u=selectedCommander();if(!u?.alive||paused||s.mode!=='playing')return;mouseAim=point;u.angle=Math.atan2(point.y-u.y,point.x-u.x);if(isGrenade){if((u.grenadeCool||0)<=s.t){grenade(u);u.grenadeCool=s.t+.330;}}else {interact(u);fire(u,true);}}
function selectable(u){return u.alive&&u.team==='human'&&['soldier','commando','tank','robot','rider-scout','dune-guard','field-mechanic'].includes(u.type);}
function selectTroops(a,b,add=false){activeCommander=null;mouseMode='troops';mouseAim=null;keys.clear();lastMoveClick=null;if(!add)selection.clear();const small=dist(a,b)<6;if(small){const u=nearest(b,s.humans.filter(selectable),23);if(u){if(add&&selection.has(u))selection.delete(u);else selection.add(u);}}else {const left=Math.min(a.x,b.x),right=Math.max(a.x,b.x),top=Math.min(a.y,b.y),bottom=Math.max(a.y,b.y);for(const u of s.humans)if(selectable(u)&&u.x>=left&&u.x<=right&&u.y>=top&&u.y<=bottom)selection.add(u);}for(const u of selection)if(!selectable(u))selection.delete(u);}
function attackMoveTo(point,force=false){const troops=[...selection].filter(selectable);if(!troops.length)return;const columns=Math.ceil(Math.sqrt(troops.length)),rows=Math.ceil(troops.length/columns);troops.forEach((u,i)=>{const raw={x:Math.max(12,Math.min(W-12,point.x+(i%columns-(columns-1)/2)*18)),y:Math.max(42,Math.min(H-18,point.y+(Math.floor(i/columns)-(rows-1)/2)*18))},goal=window.TriumphNavigation?.destination(u,raw,blocked)||raw;if(u.cannon!==undefined){const gun=s.cannons[u.cannon];if(gun?.occupant===u)gun.occupant=null;delete u.cannon;u.weapon=0;}cancelSupply(u);u.useOrder=null;u.focusTarget=null;trackBurst(u,null);u.attackMove={...goal,force};u.order=2;u.patrol=null;});moveMarker={...point,force,until:s.t+1.2};sound(1,.3);}
function usableAt(point){
 const objects=[...(s.doors||[]).filter(d=>!d.destroyed).map(target=>({kind:'door',target,x:target.cx,y:target.cy})),...(s.terminals||[]).map(target=>({kind:'terminal',target,...target})),...(s.cannons||[]).filter(c=>!c.occupant).map(target=>({kind:'cannon',target,...target})),...s.pickups.map(target=>({kind:'pickup',target,...target})),...s.flowers.filter(f=>f.alive).map(target=>({kind:'flower',target,...target})),...(s.crystal&&!s.crystal.recovered?[{kind:'crystal',target:s.crystal,...s.crystal}]:[])];
 return objects.filter(o=>o.kind==='door'?point.x>=o.target.x-8&&point.x<=o.target.x+o.target.w+8&&point.y>=o.target.y-8&&point.y<=o.target.y+o.target.h+8:dist(point,o)<24).sort((a,b)=>dist(point,a)-dist(point,b))[0]||null;
}
function useOrderTo(object){
 const units=[...selection].filter(u=>selectable(u)&&(!['pickup','flower','cannon'].includes(object.kind)||infantryType(u)));if(!units.length)return;
 const job={...object,done:false,desiredOpen:object.kind==='door'?!object.target.open:null};
 for(const u of units){cancelSupply(u);u.attackMove=null;u.focusTarget=null;trackBurst(u,null);if(u.cannon!==undefined){const gun=s.cannons[u.cannon];if(gun?.occupant===u)gun.occupant=null;delete u.cannon;u.weapon=0;}u.useOrder=job;u.order=2;u.patrol=null;}
 moveMarker={x:object.x,y:object.y,use:true,until:s.t+1.2};sound(1,.3);
}
function useSight(u,job){const t=job.target,goal=job.kind==='door'?{x:Math.max(t.x,Math.min(t.x+t.w,u.x)),y:Math.max(t.y,Math.min(t.y+t.h,u.y))}:t,length=dist(u,goal),travel=Math.max(0,length-(job.kind==='door'?7:12)),steps=Math.ceil(travel/3);for(let i=1;i<=steps;i++){const f=travel/length*i/steps;if(blocked(u.x+(goal.x-u.x)*f,u.y+(goal.y-u.y)*f))return false;}return true;}
function useOrderStep(u,dt){
 const job=u.useOrder;if(!job)return false;const t=job.target;
 if(job.done){u.useOrder=null;u.order=3;u.anchor={x:u.x,y:u.y};return true;}
 const present=job.kind==='door'?s.doors.includes(t)&&!t.destroyed:job.kind==='terminal'?s.terminals.includes(t):job.kind==='cannon'?s.cannons.includes(t)&&(!t.occupant||t.occupant===u):job.kind==='pickup'?s.pickups.includes(t):job.kind==='flower'?t.alive:!t.recovered;
 if(!present){job.done=true;return true;}
 const goal=job.kind==='door'?{x:t.cx,y:t.cy}:t,range=job.kind==='door'?42:job.kind==='terminal'?32:job.kind==='crystal'?23:18;
 if(dist(u,goal)>range||!useSight(u,job)){navigate(u,goal.x-u.x,goal.y-u.y,dt,u.type==='tank'?30:36);return true;}
 if(job.kind==='door'){if(t.locked)return true;if(t.open===job.desiredOpen){job.done=true;return true;}if(s.t-(t.lastUse??-10)<=.5)return true;job.done=interact(u,t);}
 else if(job.kind==='terminal')job.done=interact(u,t);
 else if(job.kind==='pickup'){if(pickup(u,t)){s.pickups.splice(s.pickups.indexOf(t),1);job.done=true;}}
 else if(job.kind==='flower'){t.alive=false;burst(t.x,t.y,15,'#a588bc');job.done=true;}
 else if(job.kind==='cannon'){t.occupant=u;u.cannon=s.cannons.indexOf(t);u.x=t.x;u.y=t.y;u.weapon=2;job.done=true;}
 else{if(s.level===7)t.recovered=true;job.done=true;}
 return true;
}
function enemyAt(point){return nearest(point,[...s.aliens,...s.nests].filter(a=>(a.type!=='desert-worm'||window.TriumphDesertWorm.exposed(a))&&a.alive!==false&&a.hp>0&&dist(point,a)<(s.nests.includes(a)?30:a.type==='queen'?23:16)),32);}
function focusAttackTo(target){
 if(!target||target.alive===false||target.hp<=0||(target.type==='desert-worm'&&!window.TriumphDesertWorm.exposed(target)))return;
 for(const u of selection){if(!selectable(u))continue;cancelSupply(u);u.useOrder=null;u.attackMove=null;if(u.focusTarget!==target)trackBurst(u,null);u.focusTarget=target;u.order=2;u.patrol=null;if(u.cannon!==undefined){const gun=s.cannons[u.cannon];if(gun?.occupant===u)gun.occupant=null;delete u.cannon;u.weapon=0;}}
 moveMarker={x:target.x,y:target.y,focus:true,until:s.t+1.2};sound(1,.3);
}
function focusAttackStep(u,dt){
 const target=u.focusTarget;if(!target)return false;
 if(target.alive===false||target.hp<=0||(target.type==='desert-worm'&&!window.TriumphDesertWorm.exposed(target))||!s.aliens.includes(target)&&!s.nests.includes(target)){u.focusTarget=null;trackBurst(u,null);u.order=3;u.anchor={x:u.x,y:u.y};return false;}
 const range=u.type==='tank'?300:u.type==='dune-guard'?120:['rider-scout','field-mechanic'].includes(u.type)?180:u.weapon===1?145:245;
 if(dist(u,target)>=range||!visible(u,target)){trackBurst(u,null);navigate(u,target.x-u.x,target.y-u.y,dt,u.type==='tank'?30:36);return true;}
 aimHuman(u,target,dt*.85);return true;
}
// Short opportunistic detours use the next terrain-route segment, never the straight
// line through a wall. Keep the player's destination until pickup or mounting.
function attackMoveInteraction(u,target,dt){
 if(u.type!=='soldier'||!s.originalMap||!u.attackMove||u.attackMove.force||u.useOrder||u.focusTarget||u.cannon!==undefined)return false;
 const revision=navigationRevision(),nav=window.TriumphNavigation,next=nav?.step(u,u.attackMove,humanRouteBlocked,revision)||u.attackMove;
 const dx=next.x-u.x,dy=next.y-u.y,length=dx*dx+dy*dy;
 const nearby=p=>{if(dist(u,p)>56)return false;const t=length?Math.max(0,Math.min(1,((p.x-u.x)*dx+(p.y-u.y)*dy)/length)):0;if(Math.hypot(p.x-u.x-dx*t,p.y-u.y-dy*t)>24)return false;return nav?nav.routeDistance(u,p,humanRouteBlocked,revision)<=72:!blocked(p.x,p.y)&&visible(u,p);};
 const threat=target||nearest(u,[...s.aliens,...s.nests].filter(a=>a.alive!==false&&a.hp>0&&visible(u,a)),245);
 const eagles=()=>s.pickups.filter(p=>['troops','air','tank','blitz'].includes(p.type)&&nearby(p)&&reinforcementRule(p.type)&&(!eagleClaims.has(p)||eagleClaims.get(p)===u)).sort((a,b)=>dist(u,a)-dist(u,b));
 const guns=()=>s.cannons.filter(c=>!c.occupant&&nearby(c)).sort((a,b)=>dist(u,a)-dist(u,b));
 const eagle=!threat?eagles()[0]:null,gun=(!eagle?guns()[0]:null),goal=eagle||gun;
 if(!goal)return false;
 trackBurst(u,null);
 if(dist(u,goal)>18)navigate(u,goal.x-u.x,goal.y-u.y,dt,36);
 else if(eagle){const index=s.pickups.indexOf(eagle);if(index>=0&&pickup(u,eagle))s.pickups.splice(index,1);}
 else if(!gun.occupant){gun.occupant=u;u.cannon=s.cannons.indexOf(gun);u.x=gun.x;u.y=gun.y;u.weapon=2;}
 return true;
}
function attackMoveStep(u,target,dt){if(attackMoveInteraction(u,target,dt))return true;const goal=u.attackMove;if(!goal)return false;if(!goal.force&&target&&dist(u,target)<160){aimHuman(u,target,dt*.5);return true;}if(dist(u,goal)>12)navigate(u,goal.x-u.x,goal.y-u.y,dt,u.type==='tank'?30:36);else {u.attackMove=null;u.order=3;u.anchor={x:u.x,y:u.y};}return true;}
function pointerPoint(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height};}
canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('pointerdown',e=>{if(s.mode!=='playing'||document.querySelector('#controls').open||document.querySelector('#unit-guide').open)return;if(e.button!==0&&e.button!==2)return;e.preventDefault();canvas.focus();window.TriumphMusic?.unlock();const p=pointerPoint(e);if(p.y<36)return;if(rallyMode){if(e.button===0)addRally(p);else removeRally(p);updateCommandPanel();return;}if(e.button===2){if(mouseMode==='troops'&&[...selection].some(selectable)){const now=e.timeStamp??s.t*1000,double=!!lastMoveClick&&now-lastMoveClick.time>=0&&now-lastMoveClick.time<350&&dist(p,lastMoveClick.point)<20,remembered=double?lastMoveClick.target:null,focus=remembered||enemyAt(p),usable=double?(lastMoveClick.usable||usableAt(p)):usableAt(p);if(focus){if(focus.alive!==false&&focus.hp>0)focusAttackTo(focus);}else if(double&&usable)useOrderTo(usable);else attackMoveTo(p,double);lastMoveClick=double?null:{time:now,point:p,target:focus,usable};}else mouseCommanderAction(p,true);return;}mouseAim=p;drag={start:p,end:p,add:e.shiftKey,id:e.pointerId,started:s.t,firing:false,selection:false,mouseIntent:!paused&&mouseMode==='commander'&&!e.shiftKey&&!nearest(p,s.humans.filter(selectable),23)};canvas.setPointerCapture(e.pointerId);});
canvas.addEventListener('pointermove',e=>{const p=pointerPoint(e);if(drag&&e.pointerId===drag.id){drag.end=p;if(drag.firing)mouseAim=p;else if(dist(drag.start,p)>=6)drag.selection=true;}else if(mouseMode==='commander')mouseAim=p;});
canvas.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.id||e.button!==0)return;const ended=drag;drag=null;const p=pointerPoint(e);if(s.mode==='playing'&&!ended.firing){if(ended.selection||dist(ended.start,p)>=6||nearest(p,s.humans.filter(selectable),23)||ended.add){selectTroops(ended.start,p,ended.add);mouseMode='troops';}else if(mouseMode==='commander')mouseCommanderAction(p);else {selection.clear();activeCommander=null;mouseMode='troops';}}if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);});
canvas.addEventListener('pointercancel',()=>{drag=null;});
canvas.addEventListener('lostpointercapture',()=>{drag=null;});
function drawSelection(){ctx.save();const commander=selectedCommander();if(mouseMode==='commander'&&commander?.alive){ctx.strokeStyle=colors[activeCommander-1];ctx.beginPath();ctx.ellipse(commander.x,commander.y+5,16,10,0,0,Math.PI*2);ctx.stroke();}ctx.strokeStyle='#9bf76b';ctx.lineWidth=1.5;for(const u of selection){if(!selectable(u)){selection.delete(u);continue;}ctx.beginPath();ctx.ellipse(u.x,u.y+5,u.type==='tank'?22:13,8,0,0,Math.PI*2);ctx.stroke();}if(drag&&!drag.firing){const x=Math.min(drag.start.x,drag.end.x),y=Math.min(drag.start.y,drag.end.y),w=Math.abs(drag.end.x-drag.start.x),h=Math.abs(drag.end.y-drag.start.y);ctx.fillStyle='#9bf76b20';ctx.fillRect(x,y,w,h);ctx.strokeRect(x,y,w,h);}if(moveMarker&&moveMarker.until>s.t){ctx.strokeStyle=moveMarker.focus?'#fa7770':moveMarker.use?'#73e5df':moveMarker.force?'#68c9f5':'#ffe77b';ctx.beginPath();ctx.arc(moveMarker.x,moveMarker.y,10,0,Math.PI*2);ctx.moveTo(moveMarker.x-15,moveMarker.y);ctx.lineTo(moveMarker.x+15,moveMarker.y);ctx.moveTo(moveMarker.x,moveMarker.y-15);ctx.lineTo(moveMarker.x,moveMarker.y+15);ctx.stroke();}for(const target of new Set([...selection].filter(selectable).map(u=>u.focusTarget).filter(a=>a&&a.hp>0&&a.alive!==false))){ctx.strokeStyle='#fa7770';ctx.beginPath();ctx.arc(target.x,target.y,s.nests.includes(target)?34:23,0,Math.PI*2);ctx.stroke();}if(selection.size)text(selection.size+' SELECTED',10,H-12,'#b7f5a0',12);ctx.restore();}
function draw(){ctx.imageSmoothingEnabled=false;if(background.complete===undefined||background.complete&&background.naturalWidth)ctx.drawImage(background,0,0);else {ctx.fillStyle='#af9e76';ctx.fillRect(0,0,W,H);}if(s.customMission?.objective.extractLivingGroundHumans||s.customMission?.objective.rescueCrawlers){const e=s.customMission.objective.extractLivingGroundHumans||s.customMission.objective.rescueCrawlers;ctx.save();ctx.strokeStyle='#73e5df';ctx.fillStyle='#73e5df18';ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y,e.radius,0,Math.PI*2);ctx.fill();ctx.stroke();text(s.customMission.objective.rescueCrawlers?'EXTRACTION · SAVE ONE CRAWLER':'EXTRACTION · RETURN ALL SURVIVORS',e.x,e.y+e.radius+16,'#73e5df',12,'center');ctx.restore();}for(const r of s.rocks)drawRock(r);if(s.gate&&!s.gate.open){drawRock(s.gate);ctx.fillStyle='#394c3a';ctx.fillRect(s.gate.x+4,s.gate.y+4,s.gate.w-8,s.gate.h-8);}
 for(const f of s.flowers)if(f.alive){if(original&&sprite(f.object||108,f.x,f.y))continue;ctx.fillStyle='#536735';ctx.fillRect(f.x-2,f.y-5,4,17);ctx.fillStyle='#9b72b1';for(let i=0;i<6;i++){const a=i*Math.PI/3;ctx.fillRect(f.x+Math.cos(a)*7-3,f.y+Math.sin(a)*5-3,6,5);}ctx.fillStyle='#d6b479';ctx.fillRect(f.x-2,f.y-2,4,4);}
 for(const n of s.nests)if(n.hp>0){if(original&&sprite(n.object||74,n.x,n.y,0,n.breeding?.busy?2:0,window.TriumphBreeding.frame(n)))continue;ctx.fillStyle='#695845';ctx.beginPath();ctx.ellipse(n.x,n.y+12,32,15,0,0,7);ctx.fill();for(let i=3;i>=0;i--){ctx.fillStyle=['#b59671','#c7ac87','#ddc09b','#e6d1b1'][i];ctx.beginPath();ctx.ellipse(n.x,n.y+i*3,24-i*3,15-i*3,0,0,7);ctx.fill();}ctx.fillStyle='#614d3e';ctx.fillRect(n.x-6,n.y+6,12,8);}
 for(const d of s.doors||[])if(!d.open)sprite(d.object,d.cx,d.cy);for(const t of s.terminals||[])sprite(t.object,t.x,t.y,0,t.active?11:0);for(const p of s.props||[])if(p.hp>0)sprite(p.object,p.x,p.y);for(const c of s.cannons||[])sprite(c.object,c.x,c.y,c.occupant?.angle||0,c.occupant?11:10);for(const f of s.fires||[]){ctx.fillStyle=s.t% .2<.1?'#fa982c':'#eddf71';ctx.fillRect(f.x-12,f.y-10,24,18);}if(s.terminal){ctx.fillStyle='#293731';ctx.fillRect(s.terminal.x-11,s.terminal.y-12,22,24);ctx.fillStyle=s.terminal.active?'#8bf259':'#e7a14d';ctx.fillRect(s.terminal.x-7,s.terminal.y-8,14,11);}if(s.crystal){if(s.crystal.extracting)sprite(579,510,241);if(original)sprite(s.crystal.object||547,s.crystal.x,s.crystal.y);else {ctx.fillStyle=s.crystal.recovered?'#e8ef98':'#7edfe5';ctx.beginPath();ctx.moveTo(s.crystal.x,s.crystal.y-19);ctx.lineTo(s.crystal.x+12,s.crystal.y);ctx.lineTo(s.crystal.x,s.crystal.y+15);ctx.lineTo(s.crystal.x-12,s.crystal.y);ctx.closePath();ctx.fill();ctx.strokeStyle='#d9ffff';ctx.stroke();}}
 for(const m of s.desertMines||[]){ctx.fillStyle=m.age<window.TriumphDesertRiders.rules.mineArm?'#dbc88d':'#cc653e';ctx.fillRect(m.x-4,m.y-4,8,8);}
 for(const p of s.pickups){if(['troops','air','tank','blitz'].includes(p.type)){const reason=reinforcementStatus(p.type).reason;if(reason){const x=Math.max(100,Math.min(W-100,p.x)),y=Math.min(H-12,p.y+24),width=reason.length*6+12;ctx.fillStyle='#14201ef2';ctx.fillRect(x-width/2,y-12,width,17);text(reason,x,y,'#f2cc7d',10,'center');}}if(original&&sprite(p.object||({troops:63,tank:65,air:64,auto:53,rapid:55,flame:55,plasma:54,grenade:56,blitz:99}[p.type]),p.x,p.y))continue;const pc={troops:'#f5d54d',tank:'#b78340',air:'#8ad9fa',rapid:'#ef716b',plasma:'#89b8ed',grenade:'#9aaa66'};ctx.fillStyle='#695e49';ctx.fillRect(p.x-11,p.y-9,22,19);ctx.fillStyle=pc[p.type];ctx.beginPath();ctx.moveTo(p.x,p.y+8);ctx.lineTo(p.x-10,p.y-5);ctx.lineTo(p.x-2,p.y-3);ctx.lineTo(p.x,p.y-9);ctx.lineTo(p.x+2,p.y-3);ctx.lineTo(p.x+10,p.y-5);ctx.closePath();ctx.fill();}
 for(const r of s.reinforcements)if(r.kind!=='infiltration')sprite(r.object,r.x,r.y,r.angle,r.path?.pause>0?0:1);for(const d of s.drops)sprite(d.object,d.x,d.y,d.angle,0,Math.min(d.frames-1,Math.floor(d.age/d.duration*d.frames)));window.TriumphVents.draw(ctx,s.vents,sprite);const units=[...s.humans.filter(u=>u.alive&&s.cannons?.[u.cannon]?.occupant!==u),...s.aliens].sort((a,b)=>a.y-b.y);for(const u of units)u.team==='human'?soldier(u):bug(u);for(const b of s.bullets){ctx.fillStyle=b.team==='alien'?'#3a3028':b.plasma?'#7cceff':'#fff2a0';ctx.fillRect(b.x-2,b.y-2,b.plasma?5:3,3);}for(const e of s.effects){ctx.fillStyle=e.color;for(let i=0;i<8;i++){const a=i*Math.PI/4,r=e.size*(1-e.t/.5);ctx.fillRect(e.x+Math.cos(a)*r-3,e.y+Math.sin(a)*r-3,6,6);}}
 drawRally();drawSelection();ctx.fillStyle='#1b2319';ctx.fillRect(0,0,W,36);ctx.strokeStyle='#617047';ctx.strokeRect(0,0,W,36);for(let i=0;i<4;i++){const u=s.humans.find(a=>a.id===i+1);text(`P${i+1} ${String(s.score[i]).padStart(5,'0')}`,18+i*220,15,colors[i],15);text(u.alive?`${orders[u.order]}  G:${u.grenades}${u.weapon?'  '+(u.weapon===1?'FLAME':'PLASMA'):''}`:hasRespawnSupport()?`RETURN IN ${Math.ceil(u.respawn)}s`:'NEED REINFORCEMENTS',18+i*220,29,colors[i],11);}text(`ARMY ${s.humans.filter(u=>u.alive&&u.type!=='commander').length}`,900,15,'#cdd3aa',13,'center');text(s.waveRemaining>0?`WAVE ${s.waveRemaining}`:s.hold>0?`HOLD ${Math.ceil(s.hold)}s`:s.customId?'CUSTOM':`M${s.level+1} / 9`,900,29,'#cdd3aa',13,'center');
 if(s.mode==='playing')text(missionProgress().label,W-12,H-8,'#e4e5ac',12,'right');
 if(s.mode==='playing'&&paused){ctx.save();ctx.strokeStyle='#55ddda';ctx.lineWidth=3;ctx.strokeRect(4,38,W-8,H-42);ctx.strokeStyle='#9bf7c0';ctx.lineWidth=6;for(const [x,y,dx,dy] of [[10,44,1,1],[W-10,44,-1,1],[10,H-10,1,-1],[W-10,H-10,-1,-1]]){ctx.beginPath();ctx.moveTo(x+42*dx,y);ctx.lineTo(x,y);ctx.lineTo(x,y+42*dy);ctx.stroke();}ctx.fillStyle='#082b34f2';ctx.fillRect(W/2-225,43,450,48);ctx.strokeStyle='#55ddda';ctx.lineWidth=1;ctx.strokeRect(W/2-225,43,450,48);text('TACTICAL MODE',W/2,64,'#a4fff0',20,'center');text('Issue orders · Space / Escape to execute',W/2,83,'#b8e6e4',12,'center');ctx.restore();}
 if(s.mode!=='playing'){ctx.fillStyle='#061006df';ctx.fillRect(145,105,734,550);ctx.strokeStyle='#538c37';ctx.strokeRect(145,105,734,550);text('TRIUMPH!',512,210,'#c5d4bb',54,'center');text('WAR 2099 · RECONSTRUCTION',512,243,'#75d24c',19,'center');let heading=s.mode==='briefing'?(s.customId?`CUSTOM: ${currentMission().name}`:`MISSION ${s.level+1}: ${currentMission().name}`):s.mode==='victory'?'MISSION COMPLETE':s.mode==='defeat'?'ARMY LOST':'TACTICAL MODE';text(heading,512,299,'#dfd5ad',21,'center');const lines=s.mode==='briefing'?currentMission().brief.match(/.{1,68}(?:\s|$)|.{1,68}/g)?.slice(0,8):s.mode==='victory'?[`Merits: ${s.merits}`,s.customId?'Enter replays this custom mission.':s.level===8?'Campaign complete. Enter starts a new campaign.':'Enter advances to the next mission.']:s.mode==='defeat'?[s.customId?'Enter retries this custom mission.':s.merits>=100?'Continue costs 100 merits. Press Enter.':'Not enough merits. Enter restarts the campaign.']:['Space or Tactical mode returns to action.'];lines?.forEach((l,i)=>text(l.trim(),512,344+i*24,'#b8cfa5',15,'center'));if(s.mode==='briefing'){text('SELECT ANY COMMANDER · WASD + MOUSE',512,567,'#9ac6a2',14,'center');text('ENTER TO DEPLOY IN TACTICAL MODE',512,601,'#7ede46',17,'center');text(s.terrainId?'Custom terrain · recovered and custom actor visuals.':s.customId?'Custom scenario using recovered terrain and sprites.':'Original sprites and map placements recovered from your installed game.',512,632,'#849278',11,'center');}}
}
function advance(){window.TriumphMusic?.unlock();if(s.mode==='briefing'){s.mode='playing';paused=true;drag=null;keys.clear();canvas.focus();tone(400,.15);}else if(s.customId&&(s.mode==='victory'||s.mode==='defeat'))restartMission();else if(s.mode==='victory')begin(s.level===8?0:s.level+1,s.level===8?0:s.merits);else if(s.mode==='defeat')begin(s.merits>=100?s.level:0,s.merits>=100?s.merits-100:0);else paused=!paused;}
document.querySelector('#rally').onclick=toggleRally;
for(let id=1;id<=4;id++)document.querySelector('#cmd-'+id).onclick=()=>selectCommander(id);for(let order=0;order<4;order++)document.querySelector('#order-'+order).onclick=()=>{const u=selectedCommander();if(u?.alive&&s.mode==='playing'){giveOrder(u,order);canvas.focus();updateCommandPanel();}};
window.addEventListener('keydown',e=>{window.TriumphMusic?.unlock();if(document.querySelector('#controls').open||document.querySelector('#unit-guide').open)return;if(presets.flat().includes(e.code)||['Space','Enter'].includes(e.code))e.preventDefault();const repeat=keys.has(e.code);keys.add(e.code);if(repeat||e.repeat)return;if(e.code==='KeyR'&&s.mode==='playing'){e.preventDefault();toggleRally();return;}if(e.code==='Escape'&&rallyMode){e.preventDefault();toggleRally();return;}if(e.code==='Space'||e.code==='Escape'){paused=!paused;drag=null;}if(e.code==='Enter')advance();if(e.code==='F2'){e.preventDefault();restartMission();}if(s.mode==='playing'&&mouseMode==='commander')for(let i=0;i<4;i++){if(i+1!==activeCommander)continue;const u=s.humans.find(a=>a.id===i+1);const binding=i+1===activeCommander?presets[0]:presets[i];if(i===0&&activeCommander!==1)continue;if(u.selecting&&binding.slice(0,4).includes(e.code)){giveOrder(u,[2,3,0,1][binding.indexOf(e.code)]);continue;}if(e.code===binding[4]&&u.alive&&!paused)interact(u);if(e.code===binding[5]){const u=s.humans.find(a=>a.id===i+1);if(!u.alive)continue;if(keys.has(binding[4])&&!paused){grenade(u);u.grenadeCool=s.t+.330;}else u.selecting=true;}}});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{drag=null;keys.clear();if(s.mode==='playing')paused=true;});
document.querySelector('#difficulty').onchange=()=>restartMission();
document.querySelector('#mission').onchange=e=>{const value=e.target.value;if(window.TriumphCustomMissions.get(value))loadCustomMission(value);else loadOriginal(Number(value));};
document.querySelector('#start').onclick=()=>{advance();canvas.focus();};document.querySelector('#pause').onclick=()=>{paused=!paused;drag=null;canvas.focus();};document.querySelector('#reset').onclick=()=>{restartMission();canvas.focus();};document.querySelector('#options').onclick=()=>{controlsWasPaused=paused;paused=true;drag=null;keys.clear();document.querySelector('#controls').showModal();};document.querySelector('#close').onclick=()=>{document.querySelector('#controls').close();paused=controlsWasPaused;canvas.focus();};
window.triumph={state:()=>JSON.parse(JSON.stringify({mission:s.customId?null:s.level+1,customId:s.customId||null,merits:s.merits,mode:s.mode,paused,time:s.t,activeCommander,mouseMode,rallyMode,rallyPoints,missionProgress:missionProgress(),selectedTroops:[...selection].filter(selectable).map(u=>({x:u.x,y:u.y,type:u.type,attackMove:u.attackMove,useOrder:u.useOrder?{kind:u.useOrder.kind,x:u.useOrder.x,y:u.useOrder.y}:null,focusTarget:u.focusTarget?{x:u.focusTarget.x,y:u.focusTarget.y,hp:u.focusTarget.hp}:null})),army:s.humans.filter(u=>u.alive&&u.type!=='commander').length,commanders:s.humans.filter(u=>u.type==='commander'),aliens:s.aliens,vents:s.vents,nests:s.nests,pickups:s.pickups,gate:s.gate,doors:s.doors,terminals:s.terminals,props:s.props,cannons:(s.cannons||[]).map(c=>({...c,occupant:c.occupant?{alive:c.occupant.alive}:null})),reinforcements:s.reinforcements.map(({path,...r})=>r),drops:s.drops,crystal:s.crystal,waveRemaining:s.waveRemaining,waveKills:s.waveKills})),loadMission:(level)=>{if(!Number.isInteger(level)||level<1||level>9)throw Error('Mission must be 1–9');loadOriginal(level-1);},loadCustomMission,customMissions:window.TriumphCustomMissions.list,command:(id,q)=>{if(![2,3].includes(id))throw Error('Assistant controls commanders 2 and 3');const u=s.humans.find(a=>a.id===id);u.external={...q,until:s.t+Math.min(3,Math.max(.05,q.seconds||.5))};if(q.order!==undefined)giveOrder(u,typeof q.order==='number'?q.order:null);if(q.grenade)grenade(u);},missions};
function frame(now){const dt=Math.min(.04,(now-last)/1000||0);last=now;update(dt);draw();updateCommandPanel();requestAnimationFrame(frame);}begin();updateCommandPanel();requestAnimationFrame(frame);
})();
