'use strict';
if(require.main===module)process.chdir(require('node:path').resolve(__dirname,'..'));
const fs=require('node:fs'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const baseline=execFileSync('git',['show','1e866aafd06268e6dc47ae3b791b5a2dd2e1dad0:game.js'],{encoding:'utf8',windowsHide:true});
const fixture=fs.readFileSync('tools/check-recreation.cjs','utf8').split('const api=sandbox.window.triumph')[0];
const anchor="let source=fs.readFileSync(''+file,'utf8');",replacement="let source=file==='game.js'&&baseline?baseline:fs.readFileSync(''+file,'utf8');";
function inject(source){assert.equal(source.split(anchor).length-1,1,'Support baseline loader anchor must exist exactly once');const result=source.replace(anchor,replacement);assert(!result.includes(anchor)&&result.split(replacement).length-1===1,'Support baseline substitution must apply exactly once');return result;}
assert.throws(()=>inject(fixture.replace(anchor,'')),/exactly once/);assert.throws(()=>inject(fixture+'\n'+anchor),/exactly once/);
function load(old){return new Function('require','module','__dirname','baseline',inject(fixture)+'\nreturn {sandbox,handlers,elements};')(require,{},__dirname,old?baseline:null);}
const plain=value=>{const seen=new Map();return JSON.parse(JSON.stringify(value,(key,v)=>{if(v&&typeof v==='object'){if(seen.has(v))return {$ref:seen.get(v)};seen.set(v,seen.size);}return v;}));};
function sequence(box,mission,seed){const {sandbox:b,elements:e,handlers:h}=box,api=b.window.triumph,out=[];api.loadMission(mission);let f=b.window.__fixture(),s=f.state;f.setSeed(seed);const snap=label=>out.push([label,plain({world:f.state})]);snap('initialized');
 for(const type of ['troops','tank','air','blitz']){const result=f.reinforce(type);snap([type,result]);}
 s.rules={...s.rules,maxAliens:0};s.t+=1;f.updateSupport(.04);snap('cap retry');s.rules.maxAliens=100;for(let i=0;i<350;i++){s.t+=.04;f.updateSupport(.04);if(i%25===0)snap('delivery '+i);}snap('delivered');for(let i=0;i<5;i++)f.spawnGroundBug(400+i*20,400);snap('delivery RNG continuation');
 // Dead commander return, incoming support survives army depletion, and tactical freeze.
 const u=s.humans.find(u=>u.type==='commander');f.kill(u,0);s.mode='playing';if(!api.state().paused)e['#pause'].onclick();const t=s.t;f.update(.4);assert.equal(s.t,t,'Tactical freeze preserves support clock');snap('frozen');e['#pause'].onclick();for(let i=0;i<260;i++)f.update(.04);snap('return');assert(u.alive,'Commander returns with army/support');
 h.keydown({code:'F2',preventDefault(){}});f=b.window.__fixture();s=f.state;assert.equal(s.reinforcements.length,0,'Restart clears support');assert.equal(s.drops.length,0,'Restart clears drops');snap('restart');
 api.loadCustomMission('custom-flash-silent-return');f=b.window.__fixture();s=f.state;f.setSeed(seed);assert(s.customAirPending);s.t=20;s.rules={...s.rules,maxAliens:0};f.updateSupport(.04);assert.equal(s.reinforcements.length,3);snap('scheduled');for(let i=0;i<500;i++){s.t+=.04;f.updateSupport(.04);}assert.equal(s.drops.length,0,'Scheduled cap holds delivery');assert(s.reinforcements.every(r=>!r.scheduledDropped),'Scheduled delivery retries');snap('reserved cap wait');s.rules.maxAliens=s.humans.filter(u=>u.alive&&['soldier','commando'].includes(u.type)).length+1;f.updateSupport(.04);assert.equal(s.drops.length,1,'Scheduled arrivals reserve one available slot');snap('one reservation');s.rules.maxAliens=100;for(let i=0;i<600;i++){s.t+=.04;f.updateSupport(.04);if(i%100===0)snap('scheduled delivery '+i);}assert.equal(s.reinforcements.length,0);assert.equal(s.drops.length,0);snap('scheduled exited');
 s.humans.forEach(u=>u.alive=false);assert.equal(f.hasRespawnSupport(),false,'No army/support prevents return');snap('no return support');api.loadMission(3);f=b.window.__fixture();f.setSeed(seed);f.reinforce('air');snap('replacement current state');for(let i=0;i<5;i++)f.spawnGroundBug(400+i*20,400);snap('RNG continuation');return out;
}
for(const mission of [1,3,6])for(const seed of [77,812])assert.deepEqual(sequence(load(false),mission,seed),sequence(load(true),mission,seed),'Immutable support sequence mission '+mission+' seed '+seed);
console.log('Passed six immutable support sequences: source eligibility, cap retry, carrier/air/infiltration delivery and exit, tactical freeze, death/commander return, restart/replacement, scheduled reservations and pending-arrival lifecycle.');
