'use strict';
process.chdir(require('node:path').resolve(__dirname,'..'));
const fs=require('fs'),assert=require('assert/strict');
const source=fs.readFileSync('tools/check-recreation.cjs','utf8').split('const api=sandbox.window.triumph')[0],plain=v=>JSON.parse(JSON.stringify(v));
function fresh(){const b=new Function('require','module','__dirname',source+';return {sandbox,elements};')(require,{},__dirname);b.w=b.sandbox.window;b.w.triumph.loadCustomMission('custom-jungle-canopy-recon');b.f=b.w.__fixture();b.s=b.f.state;b.r=b.w.TriumphRecon;return b;}
function arena(){const b=fresh();b.u=b.s.humans.find(u=>u.type==='recon');Object.assign(b.u,{x:400,y:400,angle:0,order:3,anchor:{x:400,y:400},cool:0});Object.assign(b.s,{t:0,mode:'playing',mask:null,rocks:[],doors:[],props:[],nests:[],vents:[],pickups:[],cannons:[],bullets:[],humans:[b.u],aliens:[],customWaves:null,jungleAmbushes:[]});b.terrain={W:1024,H:768,blocked:b.f.blocked};return b;}
const bullet=(x=380,y=400)=>({x,y,dx:1,dy:0,speed:120,life:2,team:'alien',damage:1,owner:0});
const melee={kind:'melee',x:390,y:400};
// Real production health eligibility: every supplied infantry remains1HP and1damage is lethal.
{const b=fresh();for(const m of b.w.TriumphCustomMissions.list){b.w.triumph.loadCustomMission(m.id);const f=b.w.__fixture();for(const u of f.state.humans.filter(f.infantryType).filter(u=>u.type!=='heavy-trooper'))assert.equal(u.hp,1,'No existing healable starting infantry');}for(let n=1;n<=9;n++){b.w.triumph.loadMission(n);const f=b.w.__fixture();for(const u of f.state.humans.filter(f.infantryType))assert.equal(u.hp,1);}const a=arena();a.u.recon.readyAt=100;a.f.damage(a.u,1,0,melee);assert(!a.u.alive,'No surviving ordinary integer-damage injury');}
// Prediction boundary, hostile/live filtering, screened projectile and no arbitrary movement immunity.
{const b=arena();assert(b.r.imminent(b.u,bullet(),b.terrain));assert(!b.r.imminent(b.u,bullet(373),b.terrain));assert(!b.r.imminent(b.u,{...bullet(),team:'human'},b.terrain));assert(!b.r.imminent(b.u,{...bullet(),life:0},b.terrain));b.s.doors=[{x:386,y:380,w:2,h:40,open:false,locked:true}];assert(!b.r.imminent(b.u,bullet(),b.terrain));b.s.doors=[];b.f.move(b.u,1,0,.02,36);assert(!b.r.active(b.u,0));}
// Production simulation starts early, consumes one shared cooldown and blocks firing until dash ends.
{const b=arena();b.s.bullets=[bullet()];b.elements['#pause'].onclick();b.f.update(.02);assert(b.u.recon.dash);assert.equal(b.u.recon.readyAt,3.02);const order=b.u.order,anchor=plain(b.u.anchor),initial=b.s.bullets.length;b.f.fire(b.u);assert.equal(b.s.bullets.length,initial);b.f.update(.1);assert(b.u.y>400);assert.equal(b.u.hp,1);assert.equal(b.u.order,order);assert.deepEqual(plain(b.u.anchor),anchor);b.f.update(.15);assert(!b.u.recon.dash);assert(Math.hypot(b.u.x-400,b.u.y-400)<=48.001);b.u.cool=0;b.f.fire(b.u);assert(b.s.bullets.some(q=>q.team==='human'));b.s.t=1;assert(!b.r.start(b.u,1,melee,b.terrain));b.s.t=3.02;assert(b.r.start(b.u,3.02,melee,b.terrain));}
// Melee resolution starts defensive movement immediately; no legal route means lethal hit with no immunity.
{const b=arena();b.f.damage(b.u,1,0,melee);assert(b.u.alive&&b.r.active(b.u,0));b.s.t=.25;b.r.step(b.u,.25,[],b.terrain);assert.equal(b.u.recon.dash,null);assert(!b.r.active(b.u,.25));b.f.damage(b.u,1,0,melee);assert(!b.u.alive,'Cooldown prevents repeated melee immunity');}
for(const kind of ['terrain','door','bounds']){const b=arena();if(kind==='terrain')b.terrain.blocked=(x,y)=>Math.hypot(x-400,y-400)>1;if(kind==='door')b.s.doors=[{x:398,y:402,w:4,h:80,open:false},{x:398,y:318,w:4,h:80,open:false},{x:402,y:398,w:80,h:4,open:false}];if(kind==='bounds'){b.u.x=12;b.u.y=38;b.terrain.blocked=(x,y)=>x>13||y>39;}assert(!b.r.start(b.u,0,kind==='bounds'?{kind:'melee',x:22,y:38}:melee,b.terrain),kind+' denies all routes');assert(!b.r.active(b.u,0));if(kind!=='terrain'&&kind!=='bounds'){b.f.damage(b.u,1,0,melee);assert(!b.u.alive);}}
{const b=arena();b.s.rocks=[{x:360,y:385,w:80,h:1},{x:360,y:408,w:80,h:1}];b.s.bullets=[bullet()];b.elements['#pause'].onclick();for(let n=0;n<10&&b.u.alive;n++)b.f.update(.02);assert(!b.u.alive,'Stationary corridor has no safe side route; projectile hits');assert.equal(b.u.recon.readyAt,0,'No route grants neither immunity nor a dash');}
// Thin obstacles along the sweep cannot be crossed even when endpoint is clear; a shorter legal dash is allowed.
{const b=arena();b.s.doors=[{x:398,y:415,w:4,h:1,open:false},{x:398,y:380,w:4,h:1,open:false},{x:415,y:398,w:1,h:4,open:false}];assert(b.r.start(b.u,0,melee,b.terrain));assert(Math.hypot(b.u.recon.dash.to.x-400,b.u.recon.dash.to.y-400)<=12.001);}
// Moving Recon prefers accelerating along a legal route, preserving authored explicit orders.
{const b=arena();b.u.order=1;b.r.observe(b.u);b.f.move(b.u,1,0,.1,36);const x=b.u.x;assert(b.r.start(b.u,.01,{kind:'projectile',...bullet(b.u.x,380),dx:0,dy:1},b.terrain));assert(b.u.recon.dash.to.x>x);assert.equal(b.u.recon.dash.to.y,400);assert.equal(b.u.order,1);}
// Guard returns after evade and force attack-move resumes, with no firing during dash.
for(const mode of ['guard','force']){const b=arena();if(mode==='force')b.u.attackMove={x:800,y:400,force:true};b.s.bullets=[bullet()];b.elements['#pause'].onclick();for(let n=0;n<160;n++)b.f.update(.02);if(mode==='guard')assert(Math.hypot(b.u.x-400,b.u.y-400)<13);else{assert(b.u.x>470);assert(b.u.attackMove.force);}assert.equal(b.u.hp,1);}
{const b=arena();b.s.aliens=[{x:500,y:400,hp:100,type:'soldier',team:'alien',alive:true,cool:100,angle:Math.PI,stoppedUntil:100}];b.s.bullets=[bullet()];b.elements['#pause'].onclick();for(let n=0;n<120;n++)b.f.update(.02);assert(!b.u.recon.returning,'Guard returns even with an enemy still visible');assert(Math.hypot(b.u.x-400,b.u.y-400)<=13);}
{const b=arena();b.s.bullets=[bullet()];const t=b.s.t;b.f.update(.2);assert.equal(b.s.t,t);assert.equal(b.u.recon.dash,null,'Tactical pause does not grant evade');assert.equal(b.f.pickup(b.u,{type:'plasma'}),false);assert(b.f.selectable(b.u));}
// Newly closed route ends the evade before the damage gate, retaining spent cooldown.
{const b=arena();assert(b.r.start(b.u,0,melee,b.terrain));b.s.doors=[{x:398,y:403,w:4,h:4,open:false}];b.s.t=.1;assert(!b.r.step(b.u,.1,[],b.terrain));assert(!b.r.active(b.u,.1));assert.equal(b.u.recon.readyAt,3);b.f.damage(b.u,1,0,melee);assert(!b.u.alive);}
// Pausing an active dash freezes movement, immunity deadline and shared cooldown.
{const b=arena();b.s.bullets=[bullet()];b.elements['#pause'].onclick();b.f.update(.02);b.elements['#pause'].onclick();const before=plain(b.u.recon),pos={x:b.u.x,y:b.u.y},time=b.s.t;b.f.update(10);assert.equal(b.s.t,time);assert.deepEqual(plain(b.u.recon),before);assert.equal(b.u.x,pos.x);assert.equal(b.u.y,pos.y);b.elements['#pause'].onclick();b.f.update(.1);assert(b.u.y>pos.y);}
// Focus/use orders survive a dash and execute afterward using the ordinary order controller.
for(const mode of ['focus','use']){const b=arena(),target={x:500,y:400,hp:100,type:'soldier',team:'alien',alive:true,cool:100,angle:Math.PI,stoppedUntil:100};if(mode==='focus'){b.s.aliens=[target];b.u.focusTarget=target;b.u.order=2;}else{const terminal={x:440,y:400,object:257,key:'canopy-research-terminal',active:false};b.s.terminals=[terminal];b.u.useOrder={kind:'terminal',target:terminal,x:440,y:400,done:false};}const retained=mode==='focus'?b.u.focusTarget:b.u.useOrder;b.s.bullets=[bullet()];b.elements['#pause'].onclick();b.f.update(.02);assert.equal(mode==='focus'?b.u.focusTarget:b.u.useOrder,retained);for(let n=0;n<100;n++)b.f.update(.02);if(mode==='focus'){assert.equal(b.u.focusTarget,target);assert(target.hp<100);}else assert(b.s.terminals[0].active,'Retained use reaches terminal');}
// Conservative placement and world menu isolation preserve missions/objectives/headcount/pressure.
{const b=fresh();for(const d of ['veryeasy','easy','normal','hard','veryhard']){b.elements['#difficulty'].value=d;b.w.triumph.loadCustomMission('custom-jungle-canopy-recon');const s=b.w.__fixture().state,m=s.customMission,base=b.w.TriumphCustomMissions.get(m.id),p=b.w.TriumphCustomMissions.profiles[m.id][d];assert.equal(s.humans.length,4+p.soldiers);assert.equal(s.humans.filter(u=>u.type==='recon').length,1);assert.deepEqual(plain(m.recons),[[155,320]]);assert.deepEqual(plain(m.soldiers),plain(base.soldiers.slice(1,p.soldiers)));for(const key of ['objective','support','bugs','terrainId','rescueParty','ambushes'])assert.deepEqual(plain(m[key]),plain(base[key]),key);assert.deepEqual(plain(m.waves),plain(p.waves));assert.deepEqual(plain(m.nests),plain(p.nests));assert.equal(m.nestInterval,p.nestInterval);assert(!b.w.__fixture().blocked(155,320));}for(const m of b.w.TriumphCustomMissions.list){b.w.triumph.loadCustomMission(m.id);b.w.__fixture().state.mode='playing';b.elements['#reinforcements'].onclick();assert.equal(b.elements['#reinforcement-slots'].innerHTML.includes('value="recon"'),m.environment==='Jungle');b.elements['#reinforcement-close'].onclick();}}
// Actual support factories initialize Recon and enforce troop cap on ground and air landings.
for(const support of ['troops','air']){const b=fresh(),s=b.s,initial=s.humans.length,count=s.humans.filter(b.f.infantryType).length;s.rules.maxAliens=count+1;s.reinforcementCompositions[support]=Array(5).fill('recon');assert(b.f.reinforce(support));let landing=false;for(let i=0;i<1800;i++){s.t+=.04;b.f.updateSupport(.04);landing||=s.drops.length>0;}const arrivals=s.humans.slice(initial);assert.equal(arrivals.length,1);assert.equal(arrivals[0].type,'recon');assert(arrivals[0].recon);assert(arrivals[0].reinforcementCapSlot);assert.equal(b.f.reinforcementStatus(support).reason,'TROOPS FULL · WAIT FOR SPACE');if(support==='air')assert(landing);}
console.log('Passed production Recon prediction, legal swept evade, melee/immunity/cooldown, firing/orders/Guard, health eligibility, world roster and actual ground/air cap checks. Field Medic explicitly deferred; baseline health unchanged.');
