// Custom-authored Desert Rider rules and canvas silhouettes; no recovered assets.
(function(){
 'use strict';
 const rules=Object.freeze({scoutRange:62,scoutEvade:38,scoutSpeed:100,scoutCooldown:2.5,guardRange:120,guardCooldown:1.1,pelletDamage:1,pelletSpeed:290,pelletArc:Math.PI/6,repairRange:62,repairRate:.5,crawlerHP:6,crawlerRadius:17,crawlerSpeed:30,evadeAxis:32,evadeSpeed:100,evadeCooldown:2,mineAmmo:4,mineArm:.65,mineLife:30,mineTrigger:22,mineBlast:38,mineDamage:4});
 const types=['rider-scout','dune-guard','field-mechanic','convoy-crawler'],isRider=u=>types.includes(u?.type),radius=u=>u.type==='convoy-crawler'?rules.crawlerRadius:8,alive=u=>u.alive&&u.hp>0;
 function clear(x,y,r,blocked){for(let dx=-r;dx<=r;dx+=1)for(let dy=-r;dy<=r;dy+=1)if(blocked(x+dx,y+dy))return false;return true;}
 const policies=new WeakMap();
 function footprint(blocked,r){let byRadius=policies.get(blocked);if(!byRadius){byRadius=new Map();policies.set(blocked,byRadius);}if(!byRadius.has(r))byRadius.set(r,(x,y)=>!clear(x,y,r,blocked));return byRadius.get(r);}
 function sweep(u,goal,blocked){const d=Math.hypot(goal.x-u.x,goal.y-u.y);for(let n=0;n<=Math.ceil(d);n++){const f=d?n/Math.ceil(d):0;if(!clear(u.x+(goal.x-u.x)*f,u.y+(goal.y-u.y)*f,radius(u),blocked))return false;}return true;}
 function create(type,x,y,blocked,route=[]){if(!types.includes(type)||!Number.isFinite(x)||!Number.isFinite(y)||!clear(x,y,type==='convoy-crawler'?17:8,blocked))return null;return {type,x,y,team:'human',alive:true,hp:type==='convoy-crawler'?6:1,maxHP:type==='convoy-crawler'?6:1,id:0,angle:0,cool:0,order:3,leader:1,grenades:0,weapon:0,weaponTime:0,route:route.map(p=>({...p})),routeIndex:0,evadeCool:0,mineAmmo:type==='convoy-crawler'?rules.mineAmmo:0};}
 function travel(u,goal,speed,dt,blocked){const d=Math.hypot(goal.x-u.x,goal.y-u.y);if(!d)return true;const n=Math.min(d,speed*dt),next={x:u.x+(goal.x-u.x)/d*n,y:u.y+(goal.y-u.y)/d*n};if(!sweep(u,next,blocked))return false;u.angle=Math.atan2(goal.y-u.y,goal.x-u.x);u.x=next.x;u.y=next.y;return n===d;}
 function threat(u,w){const t=w.telegraph;if(!alive(w)||w.type!=='desert-worm'||!t||!['warning','charge'].includes(w.phase))return false;const along=(u.x-t.x)*t.dx+(u.y-t.y)*t.dy,across=Math.abs((u.x-t.x)*t.dy-(u.y-t.y)*t.dx);return along>=-radius(u)&&along<=t.range+radius(u)&&across<=t.width/2+radius(u);}
 function evade(u,goals,blocked,source){const goal=goals.find(p=>sweep(u,p,blocked));if(!goal)return false;u.evade={goal,start:{x:u.x,y:u.y},source};return true;}
 function pellets(u,target){const a=Math.round(Math.atan2(target.y-u.y,target.x-u.x)/(Math.PI/2))*Math.PI/2;u.angle=a;return [-2,-1,0,1,2].map(i=>{const angle=a+i*rules.pelletArc/4;return {x:u.x+Math.cos(angle)*10,y:u.y+Math.sin(angle)*10,dx:Math.cos(angle),dy:Math.sin(angle),team:'human',owner:u.id,life:rules.guardRange/rules.pelletSpeed,speed:rules.pelletSpeed,damage:rules.pelletDamage,desertPellet:true};});}
 function step(u,dt,env){if(!alive(u)||dt<=0||!isRider(u))return false;const {blocked,aliens,humans,mines,visible,route}=env;u.evadeCool=Math.max(0,u.evadeCool-dt);if(!env.sharedControls)u.cool=Math.max(0,u.cool-dt);
  if(u.type==='convoy-crawler'&&!u.evade){const w=aliens.find(w=>threat(u,w)&&u.lastTelegraph!==w.telegraph);if(w){u.lastTelegraph=w.telegraph;if(u.evadeCool<=0){const t=w.telegraph,axis=rules.evadeAxis;evade(u,[{x:u.x+t.dx*axis+t.dy*axis,y:u.y+t.dy*axis+t.dx*axis},{x:u.x+t.dx*axis-t.dy*axis,y:u.y+t.dy*axis-t.dx*axis},{x:u.x-t.dx*axis+t.dy*axis,y:u.y-t.dy*axis+t.dx*axis},{x:u.x-t.dx*axis-t.dy*axis,y:u.y-t.dy*axis-t.dx*axis}],blocked,w);}}}
  if(u.type==='rider-scout'&&!u.evade&&u.evadeCool<=0){const bug=aliens.filter(a=>alive(a)&&(a.type!=='desert-worm'||a.phase!=='burrow')&&visible(u,a)&&Math.hypot(a.x-u.x,a.y-u.y)<rules.scoutRange).sort((a,b)=>Math.hypot(a.x-u.x,a.y-u.y)-Math.hypot(b.x-u.x,b.y-u.y))[0];if(bug){const a=Math.atan2(u.y-bug.y,u.x-bug.x),t=bug.telegraph;const goals=t&&threat(u,bug)?[1,-1].map(sign=>({x:u.x+t.dy*rules.scoutEvade*sign,y:u.y+t.dx*rules.scoutEvade*sign})):[0,.6,-.6].map(o=>({x:u.x+Math.cos(a+o)*rules.scoutEvade,y:u.y+Math.sin(a+o)*rules.scoutEvade}));evade(u,goals,blocked,bug);}}
  if(u.evade){const e=u.evade,done=travel(u,e.goal,u.type==='convoy-crawler'?rules.evadeSpeed:rules.scoutSpeed,dt,blocked);if(done||!sweep(u,e.goal,blocked)){u.evade=null;u.evadeCool=u.type==='convoy-crawler'?rules.evadeCooldown:rules.scoutCooldown;if(done&&u.type==='convoy-crawler'&&u.mineAmmo>0&&clear(e.start.x,e.start.y,4,blocked)&&!mines.some(m=>Math.hypot(m.x-e.start.x,m.y-e.start.y)<12)){mines.push({x:e.start.x,y:e.start.y,age:0,owner:u.id});u.mineAmmo--;}}return true;}
  if(u.type==='convoy-crawler'){const goal=u.route[u.routeIndex];if(goal){if(Math.hypot(goal.x-u.x,goal.y-u.y)<=2)u.routeIndex++;else {const next=route(u,goal,footprint(blocked,radius(u)));if(next)travel(u,next,rules.crawlerSpeed,dt,blocked);}}return true;}
  if(u.type==='field-mechanic'){const vehicle=humans.filter(v=>alive(v)&&['tank','robot','convoy-crawler'].includes(v.type)&&v.hp<(v.maxHP||({tank:8,robot:7,'convoy-crawler':6}[v.type]))&&Math.hypot(v.x-u.x,v.y-u.y)<=rules.repairRange&&visible(u,v)).sort((a,b)=>a.hp-b.hp)[0];if(vehicle)vehicle.hp=Math.min(vehicle.maxHP||({tank:8,robot:7,'convoy-crawler':6}[vehicle.type]),vehicle.hp+rules.repairRate*dt);}
  return false;
 }
 function updateMines(mines,dt,{aliens,blocked,visible,damage,burst}){for(let i=mines.length-1;i>=0;i--){const m=mines[i];m.age+=dt;if(m.age>=rules.mineLife||!clear(m.x,m.y,4,blocked)){mines.splice(i,1);continue;}if(m.age<rules.mineArm)continue;const exposed=a=>alive(a)&&a.team==='alien'&&a.type!=='air'&&a.phase!=='burrow';if(!aliens.some(a=>exposed(a)&&Math.hypot(a.x-m.x,a.y-m.y)<=rules.mineTrigger&&visible(m,a)))continue;for(const a of aliens)if(exposed(a)&&Math.hypot(a.x-m.x,a.y-m.y)<=rules.mineBlast&&visible(m,a))damage(a,rules.mineDamage,m.owner);burst(m.x,m.y,rules.mineBlast);mines.splice(i,1);}}
 function draw(ctx,u){ctx.save();ctx.translate(Math.round(u.x),Math.round(u.y));if(u.type==='convoy-crawler'){ctx.fillStyle='#463d31';ctx.fillRect(-17,-17,34,34);ctx.fillStyle='#ba9357';ctx.fillRect(-13,-12,26,24);ctx.fillStyle='#d6c599';ctx.fillRect(-9,-8,18,16);ctx.fillStyle='#5f7470';ctx.fillRect(-7,-5,14,5);}else{ctx.fillStyle='#463d31';ctx.fillRect(-6,-4,12,14);ctx.fillStyle=({'rider-scout':'#b9b46e','dune-guard':'#bf8057','field-mechanic':'#75aaa0'})[u.type];ctx.fillRect(-7,-6,14,10);ctx.fillStyle='#dec69b';ctx.fillRect(-4,-12,8,6);ctx.rotate(u.angle);ctx.fillStyle='#292922';ctx.fillRect(3,-2,u.type==='dune-guard'?18:13,4);if(u.type==='field-mechanic'){ctx.fillStyle='#def2d5';ctx.fillRect(-2,-3,4,8);ctx.fillRect(-4,-1,8,4);}}ctx.restore();}
 window.TriumphDesertRiders=Object.freeze({rules,isRider,radius,clear,footprint,sweep,create,travel,threat,pellets,step,updateMines,draw});
})();
