'use strict';
const presets=[['KeyW','KeyS','KeyA','KeyD','KeyV','KeyB'],['KeyI','KeyK','KeyJ','KeyL','BracketLeft','BracketRight'],['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','NumpadMultiply','NumpadSubtract'],['Numpad8','Numpad5','Numpad4','Numpad6','Numpad0','Numpad1']];
window.TriumphInput={presets,createState:()=>({keys:new Set(),selection:new Set(),rallyMode:false,rallyPoints:[],nextRallyId:1,drag:null,moveMarker:null,lastMoveClick:null,activeCommander:null,mouseMode:'troops',mouseAim:null,modalPause:{}}),create(services){
const {getState,isPaused,setPaused,inputState,keys,selection,W,H,dist,nearest,blocked,focusCanvas,refreshPanel,interact,fire,grenade,selectable,enemyAt,usableAt,focusAttackTo,useOrderTo,attackMoveTo,giveOrder,advance,restartMission,presets,modalOpen,unlockAudio,capturePointer,releasePointer,move,rallyChoose,placeCharge}=services;
function toggleRally(){const s=getState(),paused=isPaused();if(s.mode!=='playing')return;inputState.chargeMode=false;inputState.rallyMode=!inputState.rallyMode;inputState.drag=null;inputState.mouseAim=null;keys.clear();inputState.lastMoveClick=null;focusCanvas();refreshPanel();}
function addRally(point){const s=getState(),paused=isPaused();if(point.x<12||point.x>W-12||point.y<44||point.y>=H-20||[[0,0],[-4,-4],[4,-4],[-4,4],[4,4]].some(([dx,dy])=>blocked(point.x+dx,point.y+dy)))return false;if(inputState.rallyPoints.some(p=>dist(p,point)<20))return false;inputState.rallyPoints.push({...point,id:inputState.nextRallyId++});return true;}
function removeRally(point){const s=getState(),paused=isPaused();const flag=nearest(point,inputState.rallyPoints,22);if(!flag)return false;inputState.rallyPoints.splice(inputState.rallyPoints.indexOf(flag),1);return true;}
function assignRally(u){const s=getState(),paused=isPaused();if(!['soldier','tank','robot'].includes(u.type))return;const best=rallyChoose(u,inputState.rallyPoints,s,blocked);if(best){u.attackMove={x:best.x,y:best.y,force:false,rally:best.id};u.order=2;u.patrol=null;}}
function selectedCommander(){const s=getState(),paused=isPaused();return s.humans.find(u=>u.type==='commander'&&u.id===inputState.activeCommander);}
function selectCommander(id){inputState.chargeMode=false;const s=getState(),paused=isPaused();const deselect=inputState.mouseMode==='commander'&&inputState.activeCommander===id;inputState.lastMoveClick=null;inputState.activeCommander=deselect?null:id;inputState.mouseMode=deselect?'troops':'commander';selection.clear();inputState.drag=null;inputState.mouseAim=null;keys.clear();const u=selectedCommander();if(u){u.external=null;u.selecting=false;}focusCanvas();refreshPanel();}
function updateMouseFire(u){const s=getState(),paused=isPaused();if(!inputState.drag?.mouseIntent||inputState.drag.selection||inputState.mouseMode!=='commander')return;if(!inputState.drag.firing&&s.t-inputState.drag.started>=.12){inputState.drag.firing=true;interact(u);}if(inputState.drag.firing){u.angle=Math.atan2(inputState.mouseAim.y-u.y,inputState.mouseAim.x-u.x);fire(u,true);}}
function mouseCommanderAction(point,isGrenade=false){const s=getState(),paused=isPaused();const u=selectedCommander();if(!u?.alive||paused||s.mode!=='playing')return;inputState.mouseAim=point;u.angle=Math.atan2(point.y-u.y,point.x-u.x);if(isGrenade){if((u.grenadeCool||0)<=s.t){grenade(u);u.grenadeCool=s.t+.330;}}else {interact(u);fire(u,true);}}
function selectTroops(a,b,add=false){const s=getState(),paused=isPaused();inputState.activeCommander=null;inputState.mouseMode='troops';inputState.mouseAim=null;keys.clear();inputState.lastMoveClick=null;if(!add)selection.clear();const small=dist(a,b)<6;if(small){const u=nearest(b,s.humans.filter(selectable),23);if(u){if(add&&selection.has(u))selection.delete(u);else selection.add(u);}}else {const left=Math.min(a.x,b.x),right=Math.max(a.x,b.x),top=Math.min(a.y,b.y),bottom=Math.max(a.y,b.y);for(const u of s.humans)if(selectable(u)&&u.x>=left&&u.x<=right&&u.y>=top&&u.y<=bottom)selection.add(u);}for(const u of selection)if(!selectable(u))selection.delete(u);}
function pointerdown(e){const s=getState(),paused=isPaused();if(s.mode!=='playing'||modalOpen())return;if(e.button!==0&&e.button!==2)return;e.preventDefault();focusCanvas();unlockAudio();const p=e.point;if(p.y<36)return;if(inputState.chargeMode){if(e.button===0)placeCharge(p);inputState.chargeMode=false;refreshPanel();return;}if(inputState.rallyMode){if(e.button===0)addRally(p);else removeRally(p);refreshPanel();return;}if(e.button===2){if(inputState.mouseMode==='troops'&&[...selection].some(selectable)){const now=e.timeStamp??s.t*1000,double=!!inputState.lastMoveClick&&now-inputState.lastMoveClick.time>=0&&now-inputState.lastMoveClick.time<350&&dist(p,inputState.lastMoveClick.point)<20,remembered=double?inputState.lastMoveClick.target:null,focus=remembered||enemyAt(p),usable=double?(inputState.lastMoveClick.usable||usableAt(p)):usableAt(p);if(focus){if(focus.alive!==false&&focus.hp>0)focusAttackTo(focus);}else if(double&&usable)useOrderTo(usable);else attackMoveTo(p,double);inputState.lastMoveClick=double?null:{time:now,point:p,target:focus,usable};}else mouseCommanderAction(p,true);return;}inputState.mouseAim=p;inputState.drag={start:p,end:p,add:e.shiftKey,id:e.pointerId,started:s.t,firing:false,selection:false,mouseIntent:!paused&&inputState.mouseMode==='commander'&&!e.shiftKey&&!nearest(p,s.humans.filter(selectable),23)};capturePointer(e.pointerId);}
function pointermove(e){const s=getState(),paused=isPaused();const p=e.point;if(inputState.drag&&e.pointerId===inputState.drag.id){inputState.drag.end=p;if(inputState.drag.firing)inputState.mouseAim=p;else if(dist(inputState.drag.start,p)>=6)inputState.drag.selection=true;}else if(inputState.mouseMode==='commander')inputState.mouseAim=p;}
function pointerup(e){const s=getState(),paused=isPaused();if(!inputState.drag||e.pointerId!==inputState.drag.id||e.button!==0)return;const ended=inputState.drag;inputState.drag=null;const p=e.point;if(s.mode==='playing'&&!ended.firing){if(ended.selection||dist(ended.start,p)>=6||nearest(p,s.humans.filter(selectable),23)||ended.add){selectTroops(ended.start,p,ended.add);inputState.mouseMode='troops';}else if(inputState.mouseMode==='commander')mouseCommanderAction(p);else {selection.clear();inputState.activeCommander=null;inputState.mouseMode='troops';}}releasePointer(e.pointerId);}
function pointercancel(){inputState.drag=null;}
function lostpointercapture(){inputState.drag=null;}
function keydown(e){const s=getState(),paused=isPaused();unlockAudio();if(modalOpen())return;if(presets.flat().includes(e.code)||['Space','Enter'].includes(e.code))e.preventDefault();const repeat=keys.has(e.code);keys.add(e.code);if(repeat||e.repeat)return;if(e.code==='KeyR'&&s.mode==='playing'){e.preventDefault();toggleRally();return;}if(e.code==='Escape'&&inputState.chargeMode){inputState.chargeMode=false;refreshPanel();return;}if(e.code==='Escape'&&inputState.rallyMode){e.preventDefault();toggleRally();return;}if(e.code==='Space'||e.code==='Escape'){setPaused(!paused);inputState.drag=null;}if(e.code==='Enter')advance();if(e.code==='F2'){e.preventDefault();restartMission();}if(s.mode==='playing'&&inputState.mouseMode==='commander')for(let i=0;i<4;i++){if(i+1!==inputState.activeCommander)continue;const u=s.humans.find(a=>a.id===i+1);const binding=i+1===inputState.activeCommander?presets[0]:presets[i];if(i===0&&inputState.activeCommander!==1)continue;if(u.selecting&&binding.slice(0,4).includes(e.code)){giveOrder(u,[2,3,0,1][binding.indexOf(e.code)]);continue;}if(e.code===binding[4]&&u.alive&&!paused)interact(u);if(e.code===binding[5]){const u=s.humans.find(a=>a.id===i+1);if(!u.alive)continue;if(keys.has(binding[4])&&!paused){grenade(u);u.grenadeCool=s.t+.330;}else u.selecting=true;}}}
function keyup(e){keys.delete(e.code);} function blur(){inputState.drag=null;keys.clear();if(getState().mode==='playing')setPaused(true);}
function directCommanderStep(u,dt){const s=getState();move(u,(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0),dt,85);if(inputState.mouseMode==='commander'&&inputState.mouseAim)u.angle=Math.atan2(inputState.mouseAim.y-u.y,inputState.mouseAim.x-u.x);updateMouseFire(u);if(keys.has('KeyV')&&keys.has('KeyB')){if((u.grenadeCool||0)<=s.t){grenade(u);u.grenadeCool=s.t+.330;}}else if(keys.has('KeyV'))fire(u,inputState.mouseMode==='commander'&&!!inputState.mouseAim);}
function reset(){inputState.chargeMode=false;inputState.rallyMode=false;inputState.rallyPoints=[];inputState.nextRallyId=1;inputState.lastMoveClick=null;selection.clear();inputState.drag=null;inputState.moveMarker=null;inputState.activeCommander=null;inputState.mouseMode='troops';inputState.mouseAim=null;keys.clear();}
function openModal(kind){inputState.modalPause[kind]=isPaused();setPaused(true);inputState.drag=null;keys.clear();}
function closeModal(kind,clear=false){setPaused(inputState.modalPause[kind]);if(clear){keys.clear();inputState.drag=null;}focusCanvas();}
function tactical(){setPaused(!isPaused());inputState.drag=null;focusCanvas();}
return {reset,openModal,closeModal,tactical,directCommanderStep,toggleRally,addRally,removeRally,assignRally,selectedCommander,selectCommander,updateMouseFire,mouseCommanderAction,selectTroops,pointerdown,pointermove,pointerup,pointercancel,lostpointercapture,keydown,keyup,blur};
}};
