'use strict';
// Pure progress calculation shared by the HUD and automatic victory.
window.TriumphMissions={
 createWaves(m){const arrivals=m.waves.flatMap(w=>Array.from({length:w.bugsPerPoint},()=>w.points.map(([x,y])=>({at:w.at,x,y}))).flat());return {arrivals,index:0,queue:[],emitted:0,next:0};},
 emitWaves(s,spawn){const w=s.customWaves;if(!w)return;while(w.index<w.arrivals.length&&w.arrivals[w.index].at<=s.t)w.queue.push(w.arrivals[w.index++]);while(w.queue.length){w.next=Math.max(w.next,w.queue[0].at);if(w.next>s.t)break;if(s.aliens.length>=(s.rules?.maxAliens||50)){w.next=s.t+.5;break;}const p=w.queue.shift();spawn(p.x,p.y);w.emitted++;w.next+=.5;}},
 progress(s){
 if(s.customMission?.objective.rescueCrawlers){const e=s.customMission.objective.rescueCrawlers,crawlers=s.humans.filter(u=>u.rescue&&u.type==='convoy-crawler');const extracted=c=>c.alive&&c.hp>0&&c.repaired&&!c.disabled&&c.routeIndex>=c.route.length&&Math.hypot(c.x-e.x,c.y-e.y)<=e.radius,rescued=crawlers.filter(extracted).length,living=crawlers.filter(c=>c.alive&&c.hp>0),noMechanic=!s.humans.some(u=>u.alive&&u.hp>0&&u.type==='field-mechanic'),stranded=living.length>0&&living.every(c=>c.disabled&&c.hp<6)&&noMechanic,lost=crawlers.length===2&&(!living.length||stranded);return {rescued,lost,stranded,ready:rescued>0,label:stranded?'RESCUE FAILED · no mechanic to repair convoy':crawlers.map(c=>`C${c.convoyNumber} ${!c.alive||c.hp<=0?'LOST':extracted(c)?'SAVED':c.disabled?'REPAIR '+c.hp.toFixed(1)+'/6':(c.escorted?'ESCORT':'NEEDS ESCORT')+' '+Math.min(c.routeIndex,c.route.length)+'/'+c.route.length}`).join(' · ')};}

 if(s.customMission?.objective.rescueSoldiers){const o=s.customMission.objective,e=o.rescueSoldiers.extraction,relay=(o.activate||['station-relay']).every(key=>s.terminals.some(t=>t.key===key&&t.active)),living=s.humans.filter(u=>u.rescueSurvivor&&u.alive&&u.hp>0),saved=living.filter(u=>Math.hypot(u.x-e.x,u.y-e.y)<=e.radius).length,lost=s.rescueAcquired&&!living.length;return {relay,acquired:!!s.rescueAcquired,living:living.length,saved,lost,ready:relay&&s.rescueAcquired&&saved>0,label:lost?'RESCUE FAILED · designated party lost':!relay?'Activate required terminal':!s.rescueAcquired?(s.humans.filter(u=>u.alive&&u.type!=='commander'&&u.type!=='combat-drone').length+s.drops.filter(d=>!d.finished).length+3>s.rules.maxAliens?'Party waits · need 3 free army slots':'Approach stranded party (70 px)'):saved?'Survivor extracted':`Return survivor · ${living.length}/3 living`};}
 if(s.customMission?.objective.extractLivingGroundHumans){const o=s.customMission.objective,e=o.extractLivingGroundHumans,living=s.humans.filter(u=>u.alive),outside=living.filter(u=>Math.hypot(u.x-e.x,u.y-e.y)>e.radius).length,used=(o.use||[]).filter(key=>!s.terminals.some(t=>t.key===key&&t.used)).length,terminals=(o.activate||[]).filter(key=>!s.terminals.some(t=>t.key===key&&t.active)).length,support=Number(!!s.customAirPending)+s.reinforcements.filter(r=>!r.finished).length+s.drops.filter(d=>!d.finished).length,survivor=living.filter(u=>u.type!=='commander'&&u.type!=='combat-drone').length>=e.minimumNonCommanders,pending=[];if(used)pending.push('access unlock');if(terminals)pending.push('laser activation');if(outside)pending.push(`${outside} humans outside extraction`);if(!survivor)pending.push('no surviving army');if(support)pending.push(`${support} support inbound`);return {used,terminals,outside,support,survivor,ready:pending.length===0,label:pending.length?'Remaining: '+pending.join(' · '):'Silent Return secured · army extracted'};}
 if(s.customMission){const bugs=s.aliens.filter(a=>a.alive&&a.hp>0).length,nests=s.nests.filter(n=>n.hp>0&&n.birthsRemaining!==0).length,source=s.nests.reduce((sum,n)=>sum+(n.hp>0?(n.birthsRemaining||0):0),0),vents=s.vents?.length||0,terminals=s.customMission.objective.activate?.filter(key=>!s.terminals.some(t=>t.key===key&&t.active)).length||0,wave=s.customWaves?s.customWaves.arrivals.length-s.customWaves.emitted:0,wait=Math.max(0,(s.customMission.objective.minimumTime||0)-s.t),survivor=!s.customMission.objective.atLeastOneNonCommander||s.humans.some(u=>u.alive&&u.type!=='commander'&&u.type!=='combat-drone');const relief=s.customMission.objective.reliefDelivered?(Number(!!s.customAirPending)+s.reinforcements.filter(r=>!r.finished).length+s.drops.filter(d=>!d.finished).length):0;const pending=[];if(relief)pending.push(`${relief} relief inbound`);if(source)pending.push(`${source} nest births`);if(wave)pending.push(`${wave} arrivals`);if(wait)pending.push(`wait ${Math.ceil(wait)}s`);if(!survivor)pending.push('no surviving army');if(terminals)pending.push(`${terminals} relays`);if(nests)pending.push(`${nests} nests`);if(bugs)pending.push(`${bugs} bugs`);if(vents)pending.push(`${vents} transitioning bugs`);return {bugs,nests,...(s.customMission.objective.reliefDelivered?{relief}:{}),...(s.customMission.nestBudget===undefined?{}:{source}),vents,terminals,wave,wait,crystal:false,ready:pending.length===0,label:['custom-abandoned-ruin-terraces','custom-orbital-derelict-relay-strike'].includes(s.customMission.id)?(pending.length?`Relays ${2-terminals}/2 · nests ${nests} · births ${source} · bugs ${bugs}`:'Relays secured · area clear'):pending.length?'Remaining: '+pending.join(' · '):s.customMission.role==='capital-defense'?'District secured - transit open':s.customMission.role==='harbor-defense'?'Harbor secured - area clear':s.customMission.role==='defense'?'Convoy secured · area clear':'Relays secured · area clear'};}
 const bugs=s.aliens.filter(a=>a.alive&&a.hp>0).length,nests=s.nests.filter(n=>n.hp>0).length,wave=s.wave?Math.max(0,s.wave.normalKills-s.waveKills.normal)+Math.max(0,s.wave.queenKills-s.waveKills.queen):0,terminals=s.originalMap?(s.rules?.victoryTerminals||[]).filter(id=>!s.terminals.some(t=>t.object===id&&t.active)).length:0,wait=Math.max(s.hold||0,Math.max(0,(s.rules?.minimumTime||0)-s.t)),crystal=s.originalMap&&s.level===8?!s.crystal?.recovered:!s.originalMap&&s.level===7?!s.crystal?.recovered:false;
 const vents=s.vents?.length||0;
 const pending=[];if(vents)pending.push(vents+' ceiling / transitioning bugs');if(bugs)pending.push(`${bugs} bugs`);if(nests)pending.push(`${nests} nests`);if(wave)pending.push(`${wave} wave`);if(terminals)pending.push(`${terminals} terminals`);if(wait>0)pending.push(`wait ${Math.ceil(wait)}s`);if(crystal)pending.push('crystal extraction');
 return {bugs,vents,nests,wave,terminals,wait,crystal,ready:pending.length===0,label:pending.length?'Remaining: '+pending.join(' · '):'Area clear'};
}};
